UPDATE products SET brand = 'Farmatodo' WHERE name = 'Solucion Farmatodo Citrato De Potasio 10.8% Frambuesa 1Lt';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Solucion Farmatodo Citrato De Potasio 10.8% 1Lt';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Solucion Farmatodo Citrato De Potasio Frambuesa 1Lt';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Solucion Farmatodo Citrato De Potasio 10% 1Lt';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Glicerina Farmatodo 60Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Locion Farmatodo Facial Limpiadora 120Cc';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'K6' WHERE name = 'TOBILLERA AJUST NEOP K6 T-M';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Inmovilizador Dynamics Brazo Plus T-u';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina C 1000 mg Letisan Leti';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 1% Calox Crema Tópica x 20 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C + Zinc';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Locion Farmatodo Facial Dia 120Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Jengibre 120Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Merey Premium sin Sal Tostado en Hornos Grupo Cashew x 250 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Zabila Jengibre Miel 120Cc';
UPDATE products SET brand = 'Laproff' WHERE name = 'Sulfato Ferroso Hierro 300 mg Laproff Blíster x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Merey Premium Con Sal Tostado En Hornos Grupo Cashew x 250 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Palitos de Vegetales Sin gluten Sensibly Natural Con Sal Marina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Lamedor Jengibre Miel 120Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Citrato Potasio 10% 1Lt';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Citrato Potasio Frambuesa 10% 1Lt';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Solucion Farmatodo Hiposulfito De Sodio 10% 120Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Pasta Farmatodo Zing Al Agua';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente de Lectura Optiko 3.5 Colores Surtidos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartán Medoxomil 20 mg Biocor MCK Pharmaceutical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clobetasol 0.05%  SGG Ungüento';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D 2000 UI DarliDe Fc Laboratorios';
UPDATE products SET brand = 'Europharm' WHERE name = 'Sutura Adhesiva Eurofarm Eurosuture 3X75Mm';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Lamedor Zabila 120Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Achicoria 120Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Crema Farmatodo Azahares';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Agua Farmatodo De Azahares 120Cc';
UPDATE products SET brand = 'K6' WHERE name = 'Vendaje Deportivo Autoadhesivo Surtidos K6 5cm X 4.5m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica Saito Ortopedica 8Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartán Medoxomil 40 mg Biocor MCK Pharmaceutical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Medipatch Dolor Menstrual 3 Und';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Cloruro De Magnesio Solución Fresa x 240 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jabón Ácido Hialurónico y Niacinamida x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Sensitive Frasco x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Kx Elastica Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Kx Elastica Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tadalafilo 20 mg Fitex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Kx Con Estabilizador Del Pulgar';
UPDATE products SET brand = 'ASK' WHERE name = 'Cuerda De Saltar Ask';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Uvipiel Gel x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Violeta de Genciana Contra Hongos e Infecciones Recette Mark Aerosol Lata x 70 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Transparente Microperforado Zuviss 5cm x 9,10m x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas, Banditas Adhesivas 72x22mm 100unidades Two5med';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Jabon Liquido Farmatodo Glicolisado';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Antiedad Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Gotas Para Circulación Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Kx De Neopreno Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmov Bsn Brazo M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cuticell Class 10x40 Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vaselina Deportiva Free Life Style';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Dynaven Sigvaris Beige Talla M 15-20 Pantorrilla x 2 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mentol Davis Plus Tarro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Saludable Sin gluten Papas El Valle Premium sabor Trufa Negra';
UPDATE products SET brand = 'Valmor' WHERE name = 'Clonazepam 0,5 mg Clonzep Valmor';
UPDATE products SET brand = 'Vincenti' WHERE name = 'Glibenclamida 5 mg Vincenti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas, Banditas Adhesivas para Niños estampadas 72x22mm 100unidades Two5med';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Saludable Sin gluten Papas El Valle sabor Jamon';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante Truvia Natural Sweetner Cargill';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Cejas Y Pestañas';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Champu Farmatodo Antiseborreico';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Aceite Farmatodo De Coco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gabapentina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetilpiridinio + Lidocaina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite de Alhucema';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gel Cristal De Zabila x 90 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Toallita de Alcohol Briutcare 20Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitamínico Hierro Ferronorm Medifarm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida + Vitamina B6';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Super Clinica';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema Lifting x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collarin Blando Kx Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica 8Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Extra Fuerte 16 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miovit';
UPDATE products SET brand = 'Calox' WHERE name = 'Olmesartán Medoxomilo 40 mg Calox x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'VastarUni Mr Diclorhidrato de Trimetazidina 35 mg Unipharma x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Almendra Hidratante Recette Mark Aerosol Lata x 70 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Uvipiel Crema x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'SGG Gel Peroxido de Benzoilo 5%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Candesartan Cilexitilo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Yodopovidona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kalan obleas de amaranto sin azúcar y sin gluten sabor Coco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bolsa Compresa Kx';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema De Nacar Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Solucion Farmatodo Topica Bucal';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Agua Hammamelis Frasco x 200 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Tonico Farmatodo Facial Noche';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Locion Farmatodo Limpiadora Piel Grasa';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Para Psoriasis Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Champu Farmatodo Anticaida';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Jabon Liquido Farmatodo Intimo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Elastica Almohadillas Silicon Kx Sin Latex Talla P';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Aceite De Almendras Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Jabón Avena Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiocolchicosido';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Tintura de Árnica Frasco x 30 ml';
UPDATE products SET brand = 'Europharm' WHERE name = 'Adhesivo Eurosilk Eurofarm 5cm x 5m';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Alcohol Farmatodo Alcanforado 120Cc';
UPDATE products SET brand = 'ASK' WHERE name = 'Bandas de resistencia ASK 3und';
UPDATE products SET brand = 'Farmatodo' WHERE name = '!!Formula Farmatodo Jabon Niacinamida + Acido Hialuronico';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Serum Peeling Face Frasco x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Agua Micelar Bifasica Frasco x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Ricino Recette Mark Aerosol Lata x 70 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clindamicina 1% Spefar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Corrector Nasal Talla U 1 Par Pura+';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jabón Facial De Rosas Farmatodo Frasco x 100 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Coco Corporal/Capilar Recette Mark Aerosol Lata x 70 ml';
UPDATE products SET brand = 'JHC' WHERE name = 'VPD Andadera Adaptable JHC Médica x 1 Unidad';
UPDATE products SET brand = 'JHC' WHERE name = 'VPD Silla De Ruedas Estándar JHC Medica x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ladrillo para Yoga Live&Fit';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Tónico Facial Hipoalérgenico x 100 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jabón Facial Hipoalérgenico x 100 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Crema Exfoliante Limpiadora Pieles Sensibles Frasco x 60 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum Lifting x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Contorno De Ojos Hipoalérgenico Crema x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum Multivitamínico con Protector Solar x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Para Unas Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Capilar Reparador Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Urifex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clobetazol 0,05% Dermazol Medihealth Ungüento x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Champu Farmatodo Anticaspa';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Desmaquillante Bifásico Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Acido Hialuronico Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Baño De Crema Reparador x 100 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Gel Aclarante De Machas Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Serum Regenerador';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Crema Exfoliante Limpiadora De Nacar';
UPDATE products SET brand = 'Unknown' WHERE name = 'RecetteMark Azul de Metileno Spray Antiseptico';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Gel Antibacterial Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ecomed+ Dispositvo Anti-asfixia 1und';
UPDATE products SET brand = 'Unknown' WHERE name = 'H2off Protector Para Yesos Y Vendajes Pierna';
UPDATE products SET brand = 'Unknown' WHERE name = 'H2off Protector Para Yesos Y Vendajes Brazo';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Crema Farmatodo Corporal De Nacar';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Acondicionador Farmatodo Reparador';
UPDATE products SET brand = 'Unknown' WHERE name = 'FLORES DE BACH OLIVE';
UPDATE products SET brand = 'Unknown' WHERE name = 'FLORES DE BACH RESCATE SLEEP';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nifedipina 30 mg Distrilab';
UPDATE products SET brand = 'Valmor' WHERE name = 'Naclodin Clonidina Clorhidrato 0,150mg Valmor x 30';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 1% Imazol Siegfried Spray Tópico x 25 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Clotrimazol 1% Genven Crema Tópica x 20 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'FLORES DE BACH RESCATE';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Locion Farmatodo Para Lechina';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Clodoxin Metoclopramida 10 mg + Vitamina B6 Plusandex x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nitrofurantoina 50 mg Dac x 30';
UPDATE products SET brand = 'K6' WHERE name = 'Mancuerna 7 LB de Vinil K6';
UPDATE products SET brand = 'K6' WHERE name = 'Mancuerna 5LB de Vinil K6';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Exfoliante Limpiadora Coconuez Tarro x 60 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Acondicionador Farmatodo Anticaida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tapones de Oidos Para Natacion Niños TYR';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gel Facial Hidratante Con Protector Solar x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Crema Farmatodo Acido Glicolico Al 10%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Oro Sin Gluten Bailarina';
UPDATE products SET brand = 'ASK' WHERE name = 'Banda de Resistencia Fuerte Ask';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Talco Para Pies Farmatodo x 60 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Facial Antioxidante Frasco x 30 gr';
UPDATE products SET brand = 'ASK' WHERE name = 'Yoga Mat TPE 4mm Ask';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Loción Desmaquillante Bifásico Frasco x';
UPDATE products SET brand = 'K6' WHERE name = 'Kit de entrenamiento en casa K6';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Loción Afeitado x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gel Piernas Cansadas x 100 gr';
UPDATE products SET brand = 'ASK' WHERE name = 'Set de Ligas de Resistencia Ask';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite Mineral';
UPDATE products SET brand = 'ASK' WHERE name = 'Barra de Flexiones Ask';
UPDATE products SET brand = 'ASK' WHERE name = 'Soporte de Rotula Ask';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nifedipina 20 mg Lattan Medic';
UPDATE products SET brand = 'K6' WHERE name = 'Ejercitador de Antebrazo K6 Hand Grip';
UPDATE products SET brand = 'ASK' WHERE name = 'Pesas Ask Muñequera Tobillera 2Kg';
UPDATE products SET brand = 'ASK' WHERE name = 'Pelota de Yoga 65cm 9" Ask';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Crema Farmatodo Pañalitis Plus';
UPDATE products SET brand = 'K6' WHERE name = 'Banda de Resistencia K6 L1';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Repelente Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Aceite Ricino Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Exfoliante Labial Frasco x 8 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Jabon Aloe Y Manzanilla Frasco x';
UPDATE products SET brand = 'La Santé' WHERE name = 'Rifaximina 550 mg Rixigal Pharmetique Labs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nimodipina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Serum Farmatodo Acido Hialuronico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite De Oliva Henri Mor Extra Virgen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidroxido de Magnesio Polantac Antiacido 20';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidróxido de Aluminio + Hidróxido de Magnesio + Simeticona';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Carbonato De Calcio 750 mg Aplacal Siegfried Antiácido Sabor Frambuesa x 10';
UPDATE products SET brand = 'Calox' WHERE name = 'Carbonato de Calcio 500 mg Frutacid Antiácido Calox Frasco x 60';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina Mailen Jarabe 0,5 mg/mL x 50 mL';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Hidragel Facial Hidrarante x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Hidracream Facial Hidrarante Frasco x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Suero Farmatodo Oral';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Locion Azufrada Tarro x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Silkplast 5Cm X';
UPDATE products SET brand = 'Dixson' WHERE name = 'Pesa Tobillera Azul 3kg Dixson';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pelotas de Tenis Wilson US Open Tubo 4 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Bactericida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Cohesiva Vendapress';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Champú para piojos Tarro x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Crema Farmatodo Manos Hidratante';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jabón Ozonizado x 60 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Cereza';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parches Oculares Pharmalast Cure Aid Plester Animado 20 Unidades';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Loción Dermolimpiadora Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parches Oculares Pharmalast Cure Aid Plester Adulto 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levodropropizina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Aceite Ozonizado Fórmula Magistral Farmatodo Crema Ozonizada';
UPDATE products SET brand = 'Europharm' WHERE name = 'Curita Aloe Eurostrips Eurofarm 19X72Mm 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Uva';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vendas Adhesivas Cure Aid Transpiel 20 Unidades';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Crema Farmatodo Clorhidrato De Aluminio';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Aceite Farmatodo De Ricino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Arnica gotas';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gel Farmatodo De Arnica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Dynamics Neopreno';
UPDATE products SET brand = '3M' WHERE name = 'Yoga Mat 3mm Azul';
UPDATE products SET brand = 'Unknown' WHERE name = 'Termo Kangooplus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Termo Kangooplus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cincha para codo Dynamics Neopreno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Nepafenac 0,1% Nevac Oftalmi Suspensión Oftálmica x 5 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Refrescante Calaminol Fresh Gel Para Quemaduras De Sol x 90 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Dynamics neopreno con ferula transparente';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite Alcanforado Frasco x 60 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tintura De Yodo';
UPDATE products SET brand = 'Unknown' WHERE name = 'RECETTEMARK ALCOHOL YODADO 30 CC';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Muslo 18-23 mmHg Talla 3 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Muslo 18-23 mmHg Talla 2 Color Daino';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Nutricream Facial De Nacar Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'FARMATODO GEL CUTIS GRASO';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'FARMATODO CF ANTIEDAD NOCHE';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lagrifresh';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nistatina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aciclovir';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gotas Farmatodo Del Carmen';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Pomada Farmatodo Arnica';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gotas Farmatodo Valeriana 60Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'FLORES DE BACH WHITE CHESNUT';
UPDATE products SET brand = 'Calox' WHERE name = 'Omeprazol 20 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Europore Microporoso 1" x 10yd Blanco Eurociencia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Linaza Molina Pro Salud';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mat De Yoga Shuangyou';
UPDATE products SET brand = 'Unknown' WHERE name = 'CUERDA P/SALTAR (JUMP ROPE) AZUL';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'FARMATODO CF ANTIEDAD DIA';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Meropenem 1 g Green Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olanzapina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olanzapina 10 mg Psicofarma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Sin Gluten Crispy Rice Nature''s Path x 325 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Racecadotrilo 10 mg Resecal Diskam';
UPDATE products SET brand = 'K6' WHERE name = 'Tobillera Ajustable De Neopreno K6 Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Elastica Blanca Jogger T/M';
UPDATE products SET brand = 'Unknown' WHERE name = 'CODERA AJUSTABLE NEOPRENE BODY T/U';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Forma Elastica Para Hombro Femenino Talla Xl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Con Ferula Forma Elastica Derecha Talla Xl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera con ferula Forma Elastica derecha Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gypsona Venda De Yeso 8" (3ydas)';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gypsona Venda Yeso 6"x3ydas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sirope organico de Agave Sugar Krush';
UPDATE products SET brand = 'Leti' WHERE name = 'Omeprazol 40 mg Genven';
UPDATE products SET brand = 'Kimiceg' WHERE name = 'Ketoconazol 2% Kimiceg Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nitrofurantoina 100 mg Cleo';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Carbonato De Calcio 750 mg Aplacal Siegfried Antiácido Menta Blíster x 4';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cromus 0.1%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clotrigen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Dynamics con almohadilla de silicon talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Dynamics con almohadilla de silicon talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Elast Jogger 2 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bolsa Compresa Para Hielo Kx Tobillo/Rodilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra De Proteina Nugo Espresso';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Tobramicina 0.3% Medigen Oftalmi Solución Oftálmica x 5 ml';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Olopatadina Kuara 0,2% Solucion Oftalmica';
UPDATE products SET brand = 'SNC Pharma' WHERE name = 'Pramipexol 1 mg Kolzide SNC Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hexamidina + Lidocaína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carbocisteína Loganil';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bolsa compresa para hielo KX';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Pasta Capelli Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hedera Helix';
UPDATE products SET brand = 'Intervit' WHERE name = 'Therma Gel Intervit Circular';
UPDATE products SET brand = 'Intervit' WHERE name = 'Therma Gel Intervit Clinica';
UPDATE products SET brand = 'Intervit' WHERE name = 'Therma Gel Intervit Cue/Hombros';
UPDATE products SET brand = 'Unknown' WHERE name = 'Set de Pedales Pro R650';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hedera Helix 0,7% Teratosil Jarabe Miel Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bks Bomba Portatil Bicicleta P150';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Algodón Hombre Rodilla 18-23 mmHg Talla 5 Color Azul';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasas 4x4 Algobap';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Steritex Rollo 500 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante organico de cristal de Agave Sugar Krush';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Oximetazolina 0,255% Clarix Oftalmi Solución Oftálmica Colirio x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Inmovilizadora Zuviss Fibra De Vidrio 7.5cm x 3.6m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pelota De Padel Wilson';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Elevador Sanitario Con Seguro Dovant x 1 und';
UPDATE products SET brand = 'Vick' WHERE name = 'Vick Vaporub Tarro Ungüento x 100 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pelota Padel Performance';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Super Crystal';
UPDATE products SET brand = 'Pan' WHERE name = 'Mezcla para panquecas sin gluten Pancake Fit Coco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias de Compresion Deportivas Training Start Talla L Sportlast';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias de Compresion Deportivas Training Pro Talla M Sportlast';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias de Compresion Deportivas Training Pro Talla L Sportlast';
UPDATE products SET brand = 'Pan' WHERE name = 'Mezcla para panquecas sin gluten Pancake Kids Vainilla';
UPDATE products SET brand = 'La Santé' WHERE name = 'Irbesartan 150 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante Hermesetas Azul 300comprimidos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida Greenstar Leche de Almendras 1Lt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sensor para monitoreo de Glucosa Aidex GSM';
UPDATE products SET brand = 'Unknown' WHERE name = 'Termo para Agua';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Comprimido Nunu Sin Azucar Sabor Granada-Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Tiocolchicosido';
UPDATE products SET brand = 'Unknown' WHERE name = 'Superalimento Semillas De Chía Naru';
UPDATE products SET brand = 'SPL' WHERE name = 'Edulcorante Splenda';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Negra K6 Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suprasorb F Lamina Adhesiva Transparente 10x12cm 10Unidades';
UPDATE products SET brand = 'Calox' WHERE name = 'Losartán Potásico 50 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lisina + Ciclobenzaprina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartan Potasico';
UPDATE products SET brand = 'La Santé' WHERE name = 'Omeprazol 20 mg La Santé x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Irbesartan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mesageloof Mesalazina 500 mg Geloof Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Dexx 4X4 Cm 2 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'V-Balanced';
UPDATE products SET brand = 'Unknown' WHERE name = 'Muscle Force Maximo Crecimiento Desarrollo y Rendimiento Muscular';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sinacid Hidróxido de Aluminio + Hidróxido de Magnesio + Simeticona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Triamcinolona 55 mcg Itacort AQ Alpine Suspensión Nasal Spray x 120 Dosis';
UPDATE products SET brand = 'Unknown' WHERE name = 'ALG ALVE MOTA 100 G';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla de Ruedas Estándar Acero 120kg Next Step';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Fusilli La';
UPDATE products SET brand = 'Going' WHERE name = 'Gel Energético Granada Going 33 gr x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Comprimido Nunu Sin Azucar Sabor Limon-Frambuesa';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Neurixa Pregabalina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Maalox Plus Menta';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Spaguetti Gluten Free La Molisana';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina De Huevo Lifesystem Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante De Sucralosa Montalbán 0 Calorías x 112 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chips De Maiz Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada St Dalfour Cuatro Frutas x 284 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Aimdent Sin Azucar Sabor Canela 18 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche de Almendras Vilay Sin Azucar Sin Gluten/Sin Lactosa 1 Litro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Obleas de Amaranto Bites Vainilla Sin Azúcar Sin Gluten Halo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ñam Suspiros Light Sabor Limon';
UPDATE products SET brand = 'La Santé' WHERE name = 'Ambroxol 30 mg La Sante Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol Ogastan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Saludable Sin gluten Papas El Valle Premium sabor Aceite de Oliva';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Quinoa y Chia Nnova Rice';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína NutriClara de Huevo Sabor Original';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Salbutamol Salburol Solución Nebulizar 0,5%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Té de Carbon Activado a base de Matcha Ochamatcha';
UPDATE products SET brand = 'Unknown' WHERE name = 'Té Saludable de Jengibre y Curcuma a Base de Matcha Ceremonial Ochamatcha';
UPDATE products SET brand = 'Unknown' WHERE name = 'Papas Saludable Sin gluten El Valle Supreme sabor Jamon';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol 40 mg Distrilab Polvo Solución Inyectable x 1 Vial';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Proteina Dark NuGo Choco Almendra';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply7 Chips de Quinoa Sabor a Crema agria y Cebolla';
UPDATE products SET brand = 'SPL' WHERE name = 'Edulcorante Líquido Splenda Stevia x 50 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida Greenstar Leche de Arroz-Avellanas 1Lt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Drospirenona + Etinilestradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olanzapina';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina D3 5000 UI Diglet Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel De Abeja Sweetbees Sobre x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diclofenac Potasico Diclofenac Potasico';
UPDATE products SET brand = 'Novartis' WHERE name = 'Valsartan Novartis 160 Mg 28';
UPDATE products SET brand = 'Vivax' WHERE name = 'Isotretinoina 10 mg Cuticlin Vivax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Isotretinoína 20 mg Cuticlin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Iodinex Solucion Topica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Iodinex Solucion Jabonosa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D3 Diglet 1000 Ui X 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche de Almendras Sin Azucar Scotti 1lt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quinoa Royal Tricolor Andean Food x 500 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Tiocolchicosido';
UPDATE products SET brand = 'La Santé' WHERE name = 'Omeprazol 40 mg La Sante';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dicigel Reformulado Antiácido Suspensión Oral Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Rosquitas De Quinoa Horneadas Picantes';
UPDATE products SET brand = 'Unknown' WHERE name = 'Infusion Natural Insodel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostado The Pod Snacks Sabor A Miel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curcuma Ecobenefit Mezcla De Curcuma Con Pimienta 1 Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante Truvia Stevia Frasco x 280 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida';
UPDATE products SET brand = 'Polinac' WHERE name = 'Centella Asiática 10 mg Madecassol Polinac';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema Untable A Base De Mani';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketoconazol 2%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Caballero Metal +1.50';
UPDATE products SET brand = 'Unknown' WHERE name = 'Stevia Deshidratada Delta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Helios Diet Sin Azúcar Frutas Del Bosque x 280 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tortitas de Arroz 3 Pack Arandanos Choco Negro Sin Gluten Santiveri';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cacao En Polvo S/Azúcar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada St Dalfour Manzana Y Canela x 284 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cascara Sagrada Nat';
UPDATE products SET brand = 'La Santé' WHERE name = 'Orlistat 120 mg Xerograx Pharmetique Labs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetron';
UPDATE products SET brand = 'Unknown' WHERE name = 'Imiquimod 5% Virosupril Medihealth Crema x 5 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche Condensada En Polvo Sin Azucar Hiki 250 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Oximetazolina 0,05% Clarix Oftalmi Spray Nasal Descongestionante x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carboximetilcisteina Mucofar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol Praome-Es';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida en polvo Frutilike Fresa S/Azucar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra De Proteina Nugo Crema De Mani';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Pasta Penne Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Naranja';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento alimenticio Enterex Hepatic Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oxolamina Citrato';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alimento De Soya Klim';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clenbuterol Clorhidrato 0.01mg/5ml Bioquimica Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Gammaf Prokal Glutami';
UPDATE products SET brand = 'Unknown' WHERE name = 'RecetteMark Iodopovidona 10% Spray Antiseptico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nueces Muscle Granola x 200 gr';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin gluten Farina Schar 1kg';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin gluten Wafer Pocket Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Adultos Mayores Con Fibra';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketoprofeno Ronamedic';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ceregen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Sin Azúcar Falidu Sabor Uva, Limón, Naranja Y Parchita x 55 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pizza Bites Masa de Yuca Libre De Gluten Que Bites x 15 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mix Energizer Snak Club x 191 gr';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Sal Rosa Himalaya';
UPDATE products SET brand = 'Unknown' WHERE name = 'Enrollados Laminado Frolls Guayaba';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Cloruro de Sodio 0,90% JL Pharma Frasco x 500 ml';
UPDATE products SET brand = 'La Santé' WHERE name = 'Claritromicina 500 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cafe Descafeinado Anzoategui';
UPDATE products SET brand = 'La Santé' WHERE name = 'Ketorolaco Trometamina 30 mg La Santé';
UPDATE products SET brand = 'Dollder' WHERE name = 'Ketorolac Trometamina 30 mg Dolak S.L Dollder x 4';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Surtidos';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Demi +1.5';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Protección Luz Azul +1.5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein About Time sabor a vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Confitura Sin Azucar Naturgourmet Sabor A Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Infusion Natural Limon/Malojillo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vancomicina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketoprofeno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Salbutamol 100 mcg Salbutral Cassara Aerosol Para Inhalación x 250 Dosis';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Protección Luz Azul +2.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aminoacidos BCAA + Glutamina Sascha Fitness Piña';
UPDATE products SET brand = 'Unknown' WHERE name = 'Spray Antibacterial Vult O Boticario';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sin Gluten Corn Rice Penne Sam Mills Classic';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Salbutamol 0,5% Medigen Oftalmi Solución Inhalatoria x 15 ml';
UPDATE products SET brand = 'Valmor' WHERE name = 'Sildenafil 50 mg Duroval Valmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dutasterida + Tamsulosina 0,5/0,4mg Tamsulon Duo';
UPDATE products SET brand = 'Pan' WHERE name = 'Miel De Abejas La Encantada Panalito Tripack';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply7 Chips de Garbanzos Sabor a Hummus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema De Avellanas Sin Gluten Chocotella';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multigen Sin Azucar Vainilla';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Gris +2,5';
UPDATE products SET brand = 'La Piel' WHERE name = 'Parches Protectores Para Callos La Piel 3Und';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Diclofenac Potásico 50 mg Medigen Oftalmi';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Diclofenac Potásico 50 mg Aflamax Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zentim';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sin Gluten Pasta Chickpea Penne';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola con Bayas y Yogurt Summer Berries Nature''s Path x 312 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gnocchi De Batata sin gluten La Molisana';
UPDATE products SET brand = 'Unknown' WHERE name = 'Salbutamol 100mcg 200 Dosis Suspensión en Areosol para Inhalar Medigen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Protosulfil 1%';
UPDATE products SET brand = 'Calox' WHERE name = 'Simeticona 125 mg Festasim Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetrón 8 mg Vonau Flash Biolab';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Sin Gluten Koala Crisp Nature''s Path x 325 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miovit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Beauty Sleep';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciproterona + Etinilestradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Tranexámico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levonorgestrel + Etinilestradiol Femexin 0,1mg/0,02mg  Elea';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mucomax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pregabalina 75 mg Pregalis CAI';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mucomax Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Triamcinolona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina 0,01 Crema 15 G';
UPDATE products SET brand = 'Klinos' WHERE name = 'Nitrofurazona 0,20g/100g Furfuril Klinos Pomada x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'LipaZil';
UPDATE products SET brand = 'Elmor' WHERE name = 'Lactobacillus Rhamnosus 250 mg Liolactil Elmor';
UPDATE products SET brand = 'Vargas' WHERE name = 'Lercanidipina 10 mg Dihidrolip Vargas';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Terbinafina 1% Perten Siegfried Solución Tópica x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina';
UPDATE products SET brand = 'Unknown' WHERE name = 'L Glutamina 60Capsulas Natural Premium';
UPDATE products SET brand = 'Leti' WHERE name = 'Lactobacillus P + Pediococcus A 150 mg Colozin LETI Pro biótico x 30 Cápsulas';
UPDATE products SET brand = 'Enterex' WHERE name = 'Suplemento alimenticio Enterex Fresa Polvo';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Latnoprost 0,005% Xenda Lansier Solucion Oftalmica Frasco x 3 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Sin Gluten Naturgourmet Sabor A Guayaba';
UPDATE products SET brand = 'Now' WHERE name = 'Proteina Whey Protein Now Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante Fructosa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Pediplus 400 G';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Redireaders Con Estuche +1.50';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Onco Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Enplus Con Fos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pregabalina 25 mg Pregalis CAI';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betagenta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina 1% Terbicrym Frasco x';