UPDATE products SET brand = 'Unknown' WHERE name = 'Carbocisteina';
UPDATE products SET brand = 'Intervit' WHERE name = 'Edulcorante Frutazucar Intervit';
UPDATE products SET brand = 'Leti' WHERE name = 'Omeprazol 20 mg Genven x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Giralmet 100.000UI';
UPDATE products SET brand = 'SNC Pharma' WHERE name = 'Nebivolol 5 mg Relnex SNC Pharma';
UPDATE products SET brand = 'Leti' WHERE name = 'Nifedipina 30 mg Tensomax L.P. Leti';
UPDATE products SET brand = 'GVR' WHERE name = 'Roskita Horneadas de Yuka con Oregano Representaciones GVR, C.A';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola Honey Almond Nature''s Path x 312 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barras Nature Valley Frutos Trail Mix x 35 gr';
UPDATE products SET brand = 'La Santé' WHERE name = 'Cetirizina 10 mg La Santé';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Minerales + Probióticos Complemento Alimenticio Probiotal 20 Billones CFU Naturlifes x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Calcio + Vitamina D3';
UPDATE products SET brand = 'Unknown' WHERE name = 'Centella Asiatica-Alcachofa-Jengibre Cellu Lose (Anticelulitico) 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Magnesio';
UPDATE products SET brand = 'Elmor' WHERE name = 'Oxolamina 1% Perebron Elmor Jarabe Adultos x';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Glutamina Evolution X 300 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Guata de Algodón Eurosoft 15 cm x 3 mt x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Triple + Serum Rejuvenating';
UPDATE products SET brand = 'Vivax' WHERE name = 'Piridoxina 300 mg Biprin Vivax';
UPDATE products SET brand = 'ASK' WHERE name = 'Soporte de rotula ASK proteccion completa';
UPDATE products SET brand = 'ASK' WHERE name = 'Soporte de rotula ASK talla unica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esporas de Bacillus Clausii 2000 UI Bioflora Medpharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esporas de Bacillus Claussi Pragermina ADN Medical 2 Billones/5ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esporas de Bacillus Clausii 4000 Ul Bioflora Max Medpharma';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Urolprot 50capsulas Naturlife''s';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colágeno 500 mg Natural Premium';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D3+K2 30capsulas Preventud Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio ImmunoVita Vitae';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glibenclamida + Metformina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno 60 Gomitas Mason Natural';
UPDATE products SET brand = 'Unknown' WHERE name = 'Termómetro Infrarojo Bing Zun';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Selenio 50 mcg Farmatodo Blíster x 30';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato De Magnesio 500 mg Falidu x 60 Gomitas Masticables';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmuneplus 30capsulas Preventud Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bencidamina + Cetilpiridino Isospray Plus Solución 0,15%-0,25%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina + Betametasona';
UPDATE products SET brand = 'Rowe' WHERE name = 'Lidocaína + Heparinoide 2% Bargonil Rowe Ungüento x 10 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomiitas Omega 3-6-9 1000 mg Falidu x 60 und';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Spaguetti Nnova Rice';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Magnesio 1400 mg Alfa Vitamins Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C 500 mg Cebión Sabor Tropical x 12';
UPDATE products SET brand = 'Laproff' WHERE name = 'Fluoxetina 20 mg Laproff Blíster x 10 Cápsulas';
UPDATE products SET brand = 'Biotech' WHERE name = 'Dipirona 500 mg Bral Biotech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vtiamina B1 Tiamina PL Solucion inyectable';
UPDATE products SET brand = 'Farma' WHERE name = 'Trimebutina Maleato 200 mg Colypan Laboratorios Farma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Colageno con Curcuma, Silicio y HA 330 gr Zafire Labs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Kx 3x3 x 2 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitaminico e Isotonico Metal Endurance x 1 Vial';
UPDATE products SET brand = 'Calox' WHERE name = 'Vitamina C Ácido Ascórbico 500 mg Cevax Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calostro 300 mg Sp Colostrum Proyecto Nueva Vida Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fibras de Glucomannan + Semilla de Plantago Ovata';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dexametasona';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Venosan 300 mg Arco Iris Frasco x 90 Cápsulas';
UPDATE products SET brand = 'Valmor' WHERE name = 'Sildenafil 100 mg Duroval Valmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorate de Sucralosa Endolce 50';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Nafazolina 0.012% Camolyn Plus Oftalmi Solución Oftálmica x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oxolamina';
UPDATE products SET brand = 'Farma' WHERE name = 'Ketorolaco Trometamina 20 mg Notolac Laboratorios Farma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Trimetoprim + Sulfametoxazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Candesartán + Hidroclorotiazida';
UPDATE products SET brand = 'Unknown' WHERE name = 'DistroEyes 60capsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Kinesiologica  1Rollo corrida 5m x 5cm Volk';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Ashwagandha 450 mg Herbaplant x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Pure Soy Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colágeno Hidrolizado 650 mg + Vitamina C Varitylabs By Falidu Frasco x 60 Gomitas';
UPDATE products SET brand = 'Europharm' WHERE name = 'Adhesivo Eurotrasp Eurofarm 5Cm X 5M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Agua Protect 20 Unidades';
UPDATE products SET brand = 'Farma' WHERE name = 'Tadalafilo 20 mg Fitex Laboratorios Farma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Plidan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion bactericida germicida GERDEX 240 ml';
UPDATE products SET brand = 'Procare' WHERE name = 'Aplicador Con Algodon Procare 100 Und';
UPDATE products SET brand = 'Calox' WHERE name = 'Levofloxacina 750 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Cafeína + Clorfeniramina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Multivitaminas Kids Falidu x 60 und';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Ovaxol 400 mg Naturlifes';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Esoflux Esomeprazol 40 mg Aless Pharmaceuticals Polvo Solucion Inyectable I.V. x 1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Liq Powerful Moka Doble Expresso';
UPDATE products SET brand = 'Val' WHERE name = 'Omega 3 Aceite de Pescado 1000 mg VAL Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Neoprene Sencilla Jogger talla unica';
UPDATE products SET brand = 'Biotech' WHERE name = 'Hidroclorotiazida 12.5mg Di - Eudrin Biotech';
UPDATE products SET brand = 'Unknown' WHERE name = 'HAR Adrenalina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite De Oliva Chacon Romero';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante organico de cristal de Agave Sugar Krush';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol Clorhidrato + Loratadina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitalmax';
UPDATE products SET brand = 'Leti' WHERE name = 'Budesonida 200mcg/dosis Pulmolet LETI Inhalador 200 Dosis x 10 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Linezolide 600 mg Prazolid ADN Medical';
UPDATE products SET brand = 'Vargas' WHERE name = 'Lercanidipina 20 mg Dihidrolip Vargas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Hideven Motas 50 Und';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Azul K6 Talla L';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Azul K6 Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Wampole Naranja Aceite de Hígado de Bacalao + Vitaminas del Complejo B Emulsión x 240 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitamínico Prenatal Con DHA x Puritan´s Pride x 60 Cápsulas Blandas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorate de Sucralosa Endolce 100';
UPDATE products SET brand = 'Now' WHERE name = 'Edulcorante Xilitol Now x 454 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol + Miconazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Allixon Emulsión Sabor Naranja x 240 Ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartán Medoxomil + Hidroclorotiazida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartán Potásico 50 mg DAC';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite De Pescado Omega 3';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dexopral 60 MG x 30';
UPDATE products SET brand = 'La Santé' WHERE name = 'Nifedipina 10 mg La Santé';
UPDATE products SET brand = 'Pan' WHERE name = 'Motidel Enzimatico 200/80mg Blister Pancreatina/Simeticona Fardel';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Naranja K6 Talla M';
UPDATE products SET brand = 'Dollder' WHERE name = 'Cinarizina 25 mg Cinaren Dollder';
UPDATE products SET brand = 'Behrens' WHERE name = 'Fosfato de Potasio Monobasico 1mEq /ml IVN 75 mg/3 ml Solución Ineyctable Behrens x 1';
UPDATE products SET brand = 'La Santé' WHERE name = 'Diclofenac Sódico 50 mg La Santé';
UPDATE products SET brand = 'SPL' WHERE name = 'Edulcorante Splenda X 50';
UPDATE products SET brand = 'Biotech' WHERE name = 'Cloruro de Cetilpiridinio + Clorhidrato de Benzidamina Isospray Biotech x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omega 3 Aceite de Chía Omechía FC Laboratorios x 30 Cápsulas Blandas';
UPDATE products SET brand = 'Now' WHERE name = 'Omega 3 Now 1000 Mg X 45 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel de abejas Ludy';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pelota de tenis Champions Ship Wilson 3 UND';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Caballero Metal +3.50';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina Glucofage XR';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chips con Proteina de Quinoa Natural Quinoa Club x 12 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Cacao y Miel Sin Gluten Noglut';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Pureza Aloevera 200 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche De Almendras Vilay';
UPDATE products SET brand = 'Behrens' WHERE name = 'Aceite de Linaza 1000 mg Flaxol Behrens Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche De Coco';
UPDATE products SET brand = 'Unknown' WHERE name = 'ALGODON ALVE 100 G';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina A + Vitamina D3 100u.i/100u.i 9-VIT Drovenplus 10 ml x 1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carboximetilcisteina';
UPDATE products SET brand = 'La Santé' WHERE name = 'Esomeprazol 40 mg Esoz Pharmetique Labs';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Fortsan 500 mg 90capsulas Arcoiris';
UPDATE products SET brand = 'Bayer' WHERE name = 'Berocca Plus Bayer Multivitamínico x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Ácido Ascórbico + Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Giniwa M 14capsulas Probióticos Para Embarazadas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina A + Vitamina E + Óxido de Zinc  Ademina Plus Etifar Tubo x 30 g Crema';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Picolinato de Cromo 200 mcg Pharmatech Frasco x 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina De Soya Sabor Vainilla Lifesystem Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Set De Raq-Pelota-Malla Jogger';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mancuerna 3 LB Live&Fit';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Ortesis Dynamics con aticulacion de disco corta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol 40 mg Dac 55';
UPDATE products SET brand = 'Unknown' WHERE name = 'Enalapril';
UPDATE products SET brand = 'La Santé' WHERE name = 'Trimebutina Maleato 300 mg Bumetin Retard Pharmetique Labs x 20';
UPDATE products SET brand = 'Unknown' WHERE name = 'Isoconazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tapones De Oidos Jogger 4Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Infusion Natural Flor De Jamaica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Comprilan BSN para compresion 10 cm x 5 m';
UPDATE products SET brand = 'K6' WHERE name = 'Mancuerna de Vinil K6 1 lb';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bandas de Yoga de Resistencia Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hand Grip - Empuñadura Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabergolina 0,5mg Caberguni Unipharma';
UPDATE products SET brand = 'Kimiceg' WHERE name = 'Sulfadiazina De Plata 1% Laboratorios Kimiceg Crema x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetrón 4 mg Vonau Flash Biolab';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Vitybell 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Ascórbico 100 mg/ml ADN Medical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levetiracetam 1000 mg Leratab CAI';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Kinesiologica Precortada Go Plus 5 Metros Color Azul';
UPDATE products SET brand = 'Unknown' WHERE name = 'Spraymedic Alcohol Antiseptico 70% Spray';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antifom';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Spaguetti Schar';
UPDATE products SET brand = 'Dollder' WHERE name = 'Diclofenac Dollder';
UPDATE products SET brand = 'La Santé' WHERE name = 'Diclofenac Potásico 50 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tinidazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol 15% + Miconazol 4% Miconax Crema Vaginal';
UPDATE products SET brand = 'Angelus' WHERE name = 'Dapagliflozina 10 mg Glinamed Angelus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sulfadiazina + Lidocaína Silverdin Plus 1%/5%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nafazolina 0,05% Fanasal Pediátrico Gotas x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'N-Acetilcisteína 200 mg Flemaxin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Ortoban 4X4 2Und';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Asiento portatil elevado para sanitario';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acua-e Agua Electrolizada Antiséptica Limpiadora Piel y Mucosas (Acido Hipocloroso) x 240 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hioscina + N - Butilbromuro Buscapina';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Cúrcuma 500 mg Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Para Dedo Talla XL';
UPDATE products SET brand = 'Farma' WHERE name = 'Macrocristales de Nitrofurantoina 50 mg Macrodantina Laboratorios Farma x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B Novhepar Jarabe 90 Ml';
UPDATE products SET brand = 'Valmor' WHERE name = 'Candesartan 32 mg Cander Valmor';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Antiseptico Farmatodo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carboximetilcisteína Gulaper Gotas Pediátricas';
UPDATE products SET brand = 'Jerico' WHERE name = 'Semillas De Castaño De India Variplant 45Capsulas Jerico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ripped Thermogenic Evolution X 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Merengada de Proteínas Mi Ultima Dieta Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche de Almendras con Cacao en Polvo Achocolatada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply7 Chips de Quinoa Sabor a Salsa BBQ';
UPDATE products SET brand = 'Going' WHERE name = 'Proteina Sabor Vainilla Going x 30 gr';
UPDATE products SET brand = 'Dixson' WHERE name = 'MAT D/YOGA DIXSON AZUL 3MM';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hand Grips Manija Esponjada Jogger';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para Mareo - Náuseas - Vómito Medipatch';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Calcio + Vitamina D3 + Hierro + Ácido Fólico Calcifor Prenatal Pharmatech Frasco x 30';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Alcohol Absoluto x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Universal Forma Elastica Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mix Antioxidant Snak Club x 156 gr';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Elevador Sanitario Con Seguro y Reposabrazos Dovant x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mi Última Dieta Merengada de Proteínas Sabor Vainilla';
UPDATE products SET brand = 'Ana Maria Lajusticia' WHERE name = 'Triptofano + Gaba + Pasiflora + Magnesio Ana Maria Lajusticia x 60';
UPDATE products SET brand = 'Procare' WHERE name = 'Compresa Laparatomia Procare 18x18 45 x 45 cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Steritex Hidrofilo 50 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Hideven Motas 100 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Topica Iodada Xiodine 120 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorfeniramina + Dextrometorfano';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitaminas + Minerales + Ácido Fólico Multivinol Prenatal Arnet Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ortoban Yeso 3" X 3YDS  1Rollo 7.5 cm x 2,7 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina A VItahelp 5000 UI/IU x120';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Merthiolate Incoloro';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Muxer 500 mg Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Para Muslo Sz 5 T/L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio y Vitamina B6 Mag Vital x20 Marnys';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Sin Gluten Amazon Flakes Nature''s Path x 325 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esparadrapo Quirurgico Pharmamed 1,25x4,55 1 Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zinc';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Negro +3.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Procaps' WHERE name = 'Vitaminas Y Minerales Embarazo Gestavit DHA Procaps';
UPDATE products SET brand = 'Unknown' WHERE name = 'Luz Trasera Ciclismo 1230';
UPDATE products SET brand = 'Unknown' WHERE name = 'Maca';
UPDATE products SET brand = 'Unknown' WHERE name = 'Xytrex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Giniwa M Probióticos Para Embarazadas x 14 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica 6Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno Anapir';
UPDATE products SET brand = 'Calox' WHERE name = 'Alimento En Polvo Vitaminas + Minerales Prokids Calox';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Pasta Anellini Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Graviola 60Capsulas Natural Premium';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cirnaprem 60capsulas Natural Premium';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminas Para Mujeres Ziel Pharma Frasco x 50 Gomitas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kit De Bioseguridad';
UPDATE products SET brand = 'Ronava' WHERE name = 'Ronavit Complejo B 2 ml Solución Inyectable I.M. Ronava x 3';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Meloxicam 15 mg Solican FC Pharma';
UPDATE products SET brand = 'Tiares' WHERE name = 'Glicerina 0,86 g Glicerin Baby Tiares';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colágeno Hidrolizado Sin Sabor Sascha Fitness x 416.5 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitoneon 5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Tela Impermeable 5cmx4,5m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Carboprotein Modulo Calor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vinagre De Manzana';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gorro de Natación de Silicon Colores Surtidos TYR';
UPDATE products SET brand = 'Leti' WHERE name = 'Complejo B Neuromix Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Elastica Kx Ventilada Soporte De Pulgar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Regeneradora Sabor Vainilla Ziel Pharma Frasco x 50 Gomitas';
UPDATE products SET brand = 'K6' WHERE name = 'Mancuerna 9LB de Vinil K6';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina Prenatal Puritan´s Pride x 100 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te Nature Verde Libre de Azucar 1.2litros';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aminoacidos BCAA + Glutamina Sascha Fitness Patilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Leukoplast Elastica Mixta 20 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Leukoplast Estandar Color Piel 19 X 72 Mm';
UPDATE products SET brand = 'Calox' WHERE name = 'Pancreatina Festal Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zinc + Cloruro Cúprico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cocoloco Yogranola';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hialuronato De Sodio 0,4% Toptear Poen Lagrimas Artificiales x 10 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Simeticona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Trisilicato de Magnesio + Óxido de Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cebión Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B Inyectable 2 ml Vitoneon Cooper';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Siegfried Acibath-S Dermolimpiador Jabon Liquido';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Antidiarreico Medipatch 6 Und';
UPDATE products SET brand = 'Ronava' WHERE name = 'Ronavit Complejo Vitamina B Ronava Estuche';
UPDATE products SET brand = 'Unknown' WHERE name = 'Banda De Resistencia L3';
UPDATE products SET brand = 'Unknown' WHERE name = 'Banda De Resistencia L1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Correa Ajustable Kx Para Rotula';
UPDATE products SET brand = 'Unknown' WHERE name = 'OlioVita Protect Solar Oral 15 Cápsulas. Comlemento Alimenticio  Vitae';
UPDATE products SET brand = 'Ebben' WHERE name = 'Venda Elastica 20Cm Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Curativo Cutimed';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Body-Hair-Skin-Nails 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Leukopor Blanco 5cm/9 X 2m';
UPDATE products SET brand = 'K6' WHERE name = 'Base para Flexiones K6';
UPDATE products SET brand = 'Farmatodo' WHERE name = '!!Vitamina Farmatodo 30tabletas Complejo B';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina 500 mg Naturistik Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lecitina De Soya Lecithin';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Bitex 30tabletas Complejo B Naturlifes';
UPDATE products SET brand = 'Unknown' WHERE name = 'Anamu';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pluriamin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bandas de resistencia elasticas microgym KX';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Para niños 100 Gomitas Mason Natural';
UPDATE products SET brand = 'Now' WHERE name = 'Edulcorante Fructosa Now';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante Hermesetas Gold 100tabletas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína Horchata Vainilla Sascha Fitness';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venditas Adhesivas Resistentes al Agua Cure Aid 20 Unidades';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Baston Dynamics 4 Ptos Base Pqna S1 Cromo';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Negra K6 Talla S';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Azul K6 Talla XL';
UPDATE products SET brand = 'La Santé' WHERE name = 'Amlodipino 5 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clortalidona 12,5mg MT';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hantacid Susp Oral  x 20';
UPDATE products SET brand = 'Farma' WHERE name = 'Acetaminofén + Cafeína + Clorfeniramina Teragrip Forte Farma x 10';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Venacare 460 mg Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Now' WHERE name = 'L-Arginina Now 500 Mg 100 Cápsulas';
UPDATE products SET brand = 'Klinos' WHERE name = 'Vitamina B12 250 mcg Klinos';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Citrato de Calcio+Vitamina D 100Tabletas Pharmatech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C + Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida en polvo Frutilike Durazno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jabón Liquido Isogel Bactericida';
UPDATE products SET brand = 'Farma' WHERE name = 'Betadine Iodopovidona Laboratorios Farma Solución x 120 ml';
UPDATE products SET brand = 'Polinac' WHERE name = 'Centella Asiática 1% Madecassol Polinac Ungüento x 10 gr';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Transpore 3M 3" X10 Yd';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cuerda De Saltar Con Contador Jogger';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gypsona Venda De Yeso 4" X 3 Ydas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Tiocolchicosido';
UPDATE products SET brand = 'Unknown' WHERE name = 'Protector De Plastico Para Dedos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina 1% Terbicrym Avpharma Crema x 20 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Immune Support 7 en 1 Preventud Plus x 60 Cápsulas';
UPDATE products SET brand = 'Calox' WHERE name = 'Carvedilol 12,5 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mentol Davis Eucalipto Tarro';
UPDATE products SET brand = 'Pediasure' WHERE name = 'Pediasure Vainilla';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Biotina 10000 mgc Biotin Complex Naturlife''s Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Magnesio';
UPDATE products SET brand = 'La Santé' WHERE name = 'Gentamicina 0,1% La Santé Crema x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pregabalina 75 mg Neurixa';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Omeprazol 40 mg Omeflux Aless Pharmaceuticals Solución Inyectable';
UPDATE products SET brand = 'Calox' WHERE name = 'Omeprazol 20 mg Calox';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Olopatadina 0,1% Opat Oftalmi Solución Oftálmica x 5 ml';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Dequalinio + Lidocaína 0,25mg/5mg Benzodiazol Limón Miel Siegfried';
UPDATE products SET brand = 'Unknown' WHERE name = 'ADHESIVO GIDAGUS BLANCO 2.25 X 5';
UPDATE products SET brand = 'SNC Pharma' WHERE name = 'Quetiapina 100 mg Letalop SNC Pharma';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Eurofix 10cm x 2m Eurociencia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera De Neopreno Jogger Adulto Unidad';
UPDATE products SET brand = 'Genfar' WHERE name = 'Betametasona 0,05% Genfar Crema x 40 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clobetasol Propionato 0.05% Crema Clobe-1 Farmagenik x 30 gr';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina 25Mcg 10Tabletas Remeny';
UPDATE products SET brand = 'SPL' WHERE name = 'Splash Antibacterial Isogel';
UPDATE products SET brand = 'Leti' WHERE name = 'Extracto de Corteza de Pino Marino Francés 50 mg Bioletisan Forte Antioxidante x 20 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acido Absorbico Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio + Vitamina D3';
UPDATE products SET brand = 'Unknown' WHERE name = 'IntestVita  Kids15';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Melatonina 3 mg Arco Iris Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D3 1000 UI Farma D';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Keratium 60';
UPDATE products SET brand = 'Leti' WHERE name = 'Letisan 100Mmg/ml 90 ml solución oral Acido Ascorbico Vit C Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bola De Masaje Frio/Calor Kt Tape';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento Alimenticio Enterex Total RPB Vainilla Botella x 237 ml';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Micofenolato de Mofetilo 500 mg Micoflavin Iclos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitadyn C';
UPDATE products SET brand = 'Remeny' WHERE name = 'Ibandrónico Sódico 150 mg Remeny';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Vitamina C 500 mg Vitadyn C Oftalmi x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C+Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tapones de Oidos Silicona Protechs Seal-Rite x 3 Pares';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Transparente Microperforado Zuviss 2,5cm x 9,10m x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Desinfectante Santex Anti-Ácaros Kao x 450 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Kids Para Niños Briutcare x 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Manga de Compresión Fría KT Tape Talla L/Xl';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Durapore 3M 2" X10Yd';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Steripharma Ext/Clinica 1 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Steripharma Clinica 1 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lagrimas Artificiales Lacridos 0,1%';
UPDATE products SET brand = 'Meyer' WHERE name = 'Furosemida 20 mg Daliol Meyer';
UPDATE products SET brand = 'Unknown' WHERE name = 'Flemibar';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Castaño De Indias Arcoiris Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Ronava' WHERE name = 'Polietilenglicol 3350 Milax 360 Ronava Polvo Solución Oral x 360 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Kx De Neopreno Ajustable Talla G';
UPDATE products SET brand = 'Ensure' WHERE name = 'Ensure Advance Vainilla';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Chanca Piedra 400 mg Herbaplant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Masticables con Colageno y Vitamina C 650 mg Falidu';
UPDATE products SET brand = 'Unknown' WHERE name = 'Melatonina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Vitamina Ultra Vit Women Farmatodo';
UPDATE products SET brand = 'ASK' WHERE name = 'Codera ASK talla L/XL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina K 100mcg 100tabletas Mason Natural';
UPDATE products SET brand = 'Ebben' WHERE name = 'Gasa Economic 1,2Cm 2Pliegos Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pentamag';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Para Dedo Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Merey Tostado con Miel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mix Sweet and Salty Snak Club x 156 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Alimenticio NutraDose 30ampollas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mani Acaramelado Snak Club x 213 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Saw Palmetto Urolprot Advanced 400 mg x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media Pie Sensible Diabetico Hilado Cobre XL Negro Medi Varic';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Vitamina E 400 IU  Natural Systems Frasco x 60 Cápsulas Blandas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina 500 mg DAC x 10 Cápsulas';
UPDATE products SET brand = 'Calox' WHERE name = 'Atorvastatina 20 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ultra Zinc con Calcio';
UPDATE products SET brand = 'Behrens' WHERE name = 'Solución Electrolítica 45 meq Behrens Rehidrosol Uva x 600 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Escitalopram 10 mg Cleo';
UPDATE products SET brand = 'Farma' WHERE name = 'Empaglifozina 10 mg Actumir Laboratorios Farma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cobamamida 1 mg Cooper Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Terapeutica';
UPDATE products SET brand = 'Unknown' WHERE name = 'NAD + NMN + Resveratrol + Astaxantina DistroNAD 400 mg Distrilab x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina 1% Losil - C Alpharma Crema Tubo x 20 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dexametasona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Combo De Buceo Infantil';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico My Carb Blocker 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D3 5.000 UI + K 50 mcg Preventud Plus Frasco x 60 Cápsulas';
UPDATE products SET brand = 'ASK' WHERE name = 'Cinturon Deportivo Ask';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Negro de Pasta Gruesa +3.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Yoga Mat x 0.4 cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chips Arepa Sabor Original Kseritas 100 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema Corporal Antifricción Deportiva free Life Style';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Hombro Derecho Kx';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla de Baño Dovant x 1 und';
UPDATE products SET brand = 'Farma' WHERE name = 'Vitamina D3 5000UI Laboratorios Farma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina Clorace Jarabe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Jabonosa Iodada Xiodine 120 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media Pie Sensible Diabetico Hilado Cobre M Negro Medi Varic';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oxolamina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media Pie Sensible Diabetico Hilado Cobre M Blanco Medi Varic';
UPDATE products SET brand = 'ASK' WHERE name = 'Pesa Rusa 6Kg Ask';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio OlioVita Vitae';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico My Cellulost Centella Asiatica 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel antibacterial Pureza Teens Tutti Frutti 80 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'L-Carnitina 500 mg Vitamina Farmatodo Frasco x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno 100 mg Bioquimica Suspensión Oral Pediátrica x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Men Xtra Performance 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico Immunity Power Limon';
UPDATE products SET brand = 'La Santé' WHERE name = 'Enalapril 20 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Escitalopram 5 mg Cleo';
UPDATE products SET brand = 'La Santé' WHERE name = 'Atorvastatina 20 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antiacido Aplacal Banana';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketoprofeno 100 mg IV Zaki';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carbocisteína Sin Azúcar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel De Abejas La Encantada Colmenita';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico Slim Down 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gotas Lubricantes para';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cuerda De Saltar De Cuero Jogger';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel antibacterial Pureza Teens Mandari 80 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Nifedipina 30 mg Tensomax L.P Leti x 30 Cápsulas Liberación Prolongada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D 1000 UI DarliDe Fc Laboratorios';
UPDATE products SET brand = 'Unknown' WHERE name = 'Spraymedic Alcohol Antiseptico Spray 100Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Saludable Sin gluten Papas El Valle sabor Chorizo y Huevo Frito';
UPDATE products SET brand = 'Calox' WHERE name = 'Captopril 25 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmukids Sabor Naranja Vitamina C y Zinc Bionutrec';
UPDATE products SET brand = 'Unknown' WHERE name = 'GluActive Ig 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Briutcare De Plástico Transparente';
UPDATE products SET brand = 'Unknown' WHERE name = 'Selenium 200Mcg 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Extracto de Menta + Jengibre + Fibra de Goma de Acacia Optimizador de Colon 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C-Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico My Detox 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Mixtas Briutcare x 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'ADHESIVO GIDAGUS PIEL 5 X 5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collarin Cervical Dynamics talla XXL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carboximetilcisteina Ditosxil';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartan + Hidroclorotiazida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Kx Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Toallas Sanitizantes alcoholadas al 70% 30 Unidades Mor Medics';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico Appetite Support 30capsulas YYC';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Papel Blanco Bruitcare 2,4Cm X 4,57M 1Unidad';
UPDATE products SET brand = 'Calox' WHERE name = 'Loratadina 10 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Budesonida';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Calox' WHERE name = 'Diosmina 600 mg Calox';
UPDATE products SET brand = 'Valmor' WHERE name = 'Pregabalina 150 mg Prelival Valmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metilprenisolona 500 mg Protech Telelinks Solución Inyectable';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sitagliptina + Metformina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aciclovir 400 mg Distrilab x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bisoprolol + Hidroclorotiazida';
UPDATE products SET brand = 'Leti' WHERE name = 'Olmesartan Medoximil 20 mg Olmecar Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Antiséptica Dioxogen Med Hipoalergénica x 460 ml';
UPDATE products SET brand = 'K6' WHERE name = 'Set De Bandas De Resistencia K6';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gorro De Natacion Jogger';
UPDATE products SET brand = 'ASK' WHERE name = 'Ask Rueda De Abdominales';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Canelones Nnova Rice';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina + Glibenclamida Diaformina Plus';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Alve Mota';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Deportiva Elastica Colores Surtidos';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Abana Himalaya 50Tabletas Natural L';
UPDATE products SET brand = 'K6' WHERE name = 'Liga de Resistencia K6 4.5 Kg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zarzaparrilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Singrass Adelgazante 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cloruro de Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Rarivit Gotas Sabor Tutti Frutti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Damel Sin Azucar Melocoton, Fresa y Naranja';
UPDATE products SET brand = 'K6' WHERE name = 'Codera K6 Nivel 2 Talla S/M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Simeticona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carbonato de Litio 300 mg Nio Pharmaceutical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Provim vit y minerales';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla cuadraplejico tipo camilla';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Complemento Alimenticio Flexvit Farmatodo Frasco x 30 Cápsulas';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Negra K6 Talla XL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garcinia Cambogia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Donepezilo 5 mg MT Global Care';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorferinamina';
UPDATE products SET brand = 'Unknown' WHERE name = 'ALGODON AMY MOTAS 100UND';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente de Lectura Optiko Gris +2';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein Active + Best Age Sanavita';
UPDATE products SET brand = 'Calox' WHERE name = 'Vitafer-L Oral Duo x 500 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';