UPDATE products SET brand = 'Ursocol' WHERE name = 'Ácido Ursodesoxicólico 300 mg Ursocol Laboratorios Zuzu x 10';
UPDATE products SET brand = 'Calox' WHERE name = 'Vitafer-L Solucion Oral';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 1% Imazol Siegfried Crema Tópica x 20 gr';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Tiares' WHERE name = 'Desogestrel 0,075 mg Celestrel Tiares';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Acetaminofen + Clorfeniramina + Cafeína Angrip Día 8';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venpielgel Skinreg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Mandarina 500 mg + Zinc Combo 3x2';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Colageno + Vit C 60capsulas Natural Systems';
UPDATE products SET brand = 'Pan' WHERE name = 'Chía Pantera';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina Dayflu Noche';
UPDATE products SET brand = 'La Santé' WHERE name = 'Cetilpiridinio + Bencidamina Solunovar Compuesto 0,25mg/0,15mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema de Cacao y';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite Ozonizado Tópico Vitaozono x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Calcium 600 + D3 100';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Furosemida';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Champú Piritionato de zinc Frasco x 120 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Omeprazol 20 mg Genven';
UPDATE products SET brand = 'Leti' WHERE name = 'Olmesartán Medoxomil 20 mg Genven';
UPDATE products SET brand = 'Behrens' WHERE name = 'Solución Cloruro De Sodio al 0,9% Flexi-Behr Behrens Frasco x 500 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Losartán Potásico 50 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Tramadol';
UPDATE products SET brand = 'Novartis' WHERE name = 'Valsartan Novartis';
UPDATE products SET brand = 'La Santé' WHERE name = 'Dequalinio + Lidocaina Benzodiazol Limon 0,25/5Mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hierro';
UPDATE products SET brand = 'FAHD' WHERE name = 'Amoxicilina 500 mg FAHD Blíster x 10 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Kinesiologica Go Plus 1 Metro Color Azul';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amitriptilina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply7 Chips de Lentejas con Sal Marina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Manga de Compresion Fria KT Tape Talla S/M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Kx Talla L';
UPDATE products SET brand = 'Jerico' WHERE name = 'Castaño De Indias + Caléndula + Centella Asiática Venasplant Jerico x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dextrometorfano Tilodrin';
UPDATE products SET brand = 'Leti' WHERE name = 'Olmesartan Medoxomil 40 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amlodipina';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sodica 50mcg Eutirox Merck';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hierro + Ácido Fólico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hioscina + Ibuprofeno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnevit';
UPDATE products SET brand = 'Dixson' WHERE name = 'Mancuernas Dixson 1kg 2 Und';
UPDATE products SET brand = 'Enterex' WHERE name = 'Suplemento alimenticio Enterex Vainilla Polvo';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Ácido Fólico 5 mg Plusandex x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alimento Proteina Nutricap Keratine 1 Mes';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Diosmina 600 mg Bresis Megalabs';
UPDATE products SET brand = 'Valmor' WHERE name = 'Rivaroxabán 15 mg Rivaprof Valmor';
UPDATE products SET brand = 'Calox' WHERE name = 'Amlodipina 10 mg Calox';
UPDATE products SET brand = 'Leti' WHERE name = 'Atorvastatina 20 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciprofloxacina';
UPDATE products SET brand = 'La Santé' WHERE name = 'Clopidogrel 75 mg La Santé';
UPDATE products SET brand = 'Leti' WHERE name = 'Ácido Fólico 10 mg Genven x 30';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Magnesio 4x Magnevit Advanced 500 mg Naturlife´s Frasco x 50';
UPDATE products SET brand = 'Leti' WHERE name = 'Valsartán 80 mg Genven';
UPDATE products SET brand = 'Leti' WHERE name = 'Azitromicina 500 mg Genven';
UPDATE products SET brand = 'Rowe' WHERE name = 'Losartan Potásico 50 mg Nefrotal Rowe';
UPDATE products SET brand = 'Ronava' WHERE name = 'Hierro + Ácido Fólico + Fumarato Ferroso + Vitamina B12 Folifer B-12 Ronava x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glucosamine + Chondroitin + Acido Hialurionico + Colageno + Msm';
UPDATE products SET brand = 'Leti' WHERE name = 'Candesartán 8 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Pescado 1000 mg Omega 3 Preventud Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketorolaco Trometamina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carbonato de Calcio Antiacido Acifar x60';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Corentel';
UPDATE products SET brand = 'Spervend' WHERE name = 'Venda Elastica Spervend 15 Cm';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'K6' WHERE name = 'Cuerda para Saltar K6 Apolo II';
UPDATE products SET brand = 'Behrens' WHERE name = 'Solución Electrolítica 60meq/l Behrens Rehidrosol Zinc Manzana x 600 ml';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Muletas Ajustables Estándar Talla L Next Step';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhidrato De Bromexina';
UPDATE products SET brand = 'Pharmacorp' WHERE name = 'Suplemento Femi-Balance Menopausia Pharmacorp Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Leti' WHERE name = 'Loratadina 10 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Oro Sin Gluten Macarroni';
UPDATE products SET brand = 'Jerico' WHERE name = 'Saw Palmetto + Vtamina E + Óxido De Zinc + Levadura De Selenio Prostalife Jerico x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oxolamina Gencer Jarabe Pediátrico 120 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Going' WHERE name = 'Gel Energético Going Guayaba x 33 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'CoQ10 Coenzima';
UPDATE products SET brand = 'Unknown' WHERE name = 'Centella Asiática 300 mg Natural Premium Frasco x 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B B1+B6+B12 con Lidocaina Solucion Inyectable I.M. 3';
UPDATE products SET brand = 'Vargas' WHERE name = 'Bisoprolol 5 mg Biprolil Vargas';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Hipromelosa Lagricof 0,3% Cofasa Frasco x 15 ml Solución Oftálmica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alimento en Polvo Vitaminas/Minerales Mi-vit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clonidina Naclodin 0,150 Mg X 20';
UPDATE products SET brand = 'CureBand' WHERE name = 'Curas Premium CureBand';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhidrato de Oximetazolina 0,05% Almorca Frasco x';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Secnidazol';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartan + Hidroclorotiazida Gencer 160/12,5 Mg X 14';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cloruro de Sodio Nafavine Solucion Nasal Pediatrica 6.5mg/ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Losartán Potásico 100 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Corbis Bisoprolol';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Imazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nifedipina LP';
UPDATE products SET brand = 'Genia Care' WHERE name = 'Fluticasona 50 mcg Flixocare Suspensión Para Inhalación Nasal Genia Care x 120 Dosis';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curapor Transparente Aposito Quirurgico 10x15Compresa 5x11cm Und';
UPDATE products SET brand = 'Leti' WHERE name = 'Alivet Forte';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Imazol Dual 1 Capsula Blanda Vaginal';
UPDATE products SET brand = 'Leti' WHERE name = 'Bisoprolol 2.5mg 20comprimidos Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Montelukast';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Imazol';
UPDATE products SET brand = 'Angelus' WHERE name = 'Glimepirida 2 mg Angelus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miovit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oxolamina';
UPDATE products SET brand = 'La Santé' WHERE name = 'Aciclovir 5% Aclovirax Pharmetique Labs Crema x 20 gr';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Acetaminofen+Clorfeniramina Noxpirin';
UPDATE products SET brand = 'La Santé' WHERE name = 'Flunarizina 10 mg Fludil Pharmetique Labs';
UPDATE products SET brand = 'La Santé' WHERE name = 'Glimepiride 2 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Kx Neopreno Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Febrip';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bencidamina + Cetilpiridino Bucoxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levadura De Cerveza';
UPDATE products SET brand = 'Unknown' WHERE name = 'Protector Bucal Externo Talla U x1 Unidad Pura+';
UPDATE products SET brand = 'Leti' WHERE name = 'Metformina 500 mg Genven';
UPDATE products SET brand = 'Leti' WHERE name = 'Amlodipina 5 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curapor Aposito Quirurgico 10x15compresa 5x11cm Unidad';
UPDATE products SET brand = 'Tiares' WHERE name = 'Ciproterona + Etinilestradiol 35mcg/2mg Dani Tiares';
UPDATE products SET brand = 'Farma' WHERE name = 'Ácido Ibandrónico 150 mg Bonames Laboratorios Farma x 1 Tableta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clopidogrel';
UPDATE products SET brand = 'Calox' WHERE name = 'Azitromicina 500 mg Calox';
UPDATE products SET brand = 'Behrens' WHERE name = 'Carvedilol 6.25 mg Carvedil Behrens';
UPDATE products SET brand = 'Unknown' WHERE name = 'Espironolactona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levonorgestrel + Etinilestradiol 0.15 mg 0.03 mg Overol';
UPDATE products SET brand = 'Unknown' WHERE name = 'D-Glucosamina + Colágeno + Ácido Hialurónico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Budesonida Budecort';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiocolchicosido 4 mg Dac55';
UPDATE products SET brand = 'Dixson' WHERE name = 'Pesas Tobilleras Dixson 1,5 Kg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Risperidona';
UPDATE products SET brand = 'Colmed' WHERE name = 'Esomeprazol Colmed';
UPDATE products SET brand = 'Quim-Far' WHERE name = 'Amoxicilina 500 mg Quim-far';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antiacido';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Fugolin';
UPDATE products SET brand = 'Calox' WHERE name = 'Ciprofloxacina 500 mg Calox';
UPDATE products SET brand = 'Barilla' WHERE name = 'Pasta Barilla Penne R.Gluten Free';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Forma elastica Universal Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Kinesiologica Go Plus 5 Metros Color Negro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cefadroxilo 500 mg DAC';
UPDATE products SET brand = 'Leti' WHERE name = 'Hidroclorotiazida 12,5 mg Genven';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno 600 mg Brugesic';
UPDATE products SET brand = 'Leti' WHERE name = 'Carvedilol 12,5 mg Genven x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Propinox + Lisina';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Montelukast 10 mg Airon Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartán Potasico + Hidroclorotiazida';
UPDATE products SET brand = 'La Santé' WHERE name = 'Desloratadina + Montelukast 2,5mg/5mg Desler M Pharmetique Labs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azitromicina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfato Sódico Dibásico + Fosfato Sódico Monobásico Fosfolit';
UPDATE products SET brand = 'La Santé' WHERE name = 'Ambroxol + Loratadina 30-5mg/5ml Broxol Alerg Pharmetique Labs Jarabe x 100 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Tiocolchicósido';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartan+Hidroclorotiazida';
UPDATE products SET brand = 'La Santé' WHERE name = 'Talysto Tadalafilo 5 mg Pharmetique Labs x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Herba Kids Jarabe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levofloxacina Levo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betahistina';
UPDATE products SET brand = 'Leti' WHERE name = 'Glimepirida 4 mg Genven';
UPDATE products SET brand = 'Leti' WHERE name = 'Ketoprofeno 100 mg Genven';
UPDATE products SET brand = 'Rowe' WHERE name = 'Nefrotal';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Azul K6 Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amlodipina';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Spirulina 500 mg Arco Iris Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Riñonera para Correr Live&Fit';
UPDATE products SET brand = 'JHC' WHERE name = 'Omeprazol 40 mg JHC Solución Inyectable';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Valmor' WHERE name = 'Rivaroxabán 10 mg Rivaprof Valmor';
UPDATE products SET brand = 'Elmor' WHERE name = 'Alantoina + Decualino 0,5%/0,4% Alantamida Siegfried Pomada x 20 gr';
UPDATE products SET brand = 'Ensure' WHERE name = 'Suplemento Alimenticio Ensure Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esoz Hp Esomeprazol + Amoxicilina + Claritromicina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glucosamina + Colágeno + Ácido Hialurónico + Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Birgit Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina 500 mg Biumak Pharmaceuticals';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina 5 mg Deslorat Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina B12 + Vitamina B6 + Lidocaína';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'GreenPharma' WHERE name = 'Clonidina 0,150 mg Niclodi GreenPharma';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Bisoprolol 1,25 mg Corentel Megalabs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tadalafilo';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Diclofenac Potásico 50 mg Dolcan Megalabs';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Naranja K6 Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dutasteride 0,5 mg Dutapros Zoriak';
UPDATE products SET brand = 'FAHD' WHERE name = 'Penicilina G Benzatinica 2.400.000 UI FAHD Polvo Para Suspensión Inyectable x 1 Vial I.M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Leukopor Blanco 5cm X 5m';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Azul K6 Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'ADHESIVO GIDAGUS PIEL 2.25 X5';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carvedilol Carvedil 25 mg 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azitromicina';
UPDATE products SET brand = 'Leti' WHERE name = 'Esomeprazol 40 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Avitil Gel';
UPDATE products SET brand = 'Calox' WHERE name = 'Pancreatina Festal Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Salicílico + Ácido Benzoico Niosilin Medivigor Ungüento x';
UPDATE products SET brand = 'Rowe' WHERE name = 'Losartan Potasico + Hidroclorotiazida Nefrotal H 100/12,5Mg X 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amikacina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Inmunix-T4 30';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fajitas de Yuca 12und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cefixima 400 mg  DAC55';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico DAC';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Mitar Mometasona 50 mcg Siegfried Solución Inhalación Nasal x 120 Dosis';
UPDATE products SET brand = 'Unknown' WHERE name = 'Andantol Jalea Crema x 20 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel para Tansmisión de Ultrasonido Acuagel Tarro x 1l';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartán 80 mg GDC';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Zabila 430 mg Arcoiris Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Naturlife' WHERE name = 'tribulus terrestris 60capsulas naturlife''s';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Integral Penne Rigate La Molisana';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida Greenstar Leche de Avena 1Lt';
UPDATE products SET brand = 'Vick' WHERE name = 'Alcanfor + Mentol + Eucalipto Vick Vaporub Ungüento Lata x 12 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Penicilina Benzatínica 1.200.000 UI Genérico';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Olmesartán Medoxomilo 20 mg Eukene Megalabs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Milax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glibenclamida 5 mg Laboratorios Buka';
UPDATE products SET brand = 'La Santé' WHERE name = 'Esomeprazol 20 mg Esoz Pharmetique Labs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B Vial';
UPDATE products SET brand = 'Bayer' WHERE name = 'Drospirenona + Etinilestradiol 3 mg/20 mcg Yaz Bayer';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Acido Clavulanico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidroclorotiazida Di-Eudrin 12.5Mg 24';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno Ibuvin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rosuvastatina Rosutan';
UPDATE products SET brand = 'Unknown' WHERE name = '!!Suplemento alimenticio Glutapak R';
UPDATE products SET brand = 'CureBand' WHERE name = 'Esparadrapo Tela CureBand 5cmX4,50m';
UPDATE products SET brand = 'Vargas' WHERE name = 'Fumarato De Bisoprolol 2,5 mg Biprolil Vargas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nasamist';
UPDATE products SET brand = 'Ebben' WHERE name = 'Venda Economic 15Cm Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Impermeable Blanco 1,2cmx4,5cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gentamicina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Tiocolchicosido';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Fluticasona Propionato 50 mcg Flinas Oftalmi Suspensión Nasal x 140 Dosis';
UPDATE products SET brand = 'La Santé' WHERE name = 'Talysto Tadalafilo 20 mg Pharmetique Labs x 1 Tableta Masticable';
UPDATE products SET brand = 'Valmor' WHERE name = 'Candesartán 8 mg Cander Valmor';
UPDATE products SET brand = 'Valmor' WHERE name = 'Candesartán 16 mg Cander Valmor x 30';
UPDATE products SET brand = 'Rowe' WHERE name = 'Losartan Potasico Nefrotal H 100/25Mg X 30';
UPDATE products SET brand = 'La Santé' WHERE name = 'Atenolol 100 mg La Santé';
UPDATE products SET brand = 'Huazhong' WHERE name = 'Levonorgestrel 0,75mg Huazhong Pharmaceutical';
UPDATE products SET brand = 'Remeny' WHERE name = 'Aciclovir 5% Remeny Crema x';
UPDATE products SET brand = 'Leti' WHERE name = 'Atorvastatina 40 mg Genven';
UPDATE products SET brand = 'Now' WHERE name = 'Probiótico-10 25 Billones Now Frasco x 50 Cápsulas';
UPDATE products SET brand = 'Ana Maria Lajusticia' WHERE name = 'Magnesio Total 5 Ana María Lajusticia Frasco x 100';
UPDATE products SET brand = 'Calox' WHERE name = 'Candesartán 8 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mometasona 0,1% Dermacortine Medihealth Emulsión Tópica x 60 ml';
UPDATE products SET brand = 'Laproff' WHERE name = 'Naproxeno 250 mg Laproff Blíster x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartán Medoximil + Hidroclorotiazida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno Ibutan 100 Mg/5 Ml Suspensión X';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol + Nistatina + Lidocaina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gentamicina';
UPDATE products SET brand = 'Neopharma' WHERE name = 'Methoget Metotrexato 2,5 mg Neopharma x 30';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Angrip Forte Día Acetaminofén + Clorfeniramina + Cafeína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pastillero Okoi Semanal';
UPDATE products SET brand = 'La Santé' WHERE name = 'Betahistina 16 mg La Santé';
UPDATE products SET brand = 'La Santé' WHERE name = 'Bencidamina + Cetilpiridino Bucoxol Gar Sabor Frutos Rojos  La SantéSolución Tópica x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Leukoplast Elastica Redondas 2.2 Cm';
UPDATE products SET brand = 'Leti' WHERE name = 'Meloxicam 15 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Mezcla De Mani, Maiz, Almendra Y Arandanos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acido Ascorbico Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina';
UPDATE products SET brand = 'SPL' WHERE name = 'Edulcorante Stevia Splenda';
UPDATE products SET brand = 'Blue Medical' WHERE name = 'BICALUTAMIDA BLU';
UPDATE products SET brand = 'Biotech' WHERE name = 'Lactbet 3.000U 10capsulas Lactasa Biotech';
UPDATE products SET brand = 'Polinac' WHERE name = 'Vitamina B12 5 mg/mL Polinac Inyectable x 2 mL';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Diclofenac Potásico 50 mg Diclodex PlusAndex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tamsulosina Tamsupros 0,4Mg 30 Cap';
UPDATE products SET brand = 'Leti' WHERE name = 'Sildenafil 50 mg Viasek Leti';
UPDATE products SET brand = 'Farma' WHERE name = 'Nebivolol 5 mg Tonervol Laboratorios Farma';
UPDATE products SET brand = 'Calox' WHERE name = 'Bisoprolol Fumarato 5 mg Calox';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Acetaminofén + Clorfeniramina + Cafeína Angrip Forte x10';
UPDATE products SET brand = 'Tiares' WHERE name = 'Itraconazol + Secnidazol 33,33mg/166.66mg Itrasec Tiares';
UPDATE products SET brand = 'Leti' WHERE name = 'Aciclovir 1 g Aciclor A.P. Leti';
UPDATE products SET brand = 'La Santé' WHERE name = 'Rosuvastatina 10 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diclofenac Sódico';
UPDATE products SET brand = 'Val' WHERE name = 'Magnesio Para Niños Happy Kids Arándano Frambuesa VAL x 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Comprimido Nunu Sin Azucar Sabor Patilla-Mandarina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Discos De Algodon Tails 70Und';
UPDATE products SET brand = 'Leti' WHERE name = 'Metformina 500 mg Canfir LP Leti x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dipidol Dipirona 500 MG/ML I.M.';
UPDATE products SET brand = 'Unknown' WHERE name = 'Escitalopram';
UPDATE products SET brand = 'Vick' WHERE name = 'Vick Vaporub Tarro';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Kilose Himalaya 60capsulas Natural L';
UPDATE products SET brand = 'Vick' WHERE name = 'Vick Drops Pastillas Sabor Limon';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Freegells Cough Drops Miel Y Limón x 30 und';
UPDATE products SET brand = 'Tiares' WHERE name = 'Estradiol 0.01% Estrasyn Tiares Crema Vaginal x 30 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Captopril 25 mg Genven';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C + Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Leukoplast Estandar Transp 19 X 65 Mm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Fólico';
UPDATE products SET brand = 'Remeny' WHERE name = 'Ibuprofeno 400 mg Remeny';
UPDATE products SET brand = 'Unknown' WHERE name = 'Escitalopram 10 mg Escitapax Reliance Blister x 10';
UPDATE products SET brand = 'Rowe' WHERE name = 'PSI Bromazepam 6 mg Rowe';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Castaño de Indias 400 mg Venirex Naturlifes';
UPDATE products SET brand = 'Unknown' WHERE name = 'Compresa Fria Kerful';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Ácido Tranexámico 500 mg Xanextra Aless Pharmaceuticals';
UPDATE products SET brand = 'Procaps' WHERE name = 'Vitamina D3 Deferol 14.000 UI';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcachofa + Centella Asiática';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromhexina';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Aceite de Pescado Omega EPA 1000 mg Natural Systems Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Glutamine';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondopra';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol';
UPDATE products SET brand = 'JHC' WHERE name = 'Sutura Cromica 1.0 Aguja Circular Jhc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio 2fit Daily Boost Multivitamin 60cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiocolchicosido';
UPDATE products SET brand = 'La Santé' WHERE name = 'Atorvastatina 40 mg La Santé';
UPDATE products SET brand = 'Dollder' WHERE name = 'Heprox Tamsulosina 0,4 mg Dollder x 30 Cápsulas LP';
UPDATE products SET brand = 'Leti' WHERE name = 'Carvedilol 6.25 mg Genven';
UPDATE products SET brand = 'Leti' WHERE name = 'Nifedipina 60 mg Tensomax L.P Leti';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Calox' WHERE name = 'Dimenhidrinato 50 mg Viajesan Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lecitina de Soya';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Vitamina Farmatodo Vitaminas y Minerales Sábila y Colágeno x 30';
UPDATE products SET brand = 'Genfar' WHERE name = 'Trimebutina 200 mg Genfar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno Polvo';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Vaccinium Macrocarpon 500 mg Cranberry Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Mallen' WHERE name = 'Neumocort + Aeromed 200mcg Aerosol 200Dosis Budesonida Mallen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gelatina Sin Azúcar Vivo Sabor Piña x 22 gr';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Cetirizina 10 mg Cetral Siegfried';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola Karito';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostados Sabor a Chile y Lima';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite Canola En Spray';
UPDATE products SET brand = 'Ricola' WHERE name = 'Caramelos Duros con Hierbas y Edulcorante Ricola Sabor a Eucalipto';
UPDATE products SET brand = 'Klinos' WHERE name = 'Vitamina K1 10 mg Klinos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mometasona 0,1% Dermacortine Medihealth Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levinzol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Flemaxin N-Acetilcisteina 600 mg x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitanin';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antiacido Acifar Sabor Menta Farqui';
UPDATE products SET brand = 'Klinos' WHERE name = 'Multivitaminico Gotas Prosolvit Klinos';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Electrolítica Oral Suerolito Electrolitos 75meq/l + Zinc Sabor Fresa x 400 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quinoa Royal Blanca Andean Food x 500 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colactive Plus Ag Apósito Matriz De Colágeno con Plata 5cmX5cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Saccharomyces Cerevisiae Florax 100 Millones 5 Viales x 5 ml Adultos Hebron';
UPDATE products SET brand = 'Servitalento' WHERE name = 'Multivitaminico 60tabletas Servitalento';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitavision';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Vitamina C 500 mg FC Pharma';
UPDATE products SET brand = 'Calox' WHERE name = 'Metformina Calox 850 mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sultamicilina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ezolium';
UPDATE products SET brand = 'Mallen' WHERE name = 'Lactulosa Mallen 66,7mg/100ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adh Leukopor Blanco 2.50cm X 5m';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Arándano Negro Herbaplant 343 Mg X 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Femivital X 30 Cápsulas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Multivitamínico Multiviral Siegfried';
UPDATE products SET brand = 'Now' WHERE name = 'Probiotico Para Mujeres 20 Billones Now x 50 Cápsulas Veganas';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Multivitaminico Centab-Beta Pharmatech Vit Y Minerales 30Tabletas Pharmatech';
UPDATE products SET brand = 'Val' WHERE name = 'L-Glutamina 500 mg Val Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aciclovir';
UPDATE products SET brand = 'Calox' WHERE name = 'Aciclovir 200 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhidrato De Ambroxol Brocantol 15 Mg/5 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Forma elastica Deportivo Negro';
UPDATE products SET brand = 'Dollder' WHERE name = 'Ketorolac Trometamina 20 mg Dolak Dollder x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Med Comprinet Muslo Sz 1 T/s';
UPDATE products SET brand = 'Unknown' WHERE name = 'Compresa Gel Kx Para Zona Lumbar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Babilin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Centella Asiatica Adelgasen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Compresa Gel Kx Para Cabeza Y Cuello';
UPDATE products SET brand = 'Val' WHERE name = 'Melatonina 3 mg + Vitamina B6 + Magnesio VAL Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azitromicina Polvo para Suspensión';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol+Nistatina+Neomicina+Dexametasona+Lidocaina Vagilen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidralit Bebida Hidroelectrolitica Sabor Uva';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Skollage';
UPDATE products SET brand = 'Remeny' WHERE name = 'Ivermectina 6 mg Remeny';
UPDATE products SET brand = 'Unknown' WHERE name = 'Blister Colageno-Vit C';
UPDATE products SET brand = 'Calox' WHERE name = 'Sertralina 50 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Ácido Ascórbico + Zinc';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Sweetest' WHERE name = 'Edulcorante Sweetest';
UPDATE products SET brand = 'Dollder' WHERE name = 'Domperidona 10 mg Dompesin Dollder';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sitagliptina + Metformina';
UPDATE products SET brand = 'Val' WHERE name = 'Val Magtein';
UPDATE products SET brand = 'Now' WHERE name = 'L-Taurina 100capsulas Taurina Now';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketoconazol + Betametasona-+ Neomicina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Probiotico con Calcio y Vitamina C x 30';
UPDATE products SET brand = 'La Santé' WHERE name = 'Atenolol 50 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhidrato De Bronexina';
UPDATE products SET brand = 'Procare' WHERE name = 'Venda de Gasa Esteril Expandible Procare';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Noni';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Servitalento' WHERE name = 'Super Balanced B 100tabletas Complejo B Servitalento';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcifor extra vitamina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Prueba De Embarazo Hcg Bensamedic x 1 und';
UPDATE products SET brand = 'Europharm' WHERE name = 'Adhesivo Eurotrasp Eurofarm 2,5cm x 5m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Ab Vitos Pediatrico Gotas X 30 Ml';
UPDATE products SET brand = 'Barilla' WHERE name = 'Pasta Barilla Spaguetti';
UPDATE products SET brand = 'SPL' WHERE name = 'Vitamina C + Jengibre Kalifornia Endulzada con Splenda Jarabe 180 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Estradiol + Noretisterona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Fólico';
UPDATE products SET brand = 'Laproff' WHERE name = 'Albendazol 400 mg Laproff Suspensión Oral x 20 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Metformina Clorhidrato 850 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Simeticona Flatvin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Orlidiet';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Digesan';
UPDATE products SET brand = 'Arte Medico' WHERE name = 'Vitamina C + Vitamina E + Zinc + Arándano + Sauco 25/5/3/25/50mg Inmunogum Arte Médico x 30 Gomitas';
UPDATE products SET brand = 'K6' WHERE name = 'Manta de Yoga K6 5mm Con Bolso Colores Surtidos';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Omega 3 1000 mg Aceite De Pescado Natural System';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cascara Sagrada 300 mg Natural Premium x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Obleas de Amaranto Bites Coco Sin Azúcar Sin Gluten Halo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Absorbente Pharma Algi 10 Unidades Pharmalast';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Blister Glucosamina-Condroitina';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Pan' WHERE name = 'Crema Vitamínica Vitenol Cuidado Intensivo Piel Con Pantenol Vitaminas A y D x 15 gr';
UPDATE products SET brand = 'La Santé' WHERE name = 'Bencidamina Gar Sabor Menta Fresca Bucoxol La Santé Solución Tópica x';
UPDATE products SET brand = 'Vivax' WHERE name = 'Betaduo Vivax Solución Inyectable';
UPDATE products SET brand = 'Quim-Far' WHERE name = 'Metformina 500 mg Quim-Far';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bencidamina + Cetilpiridinio 3,0mg/1,0mg Bucoxol Gar Menta Fresca x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mometasona Momnase 50mcg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Irbesartan';
UPDATE products SET brand = 'Colmed' WHERE name = 'Vit A 25000UI 30capsulas Colmed';
UPDATE products SET brand = 'Unknown' WHERE name = 'Secnidazol';
UPDATE products SET brand = 'Vargas' WHERE name = 'Bisoprolol Biprolil 2,5Mg X 15';
UPDATE products SET brand = 'Unknown' WHERE name = 'Creatina Monohidratada Vida Fit Sin Sabor x 150 gr';
UPDATE products SET brand = 'Now' WHERE name = 'Omega 3 1000 mg Now Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Men''s Daily Formula 100';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico Gomitas Hair, Skin Y Nails 30 Unidades Sabor Fresa Eternal';
UPDATE products SET brand = 'Elmor' WHERE name = 'Minoxidil Zitoxil 3% Solución Elmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel De Ultrasonido Acuagel x 250 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diflucortolona + Isocolazol + Neomicina Neoderm';
UPDATE products SET brand = 'Unknown' WHERE name = 'N-Butil Bromuro De Hioscina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio 400 mg Linoflax Naturistik Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quinoa Club Musli Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cambur En Trozos Deshidratado Frusnack';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Proteina Pro';
UPDATE products SET brand = 'Leti' WHERE name = 'Complejo B Neuromix Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada St Dalfour Cereza Negra x 284 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suvit';
UPDATE products SET brand = 'Leti' WHERE name = 'Pantoprazol 40 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Angrip Noche 3Comprimidos Acetaminofen - Clorfeniramina Klinos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Forma Elastica Para Hombro Femenino Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Kx Elastica Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Biosure Ped 400 G';
UPDATE products SET brand = 'ASK' WHERE name = 'Termo deportivo ASK colores surtidos 700 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betametasona 5% Crema';
UPDATE products SET brand = 'Going' WHERE name = 'Gel Energetico Fresa Banano Going x 33 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cascara Sagrada';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Polietilenglicol Accualaxan Polvo Para Solución Oral Megalabs x 255 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Tiocolchicosido';
UPDATE products SET brand = 'Pharmacorp' WHERE name = 'Probiotics Premiun 25 Billon Cfu Pharmacorp x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'JUGO PURO DE SABILA BARUNU X';
UPDATE products SET brand = 'La Santé' WHERE name = 'Betametasona 0,1% Itisona Pharmetique Labs Crema x 30 gr';
UPDATE products SET brand = 'Procaps' WHERE name = 'Vitamina D Deferol 2000Ui';
UPDATE products SET brand = 'Unknown' WHERE name = 'Una De Gato';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitamínico Calcio + Vitamina D + Ácido Fólico + Hierro Calcibon Natal x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colágeno Hidrolizado Sanavita 30 Saches de 2.8 gr  x 84 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Doce-Plex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Antibacterial';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico My Relax 60';
UPDATE products SET brand = 'Nutragum' WHERE name = 'Nutragum Calcio vit D';
UPDATE products SET brand = 'Nutragum' WHERE name = 'Fibra Nutragum';
UPDATE products SET brand = 'Genia Care' WHERE name = 'Vitamina C Nutragum Kids Vit C Bolsa 90Unidades Genia Care';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhidrato de Difenhidramina-Cloruro de Amonio-Citrato de Sodio Benatux Menta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Activiton Extreme 30';
UPDATE products SET brand = 'Calox' WHERE name = 'Aciclovir 5% Calox Crema Tópica x 10 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loperamida 2 mg Geagar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Enantato de Noretisterona + Estradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bacillus Clausii';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bisoprolol + Hidroclorotiazida Xylon 5/6,25Mg';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 1%';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Geriatech Multivitaminico 30Capsulas Pharmatech';
UPDATE products SET brand = 'Biotech' WHERE name = 'Betametasona + Gentamicina 0,05%/0,1% Beproderm Biotech Crema x 15 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Alivet FA';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Merthiolate Rojo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Para mujeres 90';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tortas De Maíz Inflado Sabor Queso Cheddar Fitos x 120 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bascillus Clausii Clausy Suspension Oral 2Millardos/5Ml X 10 Vial';
UPDATE products SET brand = 'Unknown' WHERE name = 'Prueba Rápida de Embarazo Two5Med';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'ReCOCOvery Equilibrio Electrolitico y Recuperacion de Sales Electrolyte';