UPDATE products SET brand = 'Unknown' WHERE name = 'Ginseng Siberiano';
UPDATE products SET brand = 'Unknown' WHERE name = 'Moringa 60Capsulas Natural Premium';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio 2fit Ultimate BCAA 100cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas de Vinagre de Sidra de Manzana con Vitaminas Sweet Sydney 200 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Laxante Hierbas Naturales Naturalax X 20 Cápsulas';
UPDATE products SET brand = 'Vivax' WHERE name = 'Vitamina E + Selenio 400U.I./70mcg Selene Vivax';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Dextran70 0.1% Medigen Solución Oftálmica Lagrimas Artificiales x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina + Cafeína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Broxol Jarabe Adulto 120 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dimenhidrinato Dramanyl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B 30capsulas Jacfar';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Dextran 70 + Hidroxipropilmetilcelusosa 0.1%/0.3% Lacrifort Solución Oftálmica x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Laxante Agarol Suave Picosulfato de Sodio Vaselina Liquida Emulsion Sabor Vainilla 390 ml';
UPDATE products SET brand = 'Ana Maria Lajusticia' WHERE name = 'Triptófano con Melatonina, Magnesio y Vit B6 Ana Maria Lajusticia 60';
UPDATE products SET brand = 'ASK' WHERE name = 'Cinturon Para Running Ask';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Cardo Lechozo 370 mg Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clindamicina 600 mg/4 mL Pisa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omega 3';
UPDATE products SET brand = 'Unknown' WHERE name = 'Propranolol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola Karito';
UPDATE products SET brand = 'La Santé' WHERE name = 'Omeprazol 20 mg La Santé';
UPDATE products SET brand = 'Rowe' WHERE name = 'PSI Zoldipem 10 mg Zolpidex Rowe x 10';
UPDATE products SET brand = 'Vivax' WHERE name = 'Vitamina E 400 mg Vivax';
UPDATE products SET brand = 'Farma' WHERE name = 'Citrato de Magnesio 622,28mg Magalex Laboratorios Farma x 30 Cápsulas';
UPDATE products SET brand = 'Genfar' WHERE name = 'Vitamina C 500 mg Genfar 12';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Cloruro De Magnesio Arcoiris x 240 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Doce-Plex';
UPDATE products SET brand = 'Polinac' WHERE name = 'Aciclovir 50 mg Polinac Crema x 20 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Metformina Clohidrato 750 mg Canfir L.P Leti';
UPDATE products SET brand = 'Neilmed' WHERE name = 'Solución Salina Spray PediaMist Kids Neilmed x 75 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para Dolor Cervical Medipatch x 12 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chips De Maiz Sin Gluten';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Agua Destilada x 1 Lt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Distrovit Condroitina Glucosamina KCL+Colageno+Acido Hialuronico+Magnesio+Calcio + Vit C 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Distrosil Forte 30capsulas Extracto Cardo Mariano-Coezima Q10-Vit B1-Vit B6 Distrilab';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína Chips Quest Chile - Limón x 32 gr';
UPDATE products SET brand = 'Val' WHERE name = 'Citrato De Magnesio 500 mg VAL Frasco x 60';
UPDATE products SET brand = 'Val' WHERE name = 'Vitamina D3 5000 UI VAL Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol Pamezone';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen Hioscina N-Butilbromuro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Cafe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Name Salvaje';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Polietilenglicol 3350 Pasolax Siegfried Polvo x 100 gr';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Diclofenac Sodico 100 mg Aless Pharmaceuticals';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Complejo B Grausin Jarabe Megalabs';
UPDATE products SET brand = 'La Santé' WHERE name = 'N-Acetilcisteína 600 mg Pulmolix Pharmetique Labs x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mucolin Ambroxol Clembuterol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén  Ananty Forte 160 mg/5ml 60 ml Suspensión';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Echinacea 390 Mg 60 Cápsulas Herbaplant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colágeno + Vitamina C + Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Centella + Alcachofa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Nutrifarm Hair&Nails 30 Cápsulas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Mary' WHERE name = 'Arroz Mary Bio Integral x 800 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Viusid 9Und';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Centab-Beta Pharmatech Vit y Minerales 60tabletas Multivitaminico Pharmatech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Algodón Hombre Rodilla 18-23 mmHg Talla 3 Color Azul';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Dextroclorfeniramina Maleato + Cafeina';
UPDATE products SET brand = 'Nutritek' WHERE name = 'L-Carnitina 120Cap Nutritek';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio 2fit Advanced B-Complex 100cápsulas';
UPDATE products SET brand = 'Altian' WHERE name = 'Acicran 30tabletas Extracto de Cranberry-Vitamina C Altian Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Reall Kids 60 Gomas Sabor Naranja';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina de Soya Soy Protein Isolate Vainilla Dulcilina x 250 gr';
UPDATE products SET brand = 'Naturlife' WHERE name = 'garcina cambogia nat 50capsulas naturlife''s';
UPDATE products SET brand = 'Unknown' WHERE name = 'Prednisona Diacort';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida 2,6mg/ml Lanceran Bioquimica Solución Gotas Pediátricas x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mezhitin Memantina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Inmovilizadora Zuviss Fibra De Vidrio 5cm x 3.6m';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Electrolítica Oral 75meq/l Suerolito Sabor Coco x 400 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lactobacillus Acidophilus Lactovac Suspensión x 12 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Extracto Seco Raíz Cimifuga 40 mg Femadonna Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Doce-Plex';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Polietilenglicol 3350 Accualaxan Polvo Para Solución Oral Megalabs 17 g x 7';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidralit Bebida Hidroelectrolitica 500 ml Sabor Coco';
UPDATE products SET brand = 'Procaps' WHERE name = 'Vitamina D3 Deferol 7.000 Ui 8 Cápsulas Procaps';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Noxpirin Grip Disp 4tabletas Acetaminofen - Clorfeniramina Meyer';
UPDATE products SET brand = 'Corpus' WHERE name = 'ProteviD 1000UI 15capsulas Vitamina D3 Corpus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metilcelulosa Fibracel';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina D3 200UI Diglet Leti Solución Oral Sabor Banana x 20 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Biotech' WHERE name = 'Betametasona + Gentamicina 0,1%/0,1% Betaderm Biotech Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nandrolone';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carbonato De Calcio + Vitamina D3 + Oxido De Zinc Kidcal Tutti Frutti Farma Suspensión x 180 ml';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Media Antiembolica Al Muslo Talla XL Sigvaris DYNAVEN';
UPDATE products SET brand = 'La Santé' WHERE name = 'Probioticos + Prebioticos + Zinc 5 Billones Prolardii Pharmetique Labs 10';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Vitamina E Arcoiris Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aciclovir 5% crema';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cintas de Prevención de';
UPDATE products SET brand = 'Elmor' WHERE name = 'Bencidamina Clorhidrato 0,15% Tantum Elmor Tópico Bucal x 240 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nutrifarm vitamina hair/nail 60Capsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Activiton Kids';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Magnesio Aminoquelado 90capsulas Pharmatech';
UPDATE products SET brand = 'Drofarvica' WHERE name = 'Calciden Natal 30tabletas Hierro - Acido Folico Drofarvica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gentamicine Sulfato 0,1% Crema Balaxi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bacumer Crema Booz 2.5%-2%-1%';
UPDATE products SET brand = 'La Santé' WHERE name = 'Losartán Potásico 50 mg La Santé x 30';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sódica 100 mcg Biumak';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Estin Arcoiris Jarabe x 240 ml';
UPDATE products SET brand = 'Ronava' WHERE name = 'Bacitracina 500ui/g Ronava Ungüento x 15 gr';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol  + Dexametasona 1%/0,04% Samson Laboratories Crema x';
UPDATE products SET brand = 'Elmor' WHERE name = 'Bencidamina 0,15% Tantum Elmor Spray Tópico Bucal x 45 ml';
UPDATE products SET brand = 'Nutritek' WHERE name = 'Whey Protein Evolution vainilla 904.5g Nutritek';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Acetato de Dexametasona + Clotrimazol 0.04%/1.0% Crema Alfa x 20 gr';
UPDATE products SET brand = 'Farma' WHERE name = 'Vitamina D3 200 UI Farma D Laboratorios Farma Solucion Oral Gotas x 10 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bacitracina Zinc + Neomicina + Polimixina B Triple Antibiotico SGG Ungüento Tópico x 15 gr';
UPDATE products SET brand = 'La Santé' WHERE name = 'Momeq 0.05% Furoato De Mometasona Spray Nasal Laboratorios Pharmetique';
UPDATE products SET brand = 'Procare' WHERE name = 'Gasa 4x8 Esteril Rx Detectable x 10 Unidades Procare';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Kelp Lecithin B6  and  Cider 30Tabletas Pharmatech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidramer Locion';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina 2.5mg/5ml Kimiceg Jarabe x 60 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhexidina 0,12% Peridont Enjuague Bucal x 240 ml';
UPDATE products SET brand = 'Biotech' WHERE name = 'Citrato de Calcio + Vitamina D + Zinc Eki Cal Biotech Suspensión x 120 ml';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Sábila 500 mg Laxante Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Irbesartan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Maalox Menta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Maleadex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio 2fit Max Pontecy CLA';
UPDATE products SET brand = 'Politecnicos' WHERE name = 'Novakosid Senosidos A - B 8.6 mg Laboratorio Politecnicos Nacionales x 20';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio 2fit Colageno Ultimate Formula 60cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Irbesartan';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Centella Asiática 500 mg Natural Systems Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Comprimido Nunu Sin Azucar Sabor Menta Suave';
UPDATE products SET brand = 'Unknown' WHERE name = 'Roskitas Horneadas De Yuca';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Aimdent Sin Azucar Sabor Sandia 18 Unidades';
UPDATE products SET brand = 'Klinos' WHERE name = 'Vitamina B12 Klinos';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para Dolor Lumbar Medipatch 12Und';
UPDATE products SET brand = 'Going' WHERE name = 'Gel Energetico Cafe Going x 33 gr';
UPDATE products SET brand = 'Naturlife' WHERE name = 'BCAA 3000 650 mg Naturlifes Frasco x 50 Cápsulas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Elegance 70% Alcohol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omega 3 Longevity';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'La Santé' WHERE name = 'Vitamina C 500 mg La Santé x 10';
UPDATE products SET brand = 'Leti' WHERE name = 'Dobesilato de Calcio 500 mg Doxiumx Leti';
UPDATE products SET brand = 'Rowe' WHERE name = 'Betametasona + Gentamicina + Iodoclorhidroxiquinolina 0,05/0,1/1% Tridetarmon Rowe Crema x 15 gr';
UPDATE products SET brand = 'Portugal' WHERE name = 'Betametasona 0.05% Betapluss Laboratorios Portugal Crema x 20 gr';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nebulizador/Compresor Sunset Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cevax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamin-C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitadynkids';
UPDATE products SET brand = 'Unknown' WHERE name = 'Transmisor para monitorear Glucosa Aidex Microtech GSM';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Citrato De Magnesio 500 mg Natural Systems Blister x 10 Cápsulas';
UPDATE products SET brand = 'La Santé' WHERE name = 'Vitamina C 500 mg La Santé Tira x 10';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Reall  Adultos 45 Gomas Sabor Fruta Adultos';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Geriatech Pharmatech Multivitaminico 60Capsulas';
UPDATE products SET brand = 'La Santé' WHERE name = 'Vitamina C 500 mg Sabor Chicle La Santé Sobre x 10';
UPDATE products SET brand = 'La Santé' WHERE name = 'Losartan Potasico+Hidroclorotiazida 100/25Mg 30Tab La Sante';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ivermectina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rivaroxaban';
UPDATE products SET brand = 'Biotech' WHERE name = 'Carvedilol 6.25 mg Carbatil Biotech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Potasio 10 mEq Stonex Supplymed 30';
UPDATE products SET brand = 'Leti' WHERE name = 'Lercanidipina 10 mg Genven';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sódica 50 Mcg Tiroxin Siegfried';
UPDATE products SET brand = 'Colmed' WHERE name = 'Minoxidil Forte 5% Colmed Solución Tópica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Drospirenona + Etinilestradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carbamazepina 200 mg Gencer';
UPDATE products SET brand = 'Zuoz' WHERE name = 'Oralzinc Mandarina Electrolitos Zuoz Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio + Magnesio Zinc + Vitamina D3';
UPDATE products SET brand = 'Val' WHERE name = 'L-Arginina + L-Citrulina 500 mg/250 mg Val Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antiacido Aplacal Banana';
UPDATE products SET brand = 'Vivax' WHERE name = 'Vitamina D3 Derovit 1000Ui 15Capsulas Blandas Vivax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Con Ferula Forma Elastica Izquierda Talla Xl';
UPDATE products SET brand = 'GVR' WHERE name = 'Roskita Horneadasde de Yuka con Ajo & Perejil  Representaciones GVR, C.A';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para Dolores';
UPDATE products SET brand = 'La Santé' WHERE name = 'Minoxidil Forte 5% La Santé Solución Tópica Frasco x 60 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nafina 1%';
UPDATE products SET brand = 'Now' WHERE name = 'Omega 3 1000 mg Now Frasco x 100 Cápsulas';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sódica 100 Mcg Tiroxin Siegfried';
UPDATE products SET brand = 'SNC Pharma' WHERE name = 'Donepezilo Dozher 10 mg SNC Pharma';
UPDATE products SET brand = 'La Santé' WHERE name = 'Orlistat 120 mg Xerograx Pharmetique Labs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Pure Egg Vainilla';
UPDATE products SET brand = 'Leti' WHERE name = 'Complejo B Neuromix Pediátrico Leti Solución Oral x 20 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Aciclovir 5% Aciclor Leti Crema x 10 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola Nature Valley Barra Mix Peanut x 35 gr';
UPDATE products SET brand = 'Calox' WHERE name = 'Levofloxacino 500 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Kx Elastica Talla L';
UPDATE products SET brand = 'Galderma' WHERE name = 'Galderma Benzac AC Wash Gel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hedraliv';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartán + Hidroclorotiazida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Secnidazol';
UPDATE products SET brand = 'La Piel' WHERE name = 'Parches Protectores Para Pies La Piel 6 Und';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Geriatech Multivitaminico 60tabletas Pharmatech';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Butilbromuro de Hioscina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clonedac Feet 1% Tópico Bifonazol x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Furoato de Mometasona Elok Loción Liali';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Ipalat Solución';
UPDATE products SET brand = 'Unknown' WHERE name = 'Torunda Adhesion';
UPDATE products SET brand = 'Unknown' WHERE name = 'Polvo de Moringa Saneta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aspirador Nasal Cleanoz';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Cebolla Morada Beusan Herbaplant Jarabe x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Superalimento Quinoa Naru';
UPDATE products SET brand = 'Leti' WHERE name = 'Acetaminofén + Clorferinamina + Pseudoefedrina + Dextrometorfano Alivet FA';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Baston Dynamics 4 Ptos Base Pqna S1 Azul';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina C 500 mg Letisan';
UPDATE products SET brand = 'Polinac' WHERE name = 'Centella Asiática 2% Madecassol Polinac Polvo x 5 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acido Folico';
UPDATE products SET brand = 'Deva' WHERE name = 'Mometasona Monaliz 50 mcg x 140 Dosis Spray Nasal Deva Holding';
UPDATE products SET brand = 'Neilmed' WHERE name = 'Solución Salina Spray NasaMist Neilmed x 75 ml';
UPDATE products SET brand = 'Biohlab' WHERE name = 'Sistema Flow-Vu Aerochamber +5 años Biohlab';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Jengibre Con Miel FC Pharma Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bicarbonato de Sodio + Alginato de Sodio Refluxyl Frasco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromexina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromuro de Pinaverio + Simeticona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Bactericida Germicida Peridex 180 Ml';
UPDATE products SET brand = 'Elmor' WHERE name = 'Alres Granulado 10Sobres Acetaminofen - Clorprofenpiridamina - Cafeina Elmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carbocisteína Sin Azúcar';
UPDATE products SET brand = 'Unknown' WHERE name = 'N-Acetilcisteina NAC';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Acetaminofen + Clorfeniramina Noxpirin';
UPDATE products SET brand = 'La Santé' WHERE name = 'Cetilpiridinio Solunovar 0,05%';
UPDATE products SET brand = 'Farma' WHERE name = 'Acetaminofén + Clorfeniramina 125-1mg/5ml Teragrip Lab Farma Frasco x 120 ml Jarabe Pediátrico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ginseng Vigory';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodón Chicco Motas';
UPDATE products SET brand = '3M' WHERE name = 'Yoga Mat 3mm Fucsia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio + L-Triptofano + Vitaminas Grupo B CollVital Frasco x 120 Cápsulas';
UPDATE products SET brand = 'Naturlife' WHERE name = 'neonavit 30tabletas naturlife''s';
UPDATE products SET brand = 'Unknown' WHERE name = 'L´Treonato de Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C 500 mg 60 gomitas masticables Falidu';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Miel y Limon 12 Unidades Damel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche de Almendras Original Scotti 1lt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Blister Centella Asiatica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Trazel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina Sinutil Jarabe Pediatrico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Cafeina + Clorfeniramina Ascafyl Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gliclazida Glucofred';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Ursodesoxicólico 300 mg Nio x 30';
UPDATE products SET brand = 'Now' WHERE name = 'Selenio 100mcg 100tabletas Now';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Super Protein Aminos 100tabletas Pharmatech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kalan obleas de amaranto sin azúcar y sin gluten sabor Red Velvet';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Delgaplant 500 Mg 60 Cápsulas Herbaplant';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Centella Asiatica + Alcachofa 90 Cápsulas';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Quinchoncho 300 mg Arcoiris Frasco x 90 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack De Quinoa Club';
UPDATE products SET brand = 'Now' WHERE name = 'Creatina Now X 120 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alpha Lipoic Acid';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminas Para Hombres Ziel Pharma Frasco x 50 Gomitas';
UPDATE products SET brand = 'Now' WHERE name = 'Vitamina C Con Rose Hips Now 1000 Mg X 100';
UPDATE products SET brand = 'Remeny' WHERE name = 'Clorhidrato Verapamilo 80 mg Remeny';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Citrato De Calcio + Vitamina D Pharmatech 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Freegells Cough Drops Cereza 30und';
UPDATE products SET brand = 'K6' WHERE name = 'Ejercitador Doble K6';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Diclofenac Potásico 50 mg Aflamax Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metabas Multivitaminico Solucion Inyectable x2';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sabe Miel Plus Jarabe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sabe Miel Berro/Eucalipto Jarabe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico Probiotics con Cranberry 30';
UPDATE products SET brand = 'Pan' WHERE name = 'Pan De Sandwich Sin Huevo Libre de Gluten Tradicional Victorias Natural Foods x 720 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Reall Adultos Hsn 45 Gomas Sabor Fresa Easy Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jugo Alberry Arandano con Azucar';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Cafeína + Clorfeniramina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina + Cafeina Alipal Forte Dia/Noche 6';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levonorgestrel 0,75 mg Postinor 2 Gedeon Richter';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zinc Gluconate';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sulfato de Zinc 15 mg Zincosol Biofarco Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tostaditas con Proteina de Quinoa Natural Quinoa Club x 45 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Corn Flakes Sin Gluten Noglut';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina 10 mg Zyrtec GSK Farma';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tortitas de Arroz 3 Pack Sarraceno Choco Negro Sin Gluten Santiveri';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sábila Aloe Vera Premium 300 mg Natural Premium Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Sin Gluten Whole O''s Nature''s Path x 325 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dong Quai';
UPDATE products SET brand = 'Now' WHERE name = 'Probiótico-10 25 Billones 30capsulas Now';
UPDATE products SET brand = 'Unknown' WHERE name = 'Probiticos Masticables Con Fibra Niños 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para El Control Del Apetito The Patch Club x 6';
UPDATE products SET brand = 'Unknown' WHERE name = 'Atorvastatina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Wampole Naranja Aceite de Hígado de Bacalao + Vitaminas Del Complejo B Emulsión x 200 ml';
UPDATE products SET brand = 'Dixson' WHERE name = 'Pelota de yoga Dixson 55 Cm';
UPDATE products SET brand = 'Leti' WHERE name = 'Citrato De Magnesio 647 mg Genven Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collar BSN Cervical Suave M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Isotónica Esteril de Agua de Mar Tonimer';
UPDATE products SET brand = 'Unknown' WHERE name = 'ALG LADY FACE MOTAS 50 UND';
UPDATE products SET brand = 'Drofarvica' WHERE name = 'Calciden Vit D Alfa 30tabletas Calcio Citrato - Vitamina D3 Drofarvica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Roniprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cefadroxilo';
UPDATE products SET brand = 'La Santé' WHERE name = 'Bencidamina Bucoxol Gar Miel Y Limón La Sante';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Polietilenglicol 400 + Propilenglicol 0,4%/0,3% Systalan Ultra Lansier Solucion Oftalmica Frasco x 1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amikacina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dexametasona 4 mg/1ml Corpo Meca Solución Inyectable x 1';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Montelukast 10 mg + Desloratadina 5 mg Roweluk Ultra Rowe Megalabs x 30';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Proteina Dark NuGo Mani';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Zuzu' WHERE name = 'Sulfato de Zinc 50 mg Zuzu';
UPDATE products SET brand = 'Unknown' WHERE name = 'Champu BAF Farmagenik Tratamiento Psoriasis-Seborra x 230 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio + Vitamina D3 + Zinc Calzinc D Biofarco Suspensión Oral Pediátrica x 240 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Plantago Ovata Sabor Naranja';
UPDATE products SET brand = 'Leti' WHERE name = 'Silibina Fostolipido 120 mg Hepagras Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Steritex Hidrofilo 250 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Silvederma 1% Sulfadiazina De Plata Medifarm Tarro x 500 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bisoprolol 2,5 mg Antaar MCK Pharmaceutical';
UPDATE products SET brand = 'Tiares' WHERE name = 'Hidrocortisona + Lidocaina + Zinc + Alantoina Anomex Tiares';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antifom';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medihealth Dermacotine 0,1% Mometasona Locion';
UPDATE products SET brand = 'Unknown' WHERE name = 'NEV Valvey 100 UI/ml 5 Cartuchos Insulina Glargina Wockhardt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acido Fusidico 2%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Cartilago C/Una gato 250-250mg 60capsulas Herbaplant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vinagre De Sidra De Manzana 500 mg + Ácido Fólico Sin Azúcar Varitylabs Falidu Frasco x 60 Gomitas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ginkgo Biloba';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Men Xtra Performance 60tabletas Pharmatech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Tela 3.5cm x 4.57m Briutcare 1Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Leukoplast Elastica 1.9 X 7.6 Cm Stand 100';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein Isolate Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collarin Cervical Dynamics talla XL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azúcar de Coco Orgánico Kaldini x 500 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Vitrum 50+ Adultos 100';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Magnesio Aminoquelado 100tabletas Pharmatech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Probiótico 18 Billones UFC CollVital Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Vick' WHERE name = 'Alcanfor + Mentol + Eucalipto Vick Vaporub Ungüento x 50 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Energéticas Bolt Sabor Fresa x 60 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Plantillas Gel Microfibra Palc T-38/39';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pepto Bismol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sitagliptina + Metformina';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Laxante Cascara Sagrada 430 Mg Herbaplant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Labial Pretty Matte Lipstick 140';
UPDATE products SET brand = 'Unknown' WHERE name = 'Enema Fosfato de Sodio Monobasico 160 mg/ml - Fosfato de Sodio Dibasico 60 mg/ml SaludX.';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola Integral S/Azúcar';
UPDATE products SET brand = 'Biohlab' WHERE name = 'Ranitidina Sin Azúcar 75 mg Gastrodul Biohlab Jarabe x 100 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Una de diablo';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Nutrisite Restore';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glutamina 500 mg Naturistik Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Colageno 1000 mg Farmatodo Frasco x 30';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Glucotrin 60capsulas Glucosamina-Colágeno-Ácido Hialurónico-Mg Pharmatech';
UPDATE products SET brand = 'Leti' WHERE name = 'Nifedipina 10 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Melody Motas 50 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Onagra Evening Primrose Oil';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Nutrisite HMB 31.5g Alimento Nutritivo Cicatrizante Medsite';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D3 400U.I./ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Gidagus 10 2Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B Pharmacheck 2 ml x 1';
UPDATE products SET brand = 'Calox' WHERE name = 'Vitamina C Ácido Ascórbico 500 mg Cevax Calox';
UPDATE products SET brand = 'Now' WHERE name = 'Vitamina A 10.000 IU Now Frasci x 100 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bisoprolol-Hidroclorotiazida 2.5Mg/6.25Mg Antaar Hct Mck';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'EnterUni';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gymens';
UPDATE products SET brand = 'Unknown' WHERE name = 'CO Q-10';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Complejo B Miovit Cofasa';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Ibuprofeno 400 mg PlusAndex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Meloxicam 15 mg Medigen';
UPDATE products SET brand = 'Meyer' WHERE name = 'Espironolactona 25 mg Meyer';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartán Potásico + Hidroclorotiazida';
UPDATE products SET brand = 'Elmor' WHERE name = 'Famotidina 40 mg Ulcenol Elmor';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Europharm' WHERE name = 'Apósito Adhesivo Euromed Eurofarm 8 x 10 cm x 6 unds';
UPDATE products SET brand = 'Unknown' WHERE name = 'Compresa Caliente Kerful';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina + Sitagliptina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Arasens 2%';
UPDATE products SET brand = 'La Santé' WHERE name = 'Tadalafilo 20 mg TalystoR Pharmetique Labs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Prednisona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhidrato de Terbinafina Crema 1%';
UPDATE products SET brand = 'Leti' WHERE name = 'Ciprofloxacina 500 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Memantina 10 mg  Biumak';
UPDATE products SET brand = 'Unknown' WHERE name = 'Klincosal';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ceftriaxona Ronamedic';
UPDATE products SET brand = 'Leti' WHERE name = 'Sertralina 50 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelos Palotes Sin Azucar Damel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Suplemento Goli Gomitas Vinagre De Sidra Manzana 60 Cap';
UPDATE products SET brand = 'Vivax' WHERE name = 'Complejo B Neuribe Vivax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Spaguetti Integral Nnova Rice';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sitagliptina + Metformina 50/500Mg Crisomet';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Algobap 3"X3" X2Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Algobap 4"X4" X2Und';
UPDATE products SET brand = 'Pan' WHERE name = 'Pañal De Adulto Tipo Pants Pull Ups Clinicas M x 6 und';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Jerico' WHERE name = 'Epivital Antioxidante Jerico x 15 Cápsulas';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato Ulcon';
UPDATE products SET brand = 'Pan' WHERE name = 'Pancreatina Orozim';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quetiapina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Agua de Coco Badia';
UPDATE products SET brand = 'Pan' WHERE name = 'Trimebutina Maleato 300 mg Colypan';
UPDATE products SET brand = 'Behrens' WHERE name = 'Fluconazol 200 mg Fungomax Behrens Solución Infusión x 100 ml I.V';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magaldrato + Simeticona Sin Azúcar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sanavita Colageno Skin Polvo Sabor a Piña y Menta';
UPDATE products SET brand = 'Unknown' WHERE name = 'GlutaDose Inmune 60viales';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Elmor' WHERE name = 'Oxolamina 1% Perebron Elmor Jarabe Frasco x 120 ml';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Omega Epa 30capsulas Natural System';
UPDATE products SET brand = 'Unknown' WHERE name = 'Immune Support Kids';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Acido Absorbico';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Farmatodo Absoluto 500Cc';
UPDATE products SET brand = 'Pan' WHERE name = 'Pantoprazol';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'La Santé' WHERE name = 'Azitromicina 500 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sódica 100 mcg Eutirox Merck';
UPDATE products SET brand = 'La Santé' WHERE name = 'Carvedilol 6.25 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Montelukast';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema para untar de avellanas sin gluten Chocotella';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Gotas Nasales Silin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartán + Hidroclorotiazida';
UPDATE products SET brand = 'Pan' WHERE name = 'Bebida proteica Pancake Fit  Egg White Protein Cacao';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glutamina + Zinc';
UPDATE products SET brand = 'Procare' WHERE name = 'Gasa Sobre 4X4 Procare. X2und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fit&Slim Evolution';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te De Limon Sin Azucar';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Negro +2.5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Protector de colchon All Pro Full';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zabila + Cascara Sagrada Gameral';
UPDATE products SET brand = 'Unknown' WHERE name = '7 V Energy Shot';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nicarle Lercanidipina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Atorvastatina 40 mg DAC';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartán + Hidroclorotiazida';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Complejo B Miovit Cofasa Solución Gotas x 20 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola Vainilla Naturgourmet';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartán Potásico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartán Potásico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amino Complete 120';
UPDATE products SET brand = 'Behrens' WHERE name = 'Cloruro de Sodio 0,9% Part-Fill Behrens Frasco x 100 ml Solución Fisiológica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Energyplant X 60 Cápsulas';
UPDATE products SET brand = 'ASK' WHERE name = 'Pesas Munequeras o tobilleras ASK 0.5 k 2 und';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Infusion Natural Hinojo/hierbabuena';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Cardiolife';
UPDATE products SET brand = 'Colmed' WHERE name = 'Complejo B 30cap Colmed';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Demi +2.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clopidogrel 75 mg Cloptan Zoriak';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hioscina N-Butilbromuro + Acetaminofén';
UPDATE products SET brand = 'Laproff' WHERE name = 'Metoclopramida 10 mg Laproff Blíster x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Curcumit';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Hepaprotec 500 Mg 60 Cápsulas Herbaplant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Bactericida Somedine 120 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply7 Rizos de Quinoa Sabor a Queso Cheddar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Prokal L-Carnitina Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Prokal L-Carnitina Cho';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cristal De Aloe Vera Con Pulpa 99% Barunu Frasco x 170 gr';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Portil Clotrimazol-Gentamicina-Dexametazona Crema';
UPDATE products SET brand = 'Unknown' WHERE name = 'Apósito Gel Cicatrizante Nanoskin Soft x 50 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Urea 12% Brucen Frasco x 400 ml Gel Limpiador Capilar (Psoriasis)';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Autirice';
UPDATE products SET brand = 'Calox' WHERE name = 'Metformina 500 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D3 1000 IU = 25 mcg  Falidu Frasco x 30 gomitas masticables';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Betametasona + Clotrimazol + Neomicina 0,05g/1g/0,35g Clobedet  A Medical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Limon con Vitamina C 12 Unidades Damel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Careta Protectora Facial Ergonomica 1 Und';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Cystone Himalaya 100Tabletas Natural L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amlodipina';