UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina 1% Terbicrym Avpharma Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Prokal L- Carnitina Mant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Nutrigamma';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Sildenafil 100 mg Sildex PlusAndex x 1 Tableta';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Sildenafil 50 mg Sildex PlusAndex';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente de Lectura Optiko Protección Luz Azul +1.0';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Gris Redondo +3.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tartaletas De Ricota y Espinaca Libre De Gluten Que Bites x 12 und';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Ketoprofeno 100 mg PlusAndex';
UPDATE products SET brand = 'Valmor' WHERE name = 'Sildenafil 50 mg Duroval Valmor x 3';
UPDATE products SET brand = 'La Santé' WHERE name = 'Rosuvastatina 20 mg La Santé';
UPDATE products SET brand = 'Valmor' WHERE name = 'Sildenafil 100 mg Duroval Valmor x 1 Tableta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quetiapina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pizza 4 Cabras Masa Almendra / Chia Libre de Gluten BurbujaPizza';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pizza 4 Cabras Masa Garbanzo / Yuca Libre de Gluten BurbujaPizza';
UPDATE products SET brand = 'Pan' WHERE name = 'Pan Sandwich Multigrano Integral Victorias Natural Fooods x 720 gr';
UPDATE products SET brand = 'La Santé' WHERE name = 'Oximetrazolina 0,05% Airex Pharmetique Labs Solución Nasal Descongestionante x 15 ml';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Metformina Clorhidrato 500 mg Plusandex';
UPDATE products SET brand = 'Pan' WHERE name = 'Pan Sandwich Sin Cereales Victorias Natural Fooods x 720 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Bisoprolol Fumarato 1,25 mg Biotalol Leti';
UPDATE products SET brand = 'Leti' WHERE name = 'Bisoprolol Fumarato 5 mg Genven';
UPDATE products SET brand = 'Rowe' WHERE name = 'Bumetanida 1 mg Bumelex Rowe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico';
UPDATE products SET brand = 'Quim-Far' WHERE name = 'Omeprazol 20 mg Omefar Quim-Far';
UPDATE products SET brand = 'Unknown' WHERE name = 'Albendazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Atorvastatina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Antiseptico Guardian';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Steritex Desmaquillante Discos 60Unds';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciprofloxacina';
UPDATE products SET brand = 'SNC Pharma' WHERE name = 'Telmisartán  80 mg Termisur SNC Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Antiseptico Guardian';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glucerna Vainilla x 400 gr';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Pan Blanco Schar';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Lasagne Schar';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Muesli Frutas Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche de Ojo Zuviss x 10 Unidades Grupo Cleanup';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gel Antibacterial Farmatodo';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Agua Oxigenada Guardian';
UPDATE products SET brand = 'CureBand' WHERE name = 'Curitas CureBand';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Micropor Piel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Transpiel 30 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Unicornio 6 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Caliente Alivio Medipatch Talla M10Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ortoban Yeso 8" X 3YDS  1Rollo 20 cm x 2,7 M';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Sildex Sildenafil 50 mg PlusAndex x 2';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miovit Kit';
UPDATE products SET brand = 'Leti' WHERE name = 'Risedronato Sódico 150 mg Oxidren Leti';
UPDATE products SET brand = 'Calox' WHERE name = 'Ketoprofeno 100 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida Farmers Aloe Vera';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida Aloe Farmers Granada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida Farmers Sin Azucar Aloe Vera';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida Aloe Farmers Fresa';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Tobramicina 0,3% Tobrasol Oftalmi Solución Oftálmica x 5 ml';
UPDATE products SET brand = 'Farma' WHERE name = 'Acetaminofen + Clorfeniramina 650/4mg Teragripforte Noche Farma';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Algodón Farmatodo Hidrofilo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cepillo Quirurgico Sol Iod Bioscrub';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite De Oliva Chacon Extra Virgen';
UPDATE products SET brand = 'Vivax' WHERE name = 'Kinerton Vivax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento nutricional Nutradition Hmb Premium Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento Nutricional Nutradition Ad Fos Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Resistentes al agua Transpiel 10 Unidades';
UPDATE products SET brand = 'Klinos' WHERE name = 'PSI Zoldipem Klinos';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Timolol 0,50% Matilol Oftalmi Gotas Oftálmicas x 6 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento Nutricional Nutradition Ninos Fresa';
UPDATE products SET brand = 'Pan' WHERE name = 'BEB TERRAEPANE RICE ALMENDRA1 LT';
UPDATE products SET brand = 'Pan' WHERE name = 'BEB TERRAEPANE RICE NATURAL 1 LT';
UPDATE products SET brand = 'Unknown' WHERE name = 'Airoplast Adhesivo de plástico transparente Pharmaplast 1,25x5 1 Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Elastica Kx Ventilada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Candistat 1% Crema';
UPDATE products SET brand = 'Unknown' WHERE name = 'CuritasTransparentes Briutcare x 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein 2 Fit sabor a vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Linaza Con Ajonjoli';
UPDATE products SET brand = 'Pan' WHERE name = 'Mezcla para panquecas Pancake Fit Cacao';
UPDATE products SET brand = 'Pan' WHERE name = 'Mezcla para panquecas Pancake Fit Canela';
UPDATE products SET brand = 'Pan' WHERE name = 'Mezcla para panquecas Pancake Fit Original';
UPDATE products SET brand = 'Unknown' WHERE name = 'Trimebutina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Orlidiet';
UPDATE products SET brand = 'Klinos' WHERE name = 'Tadalafilo 20 mg Tadifil Klinos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ramipres';
UPDATE products SET brand = 'Vincenti' WHERE name = 'Tirotricina + Antipirina 0,1g-4g/100ml Otan Vincenti Gotas Óticas x 5 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Nivel 1';
UPDATE products SET brand = 'SPL' WHERE name = 'Splash Antibacterial Isogel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Kinesiologica Precortada 5mts Volk';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Kx Para El Brazo Tipo Malla Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Estabilizadora Kx Con Bisagra De Neopreno Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Soporte Para Muslo Kx Neopreno Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Spraymedic Alcohol Antiseptico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Hideven Rollo 100 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Protosulfil';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ranitidina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica Saito Ortopedica 15 Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parches para Fiebre de Gel Frío para Niños 6 unidades Two5med';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Quinoa y Banana Wipala x 35 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Energético Banana y Coco Wipala x 32 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gastro Aliv';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartan';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina 100Mcg 30Tab Colmed';
UPDATE products SET brand = 'Leti' WHERE name = 'Levodropropizina 0,6% Antux Leti Solución Oral x 120 ml';
UPDATE products SET brand = 'Vargas' WHERE name = 'Loperamida 2 mg Loperam Vargas';
UPDATE products SET brand = 'Vargas' WHERE name = 'Lactulosa 10,1g/15ml Moderan Vargas Solución';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Terbinafina 1% Perten Siegfried Crema x 20 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esparadrapo Quirurgico Pharmamed 2,5x4,55 1 Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Coco Virgen Prensado al Frio Altagua x 500 ml';
UPDATE products SET brand = 'Going' WHERE name = 'Proteina Sabor Vainilla Going x 600 gr';
UPDATE products SET brand = 'Going' WHERE name = 'Hidratante Sabor Uva Going x 300 gr';
UPDATE products SET brand = 'Going' WHERE name = 'Hidratante Sabor Limonada de Coco Going x 300 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Diclofenac Potásico 50 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Merey Premium con Sriracha y Miel x 250 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dexametasona';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Metronidazol 500 mg Aless Pharmaceuticals';
UPDATE products SET brand = 'Calox' WHERE name = 'Prednisona 5 mg Calox';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sodica 50Mcg 30 Tab Colmed';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diclofenac Potasico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Eurofix 5cm x 10m Eurociencia';
UPDATE products SET brand = 'Elmor' WHERE name = 'Dimetilpolisiloxano 125 mg Flatoril Elmor';
UPDATE products SET brand = 'Vivax' WHERE name = 'Derovit D3 1000UI 30capsulas Vivax';
UPDATE products SET brand = 'Ebben' WHERE name = 'Venda Elastica 15Cm Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Hideven Rollo 50 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela microporoso color beige 2,5 cm x 4,5 m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hepamarin';
UPDATE products SET brand = 'ASK' WHERE name = 'Cinturon Running con Botellas de Agua Ask';
UPDATE products SET brand = 'Pan' WHERE name = 'Premezcla de Panquecas de Arroz Sin Gluten Nnova Rice';
UPDATE products SET brand = 'K6' WHERE name = 'Base Para Flexiones K6';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Truballs Naranja y Nueces Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Truballs Chocomani Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Paracetamol + Cetirizina + Fenilefrina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Vermicelli Nnova Rice';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol 500 mg Alpharma';
UPDATE products SET brand = 'Leti' WHERE name = 'Diacereina 50 mg Artrodar Leti';
UPDATE products SET brand = 'Dollder' WHERE name = 'Diclofenac Sódico 1% Difenac Dollder Gel x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diltiazem';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol 500 mg Alpharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol + Miconazol 15%/4% Gynotran Exeltis Crema Tubo x 40 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'DistroMag';
UPDATE products SET brand = 'Calox' WHERE name = 'Deflazacort 30 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol Pediátrico 10 mg Disomez Distrilab';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela impermeable color beige 5 cm x 4.5 cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Steriph Comprimida 1 Und';
UPDATE products SET brand = 'Pan' WHERE name = 'Mezcla para Panquecas de Avena Avelina Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Avena en Hojuelas Avelina Sin Gluten';
UPDATE products SET brand = 'La Santé' WHERE name = 'Loratadina 10 mg La Sante';
UPDATE products SET brand = 'Pan' WHERE name = 'Sin Gluten Heaven Pancake Baking Mix';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema Desmanchadora x 20 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Amoxicilina 500 mg Genven';
UPDATE products SET brand = 'Tiares' WHERE name = 'Levonorgestrel 1.5 mg Tiares';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bicarbonato de Sodio Botica Casera Sobre x 25 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum Niacinamida x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Timol 4% Fórmula Magistral Farmatodo Antimicótica Uñas Gotas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para Aliviar La Tos Medipatch';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Media Antiembolica Al Muslo Talla L Sigvaris DYNAVEN';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Media Antiembolica Al Muslo Talla S Sigvaris DYNAVEN';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sin Gluten Heaven Vanilla Cake Mix';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jabón Neutro Fórmula Farmatodo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiras Adhesivas Para Rodillas KT Tape';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Dynaven Sigvaris Beige Talla L 15-20 Pantorrilla x 2 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cintas kinesiologicas Pre Cortadas Sinteticas 20 X 25 Cm KT TAPE Color Negro';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Gris Talla S 15-20 Pantorrilla';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Negra Talla L 15-20 Pantorrilla';
UPDATE products SET brand = 'Polinac' WHERE name = 'Sal Efervescente Disfruta Clásico Polinac Maver x 5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cuerda De Saltar Especial Foam Jogger';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Parafina Frasco x 60 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gel De Árnica x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum Despigmentante x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema De Zabila Al 2% x 90 gr';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite de Palo x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Para Uñas Frasco x 10 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cepillo Quirurgico Seco Bioscrub';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Antiembolica Autoreggente Talla S Color Blanco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Rodilla 22-27 mmHg Talla 5 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Gambaletto 280 Den Talla 2 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collarin Blando Kx Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Kx Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ferula Inmovilizadora para tobillo Dynamics con bomba';
UPDATE products SET brand = 'Unknown' WHERE name = 'LIGA PARA AEROBIC BODY TRIMMER';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Dorzolamida 2% + Timolol 0,5% + Brimonidina 0,2% Xegrex Poen Solución Oftálmica x 5 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol + Miconazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diosmina + Hesperidina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartán + Hidroclorotiazida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartán + Clortalidona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collar BSN Cervical Suave S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias de compresion Jobst 15-20 negra talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Med Jobst 15-20dam.rod.beige L';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite de Ricino Frasco 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colchon Anti Escara sin motor';
UPDATE products SET brand = 'Calox' WHERE name = 'Prednisona 5 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Locion Nutracort 1%';
UPDATE products SET brand = 'Calox' WHERE name = 'Prednisona 50 mg Calox';
UPDATE products SET brand = 'Ronava' WHERE name = 'Propranolol 10 mg Algoren Ronava';
UPDATE products SET brand = 'Angelus' WHERE name = 'Prednisolona 5 mg Angelus';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Contorno Ojos x 15 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Peróxido Benzoilo 5% x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pregabalina 75 mg Pregatan Zoriak';
UPDATE products SET brand = 'Dollder' WHERE name = 'Ranitidina 150 mg Vizerul Dollder';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quetiapina';
UPDATE products SET brand = 'Intervit' WHERE name = 'Therma Gel Intervit Antifaz';
UPDATE products SET brand = 'Ebben' WHERE name = 'Venda Elastica 5Cm Ebben';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Crema Humectante con Protector Solar Frasco x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Protector Solar FPS30 Gel x 100 ml';
UPDATE products SET brand = 'Dollder' WHERE name = 'Ranitidina 75 mg Vizerul Dollder';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Serum Multivitaminico Hidratante Facial con Protector Solar Frasco x 30 Ml';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Ramipril 2.5 mg Ramipres Megalabs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medroxiprogesterona + Enantato de Estradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betametasona 0,05% - Acido Salicilico 3% Betasalic Unguento';
UPDATE products SET brand = 'Unknown' WHERE name = 'Spray Antibacterial Con';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Con';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Forma elastica Universal Talla Xl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Forma Elastica cierre magico negra talla L/XL';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Alumbre en Polvo Sobre/Papeleta x 25 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Desonida 0,1% Dermosupril Medihealth Loción Tópica x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias de Compresion Deportivas Training Start Talla M Sportlast';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Contorno de Ojos Frasco x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tadalafilo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato';
UPDATE products SET brand = 'Unknown' WHERE name = 'Telmisartan Renangio';
UPDATE products SET brand = 'Calox' WHERE name = 'Sertralina 50 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Trimetoprim + Sulfametoxazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Trimetoprim + Sulfametoxazol';
UPDATE products SET brand = 'Valmor' WHERE name = 'Tadalafilo 5 mg Tadafox Valmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vaso Mezclador Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pesa Tobillera 2 KG Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromexina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mancuerna 7 LB Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te De Durazno Sin Azucar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Desogestrel 0,075 mg Carmin Urufarma';
UPDATE products SET brand = 'Leti' WHERE name = 'Sulbutiamina 200 mg Tekron Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Batametasona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Flores de Manzanilla Botica Casera Sobre x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Crema Exfoliante Limpiadora Coconuez';
UPDATE products SET brand = 'Laproff' WHERE name = 'Dinitrato De Isosorbide 10 mg Laproff Blíster x 10';
UPDATE products SET brand = 'La Santé' WHERE name = 'Levosulpirida 25 mg Leprit Pharmetique Labs';
UPDATE products SET brand = 'Calox' WHERE name = 'Diosmina 600 mg Calox x 28';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dapagliflozina 10 mg Dapaxit Zoriak';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Diclofenac Potásico 1,8mg/ml Dicloret Oftalmi Suspensión Oral Pediátrica x 60 ml';
UPDATE products SET brand = 'Vivax' WHERE name = 'Atorvastatina 40 mg Atovarol Vivax';
UPDATE products SET brand = 'ASK' WHERE name = 'Cinturon para Running Ask';
UPDATE products SET brand = 'Unknown' WHERE name = 'Daglitan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Pharmapore Sterile 8x10 Pharmalast 5 Unidades';
UPDATE products SET brand = 'La Santé' WHERE name = 'Diclofenac Potásico 50 mg La Santé';
UPDATE products SET brand = 'Zuoz' WHERE name = 'Nitazoxanida 500 mg Nizox Zuoz';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nitazoxanida 500 mg Dac 55';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Deslorat 2,5mg/5ml';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Metronidazol 500 mg Aless Pharmaceuticals';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diosmina + Hesperidina 90/100';
UPDATE products SET brand = 'Ronava' WHERE name = 'Dexametasona 4 mg Decobel Ronava';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vendaje Neuromuscular Azul Pharma Kt 1 Unidad';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Inmovilizador Dynamics Codo C/bisag Bloqueo Art 42cm';
UPDATE products SET brand = 'Leti' WHERE name = 'Ácido Acetilsalicílico 81 mg Asaprol Leti';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina 5 mg Calox';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Ortesis Dynamics Rod Plus C/bisag Art 42m';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Antioxidante Frasco x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Difenhidramina Calamina Zukadryl Elea Loción x 100 ml';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Ortesis Dynamics con articulacion de disco larga';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jarabe Lamedor x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína NutriClara de Huevo Sabor Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pinaverio + Simeticona Aliverium';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miarepa Fit Mezcla Para Arepas de Auyama Saneta x 800 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mesames Drospirenona + Etinilestradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Proteína Pro Bar Caramelo x 70 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pamoato de Pirantel';
UPDATE products SET brand = 'Farma' WHERE name = 'Sacubitrilo + Valsartán 50 mg Neblum Laboratorios Farma x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ascenda';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Hioscina Analper Fem Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gelatina Sin Azúcar Vivo Sabor Durazno x 22 gr';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Enalapril 20 mg PlusAndex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Eurofix 15cm x 10m Eurociencia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Eurofix 10cm x 10m Eurociencia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fenitoina Sódica';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Solución Citrato De Potasio 10.8% Frambuesa x 500 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Eurofix 5cm x 5m Eurociencia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vinagre De Sidra De Manzana';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alumbre En Polvo Botica Casera Sobre x 25 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Agua de Rosas x 240 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Solución Citrato De Potasio Frambuesa x 500 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico';
UPDATE products SET brand = 'Calox' WHERE name = 'Azitromicina 500 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Albendazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Albendazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciproterona + Etinilestradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amikacina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Frutos Mixtos Naturales x 250 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche de Almendras Vilay Sabor Vainilla Sin Gluten/Sin Lactosa 1 Litro';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema Fría x 30 gr';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sodica 25mcg Eutirox Merck';
UPDATE products SET brand = 'Calox' WHERE name = 'Etoricoxib 60 mg Calox';
UPDATE products SET brand = 'Vivax' WHERE name = 'Cetirizina 10 mg Cetirivax Vivax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Domperidona';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Solución Fisiológica Gotas x 60 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Cloruro de Magnesio Polvo Para Disolver x 33.3 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Farmagenik Citrato de Potasio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fitex Tadalafilo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfomicina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amiodarona 200 mg Gencer';
UPDATE products SET brand = 'Ronava' WHERE name = 'Alopurinol 100 mg Aluron Ronava';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fluoxetina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Famotin';
UPDATE products SET brand = 'Elmor' WHERE name = 'Hepadesicol 325 mg Elmor';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Solución Citrato De Potasio 10% x 500 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina + Ambroxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Palitos De Maiz Ostin Horneados';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Ácido Tranexámico 500 mg Ciclokan Megalabs';
UPDATE products SET brand = 'Calox' WHERE name = 'Domperidona 10 mg Laboratorio Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miarepa Fit Mezcla Para Arepas de Remolacha Saneta x 800 gr';
UPDATE products SET brand = 'Pediasure' WHERE name = 'Pediasure Rpb';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel de Abeja  Sweetbess Sobre x';
UPDATE products SET brand = 'La Santé' WHERE name = 'Azitromicina 500 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Flebitop crema';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clindamicina';
UPDATE products SET brand = 'Calox' WHERE name = 'Carvedilol 25 mg Calox';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento alimenticio Proteinex Enterex x 275 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato De Magnesio 500 mg Preventud Plus Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clindamicina + Ketoconazol 100/400mg Clinfol Duo Tecnofarma';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Intimo Frasco x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciprofloxacino';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Kit Facial Fórmula Farmatodo Jabón Avena + Serum Acido Hialurónico + Serum Restaurador';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina A + D Adel Ponce y Benzo Ungüento x 50 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetilpiridinio + Lidocaína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azufre en polvo Botica Casera Sobre';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Antimicotica Plus Crema 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Fusilli América Orgánica Sin Gluten x 227 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio para Niños Happy Kids 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Truballs Naranja y Nueces Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Truballs Chocomani Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostados Snacks Sabor A Crema Y Cebolla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multigen Sin Azucar Fresa';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento Alimenticio Enterex Diabetic Vainilla x 400 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Helios Diet Sin Azúcar Frambuesa x 280 gr';
UPDATE products SET brand = 'Barilla' WHERE name = 'Barilla Penne Rigate Integral';
UPDATE products SET brand = 'Behrens' WHERE name = 'Centella Asiática 500 mg Redugras Behrens Frasco x 30 Cápsulas Blandas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levocetirizina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostado The Pod Snacks Sabor A Especies Arabes';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite De Almendras';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oh Snack Natural Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Proteína Quest Cookie Dough x 60 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Proteina Nature Valley Peanut Butter x 40 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kalan Krunch Nuez sin azúcar y sin gluten';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Multivitaminico Plexamin Siegfried Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta  Animalitos America Organica Sin Gluten';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Salti Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel Sin Azucar Natures Hollow';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante Truvia Stevia Bolsa Refill';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Viusid 90UND';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Damel Sin Azucar Gummy Bears x 100 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Enrollados Laminado Frolls Parchita';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Savoiardi Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pastillas Detox Triple';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack De Maiz Europa';
UPDATE products SET brand = 'SPL' WHERE name = 'Merengada 3P con Splenda sabor a fresa';
UPDATE products SET brand = 'Pan' WHERE name = 'BEB TERRAEPANE AVENA S/GLUTEN 1 LT';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento nutricional Nutradition Ninos Soya Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te Nature Verde Sin Azucar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema untable libre de gluten sabor chocoavellana de cacao organico Sugar Krush';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola de Coco Fitness Delta';
UPDATE products SET brand = 'SPL' WHERE name = 'Edulcorante Splenda X 25';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento nutricional Nutradition Nino Choco Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento nutricional Nutradition Nino Soya Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Digestal';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lidocaina Farmacaina Pomada 5% x 35 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Salsa BBQ Servivita';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pastilla Perdida de Grasa FIT9 Sascha Fitness 120';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aminoacidos BCAA + Glutamina Sascha Fitness Piñacolada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aminoacidos BCAA + Glutamina Sascha Fitness Magococo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Sascha Fitness Isolatada Hydrolizada Sin Sabor x 907 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Sascha Fitness Isolatada Hydrolizada Mantequilla de Mani';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Sascha Fitness Isolatada Hydrolizada Coco';
UPDATE products SET brand = 'Behrens' WHERE name = 'furosemida edemid 20mg/2ml 5ampolla behrens';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de granola sin azucar de almendras Avelina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de granola sin azucar Fre/cere/aran Avelina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein 2 Fit sabor a fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'EDUL DAILY SUCRALOSA 180 ML';
UPDATE products SET brand = 'Unknown' WHERE name = 'EDUL DAILY STEVIA 180 ML';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorate de Stevia Endolce 300 tab';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorate de Sucralosa Endolce 300 tab';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gotas Farmatodo De Azahares 30Cc';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Furoato de Mometasona 0,05% Cortynase Oftalmi Suspensión Nasal x 80 Dosis';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Citrato Potasio Frambuesa 10.8% 500Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Citrato Potasio 10.8% 500Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Citrato Potasio 10% 500Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Citrato Potasio Frambuesa 10% 500Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Champu Farmatodo Reparador';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Cofastane Polietilenglicol + Propilenglicol 0.4%/0.3% Cofasa';
UPDATE products SET brand = 'Unknown' WHERE name = 'FLORES DE BACH CLEMATIS - CHESNUT BUD';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Agua';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Agua Farmatodo De Rosas 120Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cebada granos';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Kit Farmatodo Jabon Facial Aloe';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Kit Formula Farmatodo 3 Mini Serum Niacinamida Cejas y Cont Ojos 10 ML';
UPDATE products SET brand = 'Unknown' WHERE name = 'FLORES DE BACH ASPEN MIMULUS';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Tintura Farmatodo De Arnica 30Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gotas Farmatodo Valeriana 30Cc';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Crema Farmatodo Antipanalitis';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Farmatodo Glicerinado 120Cc';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gel Farmatodo Aloe Vera';
UPDATE products SET brand = 'Unknown' WHERE name = 'jeringa ecomed 20cc 21x1';
UPDATE products SET brand = 'Unknown' WHERE name = 'jeringa ecomed 10cc 21 x 1';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Agua Farmatodo Alibour';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Solución Hiposulfito De Sodio 40% x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Solución Hiposulfito De Sodio 20% x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'jeringa ecomed 5cc 21x1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jeringa Ecomed 3 mL 21Gx1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina';
UPDATE products SET brand = 'Bayer' WHERE name = 'Valerato de Estradiol + Dienogest Qlaira Bayer';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Bucal Galactic Kids Tutifruti Niño';
UPDATE products SET brand = 'Unknown' WHERE name = 'Extracto Hedera Hélix';
UPDATE products SET brand = 'Mallen' WHERE name = 'Mometasona Furoato 50 mcg Nalosar Mallen Spray x 150 Dosis';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levodropropizina Antux 0,6% Solución Oral X 180 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol 40 mg x14';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Mometasona 50 mcg Cortynase Oftalmi Suspensión Nasal x 140 Dosis';
UPDATE products SET brand = 'Unknown' WHERE name = 'Enalapril';
UPDATE products SET brand = 'Calox' WHERE name = 'Escitalopram 10 mg Calox';
UPDATE products SET brand = 'La Santé' WHERE name = 'Esomeprazol 40 mg Esoz Pharmetique Labs';
UPDATE products SET brand = 'Leti' WHERE name = 'Enalapril Maleato 20 mg Genven';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Polietilenglicol + Propilenglicol 0,4%-0,3% Systane Ultra Alcon Solución Oftálmica Frasco x 10 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Esomeprazol 40 mg Ulgarin Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Empaglu';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Likacin 5%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketorolaco Trometamina 30 mg Notolac';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketoprofeno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sildenafil';
UPDATE products SET brand = 'Valmor' WHERE name = 'Sildenafil 50 mg Duroval Valmor';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Prednisolona Acetato 1% Ocupred Oftalmi Suspensión Oftálmica x 5 ml';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Sildenafil 100 mg Sildex PlusAndex';
UPDATE products SET brand = 'Elmor' WHERE name = 'Lactobacillus Rhamnosus 1,5g Liolactil Elmor Polvo Para Suspensión Oral x 6';
UPDATE products SET brand = 'Vargas' WHERE name = 'Ketoconazol 20 mg Ketazol Vargas Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levosulíride 25 mg Disulpec Mck Pharmaceutical';
UPDATE products SET brand = 'Farma' WHERE name = 'Loperamida Clorhidrato 2 mg  Antilax Laboratorios Farma';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Terbinafina 1% Perten Siegfried Solución Atomizadora x 30 ml';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Topiramato 50 mg Topitolep FC Pharma';
UPDATE products SET brand = 'Leti' WHERE name = 'Tibolona 2,5 mg Fomene Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Algobap rollo';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Loratadina 10 mg Medigen Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina + Pseudoefedrina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Acido Clavulánico';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Amlodipina 5 mg Lodipin Megalabs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Furosemida 40 mg PlusAndex';
UPDATE products SET brand = 'Vincenti' WHERE name = 'Simeticona 125 mg Flatvin Vincenti x 20 Cápsulas Blandas';
UPDATE products SET brand = 'Leti' WHERE name = 'Clindamicina 300 mg Genven';
UPDATE products SET brand = 'Dollder' WHERE name = 'Cinnarizina 75 mg Cinaren Dollder';
UPDATE products SET brand = 'SNC Pharma' WHERE name = 'Pramipexol 1 mg Mipax SNC Pharma';
UPDATE products SET brand = 'La Santé' WHERE name = 'Ciprofibrato 100 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bifosfato Sódico + Fosfato Sódico Flex Enema';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromhexina Bisolvon Linctus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dexametasona';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Dorzolamida + Timolol 2%/0,5% Dobet Oftalmi Solución Oftálmica x 5 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Secnidazol';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Dextran70 0,1% Lacridos Oftalmi Lagrimas Artificiales x 15 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Valsartán 160 mg Genven';
UPDATE products SET brand = 'La Santé' WHERE name = 'Metronidazol 500 mg La Santé x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Tobramicina + Dexametasona 0,3%-0,1% Todex Oftalmi Suspensión Oftálmica x 5 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Enalapril 10 mg Genven';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Tobramicina + Dexametasona 0,3/0,1% Todex Oftalmi Ungüento Oftálmico x 7,5 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tamsulosina + Dutasteride 0,4mg/0,5mg Sulixtra Duo FC Laboratorios';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Moxifloxacina + Dexametasona 0,50%/0,10% Moxidex Oftalmi Solución Oftálmica x 5 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Slinda Drospirenona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carnisin Solución Sin  Azúcar  X 180 Ml';
UPDATE products SET brand = 'Rowe' WHERE name = 'Carvedilol 25 mg Curpinol Rowe';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Tiocolchicosido 4 mg Eusilen Cofasa';
UPDATE products SET brand = 'Calox' WHERE name = 'Clobetasol Propionato 0.05% Calox Crema Tubo x 20 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carboximetilcisteina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Hioscina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nistat 100.000 UI 24Comp Nistatina Cevallos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Novasil 0.1%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metrotrexato Prismatrex 2.5 mg Blister 10';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Mupirocin 2% Muproban Siegfried Ungüento x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Netunal';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Nafazolina 1,00mg NAS Oftalmi Gotas Nasales x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetron';