UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfato Monosodico + Disodico Fosfodual';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jengimiel Limon Jarabe x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antiacido Aplacal Mandarina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetilcisteina Cisteil';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcanfor+Mentol+Eucalipto Mentorub Tarro';
UPDATE products SET brand = 'Genfar' WHERE name = 'Clobetasol Propionato 0,05% Genfar Crema x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Freegells Cough Drops Fresa 30und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jengimiel Kids Jarabe Pediátrico x 120 ml';
UPDATE products SET brand = 'La Santé' WHERE name = 'Esomeprazol 20 mg Esoz Pharmetique Labs';
UPDATE products SET brand = 'K6' WHERE name = 'Cuerda Para Saltar K6 Apolo IV Ajustable Color Rojo';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Complejo B Miovit Cofasa Jarabe Sin Azúcar x 180 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carbonato De Calcio Aplacal Antiacido Menta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Corrector De Postura Kx';
UPDATE products SET brand = 'Unknown' WHERE name = 'Propinox + Lisina';
UPDATE products SET brand = 'Remeny' WHERE name = 'Ibuprofeno 600 mg Remeny';
UPDATE products SET brand = 'Unknown' WHERE name = 'Linazan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suero Hidratante Electro-C Vitamina C Zinc y Probioticos 6';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D3 Derovit 1000U.I. Pack 15+15';
UPDATE products SET brand = 'Unknown' WHERE name = 'Resveratrol NAD + VID';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vita Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mylanta Extra Carbonato De Calcio + Hidróxido De Magnesio + Famotidina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol 40 mg Medigen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esporas de Bacillus Clausii Clasi Bac 2bn/5ml 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Candesartan 8 mg 30';
UPDATE products SET brand = 'Leti' WHERE name = 'Nitazoxanida 100 mg Zontricon Leti Suspensión Oral Pediátrica x 30 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Zinc 50 mg Now Frasco x 100';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cloruro de Sodio + Dextrosa Solumar 60 ml D''Empaire Dlab Frasco x 60 ml Solución';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bencidamina Azutan Colutorio 180 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Agua Oxigenada Farmatodo 500Cc';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Acetaminofén + Clorfeniramina Angrip Noche 500/3mg x 4';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Leukoplast Estandar Color Piel Redondas 100 Und';
UPDATE products SET brand = 'Biotech' WHERE name = 'Betametasona 4 mg Betagen Biotech Solución Inyectable x 1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada sin azucar Conuco sabor a Guayaba';
UPDATE products SET brand = 'Unknown' WHERE name = 'Candesartan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bomba Portatil de Bicicleta P110';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno Brugesic Forte';
UPDATE products SET brand = 'Leti' WHERE name = 'Sitagliptina 50 mg Sitaglis Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Infusion Moringa Ginger Saneta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jugo Alberry Manzana 380 Ml';
UPDATE products SET brand = 'ASK' WHERE name = 'Soporte de tobillo ASK talla L/XL';
UPDATE products SET brand = 'Kimiceg' WHERE name = 'Clotrimazol 10% Kimiceg Crema Vaginal x';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fluticasona Propionato 6 ml Fluticort Cassara Spray Nasal x 60 Dosis';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico Drink Mix Aloe Vera';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Universal Forma elastica talla L';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla De Baño Con Respaldar y Reposabrazos Dovant x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno 200 mg Brugesic Forte Suspensión x';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Diclofenac Potásico Diclodex PlusAndex 50 mg';
UPDATE products SET brand = 'Calox' WHERE name = 'Ibuprofeno 600 mg Calox';
UPDATE products SET brand = 'La Santé' WHERE name = 'Lagrimas Artificiales 0,3% Lagrioftol Pharmetique Labs Solución Oftálmica Frasco x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gastriboleno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bisoprolol 5 mg Antaar MCK Pharmaceutical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetron';
UPDATE products SET brand = 'Unknown' WHERE name = 'Soluhex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carboximetilcisteína';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Farmatodo Thimerosal 60 ML';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mancuerna 9 LB Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola de papelon y coco Delta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gelatina Yoya Sabor A Naranja Cero Calorias';
UPDATE products SET brand = 'Biotech' WHERE name = 'Candesartán 8 mg Biotech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gestasyn II';
UPDATE products SET brand = 'Unknown' WHERE name = 'Piracetam 800 mg Breinox Farma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Linazeite 1000 Mg X 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitomit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Guardian Galon';
UPDATE products SET brand = 'Ebben' WHERE name = 'Gasa Estandar 60Cm 4Pliegos Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Probioticos 5 Billones CFUS Complemento Alimenticio Ziel Pharma Frasco x 60 Gomitas';
UPDATE products SET brand = 'La Santé' WHERE name = 'Clotrimazol + Neomicina + Dexametasona 1,0%/0,5%/0,04% La Santé Crema x 20 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Cefadroxilo 500 mg Genven';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Tiocolchicosido 4 mg Eusilen Cofasa';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Brimonidina Alfadyn 0,2% Solución Oftálmica X 5 Ml';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 1% Imazol Siegfried Crema Vaginal x 50 gr + 6 Cánulas';
UPDATE products SET brand = 'Genfar' WHERE name = 'Metformina 850 mg Genfar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Refluxyl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lacplus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vit C';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Fugolin 1% Spray';
UPDATE products SET brand = 'Unknown' WHERE name = 'Totumo Plus';
UPDATE products SET brand = 'SPL' WHERE name = 'Merengada 3P con esplenda sabor a vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colagened Plus';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pastillas Perdida de Grasa Fat Burner Triple Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Cafeina + Clorfeniramina Dayflu Dia X 5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Degastrol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levodopa + Carbidopa Pf 250/25Mg Psicofarma';
UPDATE products SET brand = 'Ronava' WHERE name = 'Polietilenglicol 3350 8,5g Milax Ronava';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Val' WHERE name = 'Acetaminofen + Tramadol Traceval 325/37,5 Mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Losartán Potásico + Hidroclorotiazida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Tranexámico';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina 2,5Mg/5Ml Jarabe';
UPDATE products SET brand = 'Elmor' WHERE name = 'Ibuprofeno 200 mg Brugesic Elmor';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida + Vitamina B6 Clodoxin 1-10 Mg/Ml Gotas X 30 Ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Carbamazepina 200 mg Aless Pharmaceuticals';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Moxifloxacina 0,50% Quinomax Oftalmi Solución Oftálmica x 5 ml';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Micropore 43862 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Corrector Postura Premium Talla S-M x1 Unidad Pura+';
UPDATE products SET brand = '3M' WHERE name = 'Florina 0,15mg-0,03mg 21tabletas Levonorgestrel-Etinilestradiol Drotafarma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bencidamina Clorhidrato + Cloruro de Cetilpiridinio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Saludable Sin gluten Papas El Valle sabor Aceituna Negra';
UPDATE products SET brand = 'Unknown' WHERE name = 'Epigalocatequina Galato 150 mg Extracto de Té Verde Tecaps x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiras de Cierre Heridas PharmaStrip Fabric 4x76 16 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antiacido Aplacal Mandarina';
UPDATE products SET brand = 'La Santé' WHERE name = 'Sultamicilina 750 mg Sulamp Pharmetique Labs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Budesonida + Formoterol 200 mcg/6 mcg Budeplus';
UPDATE products SET brand = 'Leti' WHERE name = 'Acetaminofén 180 mg/5 ml Genven Solución Oral x 120 ml';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Complejo B Miovit Cofasa Jarabe Sin Azúcar x 90 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Polietilenglicol 3350 8,5 g DAC-Lax Polvo Para Suspensión Oral';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ranitidina';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina + Montelukast';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Cognivit Natur Life''s';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Multivitaminico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sódica 25 mcg Tiroxin Siegfried';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lidocaína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Klincosal Bismuto Subcarbonato + Carbonato De Calcio';
UPDATE products SET brand = '3M' WHERE name = 'Levonorgestrel + Etinilestradol 0,15mg/0,03mg Linofeme Cifarma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Atorvastatina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol Hexant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina-Pseudoefedrina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glibenclamida';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Glicinato De Magnesio 500 mg Natural Systems x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina + Betametasona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Semaglutida 0.25 mg Orsema Incepta x 1 Jeringa Prellenada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sampling Procilus D2 Bionutrec Sobre x 1 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citicolina 500 mg Unicolina Unipharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B Compositum';
UPDATE products SET brand = 'Europharm' WHERE name = 'Gel Cicatrizante Hydromed Eurofarm x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Infusion Sabores Surt Saneta';
UPDATE products SET brand = 'Pan' WHERE name = 'Med Jobst Desc.panty Beige M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Saw Palmetto';
UPDATE products SET brand = 'Val' WHERE name = 'Omega 3 Aceite De Pescado 1000 mg VAL x 60 Cápsulas';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Amoxicilina 750 mg/5ml Amoxiduo Megalabs Suspensión Oral Pediátrica x 70 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Rarivit Inmuno';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Blister Multivitamínico 10tabletas Natural Systems';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tapones de Oidos 2pares Protechs';
UPDATE products SET brand = 'Nutritek' WHERE name = 'L-Glutamine Evolution 120capsulas Nutritek';
UPDATE products SET brand = 'Nutritek' WHERE name = 'Creatine Evolution 120capsulas Nutritek';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche De Coco En Polvo Kaldini x 300 gr';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento Alimenticio Enterex Total Polvo sabor a Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelo Sin Azucar Eucalipto con Vitamina C 12 Unidades Damel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tamsulosina 0.4 mg Tamsulon Tecnofarma';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clindamicina + Clotrimazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Multivitamnico Estrogvit Naturlifes';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colacell';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio + Citrato de Potasio';
UPDATE products SET brand = 'Valmor' WHERE name = 'Tadalafilo 5 mg Tadafox Valmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ceftazidima';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nanbolic-PH';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Hidrocortisona 100 mg Aless Pharmaceuticals';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Ipratropio + Fenoterol 0,25mg-0,5mg/ml Duovent Oftalmi Solución Inhalatoria x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clindamicina 300 mg Nio x 10 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Givotan';
UPDATE products SET brand = 'Val' WHERE name = 'Complejo B Vitisival Jarabe 240 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mousse Antibacterial Humectante Claress';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Steritex Motas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ortoban Yeso 6" X 3YDS  1Rollo 15 cm x 2,7 M';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Biotin 5000 mcg Natural Systems Frasco x 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Resveratrol + Selenio Q10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fomentera Electrica Therma + Luxe Heating Pad Extragrande Conair';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Enterex' WHERE name = 'Suplemento Alimenticio Enterex Renal Vainilla Tetrapak';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Oro Sin Gluten Tornillo';
UPDATE products SET brand = 'CureBand' WHERE name = 'Esparadrapo Tela CureBand 2,5cmX4,50m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Simeticona';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Arte Medico' WHERE name = 'Ácido Fólico 500 mcg Foligum Arte Médico Frasco x 30 Gomitas';
UPDATE products SET brand = 'JHC' WHERE name = 'Sutura Nylon 2.0 Aguja Recta 75Cm Jhc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida + Vitamina B6 Clodoxin 10/100Mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Simeticona';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitisival';
UPDATE products SET brand = 'Polinac' WHERE name = 'Centella Asiática 2% Madecassol Polinac Polvo x 10 gr';
UPDATE products SET brand = 'Nutritek' WHERE name = 'Bcaa Evolution 120capsulas Nutritek';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Septilin Himalaya 100Tabletas Natural L';
UPDATE products SET brand = 'Nutritek' WHERE name = 'Fit and Slim Evolution Coco 904.5g Nutritek';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Antiembolica Autoreggente Talla Xl Color Blanco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sitagliptina + Metformina';
UPDATE products SET brand = 'SNC Pharma' WHERE name = 'Citalopram 20 mg Trolam SNC Pharma';
UPDATE products SET brand = 'Dollder' WHERE name = 'Diclofenac Sódico 75 mg Udox Dollder';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cefadroxilo';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'FARMATODO THIMEROSAL INCOLORO 60 ML';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Vit E 400 Ui 60capsulas Natural System';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cúrcuma Jengimiel Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol 40 mg Corpo Meca Frasco Polvo Solución Inyectable x 1 Vial  I.V.';
UPDATE products SET brand = 'Unknown' WHERE name = 'Broncoral ped jarabe';
UPDATE products SET brand = 'Klinos' WHERE name = 'Ácido Fólico 10 mg Klinos x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Exforge';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Naranja K6 Talla XL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ginseng-Guarana Mg 60capsulas Pharmamerican';
UPDATE products SET brand = 'Leti' WHERE name = 'Cetirizina 10 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Alimenticio Ducray Anacaps';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema De Avena Con Leche Descremada Lumalac';
UPDATE products SET brand = 'Unknown' WHERE name = 'Obleas de Amaranto Capuchino Sin Azúcar Sin Gluten Halo';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Tiocolchicosido 4 mg Eusilen Cofasa';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Antiseptico Farmatodo';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina';
UPDATE products SET brand = 'Enterex' WHERE name = 'Suplemento Alimenticio Enterex Total Polvo Sabor Fresa';
UPDATE products SET brand = 'Leti' WHERE name = 'Atenolol 50 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Enoxaparina Clenox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Florastor Uq 12cápsulas Lactobacillus Acidophilus Hospitalaria';
UPDATE products SET brand = 'Leti' WHERE name = 'Ginseng 100 mg Pharmorat Forte Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valaciclovir 500 mg ADN Medical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vastrón Ácido Valproico 500 mg Cleo x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartan';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Centella Asiática 500 mg Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hesperidina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glicerina 2,88 g Genérico de Calidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Ultimate';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dextrometorfano';
UPDATE products SET brand = 'Unknown' WHERE name = 'Distrosleep';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidrocortisona 500 mg Pharmacheck Polvo Liofilizado x 1 Vial';
UPDATE products SET brand = 'La Santé' WHERE name = 'Hidroclorotiazida 12,5mg La Santé';
UPDATE products SET brand = 'Leti' WHERE name = 'Tadalafilo 5 mg Genven';
UPDATE products SET brand = 'La Santé' WHERE name = 'Losartán 50 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno Con Vitamina C 500 mg Natural Premium';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Pilex Himalaya 100tabletas Natural L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cepillo Solucion Clorhexidina Al 0,04';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jabon Liquido Bactericida Somedine 120 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pinaverio + Simeticona Brosidual';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina';
UPDATE products SET brand = 'Biotech' WHERE name = 'Betametasona 1 ml Betagen Solspen Biotech';
UPDATE products SET brand = 'La Santé' WHERE name = 'Fexofenadina Clorhidrato 120 mg Allerfex Pharmetique Labs';
UPDATE products SET brand = 'Nordic Vision' WHERE name = 'Lente Lectura Nordic Vision Helsinborg +1.5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pregabalina';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Multivitaminico Gomitas para niños 60 Unidades Natural Systems';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Coco Organico Virgen Kaldini 500 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante de Sacarosa con Stevia Montalbán Bolsa x';
UPDATE products SET brand = 'Unknown' WHERE name = 'ADHESIVO GIDAGUS BLANCO 5 X 5';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Colágeno + Vitamina C 650 mg Naturlife''s Frasco x 50 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica 10Cm';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Creatina Atp Naturlife''s';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cassia Angustifolia 125 mg Ciruelax Forte Garden House';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vit E 60capsulas Cristomedical';
UPDATE products SET brand = 'Pan' WHERE name = 'Stamyl Forte 10tabletas Pancreatina - Simeticona Lab Farma';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina';
UPDATE products SET brand = 'Leti' WHERE name = 'Complejo B Neuromix Leti Solución Inyectable 3 ml x 3';
UPDATE products SET brand = 'Kimiceg' WHERE name = 'Clotrimazol 1% Kimiceg Crema x 50 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valproato de Sodio Seizur';
UPDATE products SET brand = 'Unknown' WHERE name = 'Duloxetina 30 mg Cleopharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartan Medoxomilo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sábila + Linaza';
UPDATE products SET brand = 'Vincenti' WHERE name = 'Bencidamina + Lidocaína 0,15%/0,15% Gencivol Vincenti Solución Tópica x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bebida de Almendras UHT Natulac Sin Azucar 946 ML';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Tela 2.54cm x 4.57m 1 Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodón Algobap 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Macarroni Nnova Rice';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante En Polvo Equal Stevia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Longevity 60tabletas Cristomedical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio + Aluminio Biofarco Neutrox Antiácido Biofarco Frasco x 240 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Agua Oxigenada Guardian';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aciclovir 5% SGG Tubo x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nasin ped gotas';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Imazol Solución 1% X 20 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodón Rollo Algobap';
UPDATE products SET brand = 'La Santé' WHERE name = 'Terbinafina Clorhidrato 1% Fungex Pharmetique Labs Crema x 15 gr';
UPDATE products SET brand = 'Laproff' WHERE name = 'Naproxeno 500 mg Laproff Blíster x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glicerina 1,03g Uso Pediátrico OFA x 6 Supositorios';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loperamida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfato Ácido de Sodio Nemax Adulto Enema x 133 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lamotrigina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omega 3-6-9 Longevity 1000 Mg 60 Cap Cristomedical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Guardian';
UPDATE products SET brand = 'Nutritek' WHERE name = 'Fat Burner Noct Evolution 60capsulas Melatonina Nutritek';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Centella Asiática 300 mg Centellasan Arcoiris Frasco x 90 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levonorgestrel 1.5 mg Overol';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol+Gentamicina+Betametasona Crema';
UPDATE products SET brand = 'Unknown' WHERE name = 'Plidan Compuesto';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmunoforte';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Desonida 0,05% Siegfried Tubo x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rabano Yodado';
UPDATE products SET brand = 'Biohlab' WHERE name = 'Sistema Aerochamber Flow-Vu + Mascara Pediátrica (0-5 Años) Biohlab';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Colageno Hidrolizado Vit E-C 60tabletas Pharmatech';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lactovac Lactobacillus Acidophilus Suspensión Pediátrica x 12 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Inositol 500 mg Now Frasco x 100 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diecaps';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Candesartán 8 mg Coropres Megalabs';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lecitina De Soya Lecithin';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 500 mg Aless Pharmaceuticals';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Vitamina C 1000 mg CloraC Cofasa Frasco x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Urea 10% Brucen Frasco x 400 ml Crema Corporal Extrahidratación (Psoriasis)';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sustaplus Energy Gammafood';
UPDATE products SET brand = 'Unknown' WHERE name = 'Wampole Tutti Frutti Aceite de Hígado de Bacalao + Vitaminas del Complejo B Emulsión x 200 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Macarroni con Salsa Queso Cheddar Nnova Rice';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitadyn C';
UPDATE products SET brand = 'Polinac' WHERE name = 'Sal Efervescente Disfruta Limón Polinac Maver x 5';
UPDATE products SET brand = 'Unknown' WHERE name = 'ADHESIVO GIDAGUS BLANCO 1.25 X 5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Med Comprinet Muslo Sz 3 T/m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mirtazapina';
UPDATE products SET brand = 'Dollder' WHERE name = 'Amiodarona 200 mg Novarona Dollder';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Andantol';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Antiseptico Farmatodo Spray';
UPDATE products SET brand = 'La Santé' WHERE name = 'Olmesartán Medoxomil 20 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clobetazol 0,05% Dermazol Medihealth Crema Tópica x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loción Capilar Desonida Dermosupril 0.1% Medihealth 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Potasio Aminoácido Quelado 495 mg Vitamina Farmatodo Frasco x 30';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol-Dexametasona-Neomicina  1%-0,4%-0,57%';
UPDATE products SET brand = 'Now' WHERE name = 'Probiotico 2 Billones Vayas Dophilus Now x 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitalmax';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Especializado Calaminol Picaliv Para Picadura x 16 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'ColostruDerm';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Negro +1.5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Urea 12% Brucen Syndet Frasco x 250 ml Gel Limpiador Corporal (Psoriasis)';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Kimiceg' WHERE name = 'Famotidina 40 mg Kimiceg';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Drospirenona + Etinilestradiol';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Flixotide 250mcg 60 Dosis Susp P/Inha Propionato de Fluticasona Gsk';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zabila C/Miel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Klas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico';
UPDATE products SET brand = 'Leti' WHERE name = 'Bisoprolol Fumarato 2,5 mg Genven x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina A 10.000 UI Preventud Plus Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Tiares' WHERE name = 'Depofem Medroxiprogesterona Acetato 150 mg Tiares Solución Inyectable 1 Vial x 1 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Apixaban 2,5 mg MT Global Care';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Maca 500 mg Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cristal De Sábila Barunu 99% X 170 G';
UPDATE products SET brand = 'Farma' WHERE name = 'Citrato de Magnesio 622,28 mg Magalex Laboratorios Farma x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gentamicina';
UPDATE products SET brand = 'La Santé' WHERE name = 'Glimepiride 4 mg La Santé x 30';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Mometasona Furoato 0,1% Resequil Oftalmi Loción Tópica x 10 ml';
UPDATE products SET brand = 'Val' WHERE name = 'Biotina 5000 mcg Val Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Ácido Hialurónico + Colágeno + Biotin Natural Systems x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Vera 30';
UPDATE products SET brand = 'Kimiceg' WHERE name = 'Clotrimazol 1% Kimiceg Tubo x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tubo Interno de Neumatico 26 R130 Schrader';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetron';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bacillus Clausii Baciclasi Suspension Oral Sanzyme';
UPDATE products SET brand = 'Unknown' WHERE name = 'GlutaDose Guard 6viales';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sulfadiazina de Plata 1% Argenzil Avpharma Crema x 50 g';
UPDATE products SET brand = 'Ronava' WHERE name = 'Ronavit Complejo Vitamina B Ronava';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesio Aminoquelado';
UPDATE products SET brand = 'Unknown' WHERE name = 'Z20';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Clásicas Briutcare x 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Vita Cell Premium X 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina B2';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Colágeno Hidrolizado + Vitamina E y C Pharmatech x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Sensitive Kids De 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vendas Adhesivas Infantiles Cure Aid 20 Unidades';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Gasex Himalaya 100Tabletas Natural L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno + Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Kaymed 3x3 cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Micro Herramientas Plegable Ciclismo T160';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin Gluten Choco Balls Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Laxante Hierbas Naturales Colon Clean Pro-Salud';
UPDATE products SET brand = 'Elmor' WHERE name = 'Cefadroxilo 500 mg Cefonax Elmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vaso Mezclador Pro Sport Surtidos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mesalazina 500 mg Kmplus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Surtidas Sensitive Cure Aid Pharmalast 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio + Vitamina D';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bacitracina 500UI';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glutathione + Vitamina C + Zinc Glutadose';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidralit Bebida Hidroelectrolitica 500 ml Sabor Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diuret 80';
UPDATE products SET brand = 'Dixson' WHERE name = 'Cuerda de saltar Dixson';
UPDATE products SET brand = 'Unknown' WHERE name = 'Triball Ejercitador Respiratorio x 1 Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartán Medoximil + Amlodipina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acido Ascorbico Vit C Vitrexon';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fibra Natural Metamucil Sabor Naranja x 174 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Climasoy';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Liq Powerful';
UPDATE products SET brand = 'Unknown' WHERE name = 'Agua Oxigenada Guardian';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clindamicina + Ketoconazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Desonida 0,1% Dermosupril Medihealth Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato Digifal';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol + Amoxicilina + Claritromicina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfato Monobasico de Sodio + Fosfato Dibasico de Sodio Lit Enema';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Hialuronato de Sodio 0,4% Hyalo Comfort Vitaline Solución Oftálmica x 10 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina';
UPDATE products SET brand = '3M' WHERE name = 'Dienogest + Etinilestradiol 2,0mg/0,03mg Florence Urufarma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Moringa Graviola 60Capsulas Natural Premium';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Transpore 1 und';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Linaza Herbaplant 500 Mg X 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina';
UPDATE products SET brand = '3M' WHERE name = 'Levonorgestrel + Etinilestradiol Ovorest 0,15mg/0,03mg Capsuven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diecaps';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Tegaderm + Pad 5x7cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Prostanat Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Natural Aloe Vera';
UPDATE products SET brand = 'La Santé' WHERE name = 'Amlodipina 10 mg La Santé';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Diamet 90Capsulas Arcoiris';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Benefic Uomo Talla 4 Color Negro';
UPDATE products SET brand = 'Unknown' WHERE name = 'UrinVita Complemento Alimenticio 60 Cápsulas Vitae';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cristal Sabila Barunu C/Glicerina Gel X170G';
UPDATE products SET brand = 'La Santé' WHERE name = 'Diclofenac Potásico 100 mg Klafenac R Pharmetique Labs x 10';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Chromium Picolinate 200mcg 100tabletas Natural System';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio CalmTu Vitae';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio-Vitamina D Kids';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Drenaqua Cumlaude Lab';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Fat Burner Natural Systems X 60 Cápsulas';
UPDATE products SET brand = 'Vick' WHERE name = 'Guaifenesina + Dextrometorfano Jarabe De Tos Vick 44';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiochax Tiocolchicosido';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento Alimenticio Enterex DBT Vainilla Libre de Gluten Botella';
UPDATE products SET brand = 'Farma' WHERE name = 'Teragrip Supra Acetaminofén + Clorfeniramina + Pseudoefedrina 650/30mg Farma x 10';
UPDATE products SET brand = 'Calox' WHERE name = 'Tadalafilo 20 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diclofenac Sódico Lofnac';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Real Kids Sabor Fruta';
UPDATE products SET brand = 'Genia Care' WHERE name = 'Multivitaminico Nutragum Kids Vit C + Zinc Fresa Bolsa 90Und Multivitaminico Genia Care';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Forma Elastica Para Hombro Femenino Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Forma Elastica Para Hombro Masculino Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiamina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pelotas De Tenis Wilson Ao 4 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador sorporte para el pulgar Actimove Rhizo Forte';
UPDATE products SET brand = 'Now' WHERE name = 'Candida Support 90capsulas Now';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Benefic Uomo Talla 5 Color Negro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Benefic Uomo Talla 3 Color Negro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Arasens 2%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Viter C';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Dequalinio + Lidocaina 0,25mg/5mg Benzodiazol Tutti-Frutti Siegfried';
UPDATE products SET brand = 'Unknown' WHERE name = 'Plusargin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel Magic Honey Sobre x 1 unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acemuk 600 mg x 10';
UPDATE products SET brand = 'Dollder' WHERE name = 'Quetiapina 25 mg Dropil Dollder';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nexcare Micropore 1/2X9,14M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Probiótico Complemento Alimenticio Sin Gluten Giniwa U';
UPDATE products SET brand = 'Unknown' WHERE name = 'Biotina y Colágeno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calostro de Bovino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulsil Sucralosa Edulcorante Liquido';
UPDATE products SET brand = 'Unknown' WHERE name = 'Iced Tea A Base De Matcha Ochamatcha';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Cal-Mag-Zinc + D 60tabletas Natural System';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio 2fit Advanced Amino Energy 100cápsulas';
UPDATE products SET brand = 'Calox' WHERE name = 'Tadalafilo 20 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Labioderm 5%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B Forte Kronos Solución Inyectable I.M- I.V. x 10 ml';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Omega 369 1000 mg Natural System Frasco x 100 Cápsulas Blandas';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-carnitine';
UPDATE products SET brand = 'Unknown' WHERE name = 'Biotína + Calcio + Zinc 2100mcg/120mg/10mg Biotina Complex Naturistik Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Ebben' WHERE name = 'Venda Economic 10Cm Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack De Maiz Y Arandanos';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Andadera Reciprocal Dovant x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra De Proteina Nugo Brownie';
UPDATE products SET brand = 'Val' WHERE name = 'Magnesio Para Niños Happy Kids Uva VAL x 60';
UPDATE products SET brand = 'Leti' WHERE name = 'Cefixima 400 mg Longacef Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Micropore 3M 2" X10Yd';
UPDATE products SET brand = 'K6' WHERE name = 'Liga de Resistencia K6 9 Kg';
UPDATE products SET brand = 'Farma' WHERE name = 'Clortalidona 12,5 mg Hidroten Laboratorios Farma';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Complejo B Miovit Cofasa Jarabe x 180 ml';
UPDATE products SET brand = 'Calox' WHERE name = 'Tiocolchicosido 4 mg Calox';
UPDATE products SET brand = 'La Santé' WHERE name = 'Tadalafilo 5 mg TalystoR Pharmetique Labs';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Gris Cuadrado +3.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Malla Cutimed Sorbact 7x9cm 1 Sobre';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Nordic Vision' WHERE name = 'Lente Lectura Nordic Vision Helsinborg +2.5';
UPDATE products SET brand = 'Nordic Vision' WHERE name = 'Lente Lectura Nordic Vision Helsinborg +2.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Magnesio';
UPDATE products SET brand = 'Vivax' WHERE name = 'Vitamina E Vivax 400 Ui X 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Multivitamínico Para Dormir The Patch Club Sobre x 6 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dermanutrix colageno Lsi';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glizigen Gel Íntimo Medicado';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hormoskin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multiderm 2%';