UPDATE products SET brand = 'Pan' WHERE name = 'Cifarma Probentol Derma Creme Dexpantenol Crema';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oximetazolina Clorh 0,025% solución nasal';
UPDATE products SET brand = 'Valmor' WHERE name = 'Mirtazapina 15 mg Mirtazaval Valmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetron';
UPDATE products SET brand = 'Nutritek' WHERE name = 'Cla Fit Evolution 90capsulas Nutritek';
UPDATE products SET brand = 'Unknown' WHERE name = 'Buscapina';
UPDATE products SET brand = 'Naturlife' WHERE name = 'hepaclean 50capsulas naturlifes';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tostadas Crujiente Sin Gluten Santiveri Noglut';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina';
UPDATE products SET brand = 'Laproff' WHERE name = 'Espironolactona 25 mg Laproff Blíster x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cofasur';
UPDATE products SET brand = 'Kimiceg' WHERE name = 'Ungüento Dérmico Bacitracina Kimiceg Crema x 15 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Urea 12% Brucen Frasco x 250 ml Crema Corporal Emoliente';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Complejo B Miovit Cofasa x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clopidogrel';
UPDATE products SET brand = 'Nordic Vision' WHERE name = 'Lente Lectura Nordic Vision Helsinborg +3.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol 40 mg Kmplus';
UPDATE products SET brand = 'Sweetest' WHERE name = 'Edulcorante Sweetest Monkfruit Envase Flexible x 200 gr';
UPDATE products SET brand = 'Nordic Vision' WHERE name = 'Lente Lectura Nordic Vision Helsinborg +0.0';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Acetaminofen + Clorfeniramina + Cafeina 650/4/30mg Tempiren Dia FC Pharma x 10 Cápsulas Blandas';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Acetilcisteina 200 mg Acemuk Siegfried x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Beclometasona Beclo-Asma 50mcg Aerosol para Inhalacion Oral 200 dosis';
UPDATE products SET brand = 'Calox' WHERE name = 'Lansoprazol 30 mg Calox';
UPDATE products SET brand = 'Rowe' WHERE name = 'Sulfadiazina de Plata 1% Protosulfil Rowe Crema x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Compresor Nebulizador Dynamex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite De Orégano Natural Premium Gotas x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B + Aminoácidos Lisin-Be';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'PSI Clonazepam';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Dexclorfeniramina Maleato + Cafeina';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Prednisolona 3 mg Pediacort Oftalmi Solución Oral Pediátrica x 60 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorace';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhidrato De Bromexina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Wampole Tutti Frutti Aceite de Hígado de Bacalao + Vitaminas del Complejo B Emulsión x 360 ml';
UPDATE products SET brand = 'Ronava' WHERE name = 'Complejo B12 Inyectable Ronavit Ronava x 3';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio 2fit Cerebral Boost con Ginkgo Biloba 60cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Cafeína + Clorfeniramina';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Clindamicina + Ketoconazol Frondos FC Pharma';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Complejo B Miovit Cofasa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cal-Magnesio-Zinc 60tabletas Cristomedical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para La Energía The Patch Club x 6';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Negro Demi +2.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartán 160 mg Drotafarma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pegyt';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cola de Caballo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Transparente Fijacion Canulas Pharmapore 8,5x11,5 20 Unidades';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Neopreno Kx Ajustable Talla P';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Liq Powerful Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mancuerna Vinyl DX Par 4 LB';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mupirocina 2% FarmageniUngüento x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sulfadiazina De Plata';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Trimebutina Maleato';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Val' WHERE name = 'Vitamina C 500 mg + Zinc + Bioflavonoides + Llisina VAL x 30';
UPDATE products SET brand = 'Farma' WHERE name = 'Acetaminofen + Clorfeniramina Teragrip Gotas 100-0,35mg/ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol Clorhidrato';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farma' WHERE name = 'Acetaminofén + Clorfeniramina Teragrip Forte Noche 500 mg/2 mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caladryl Difenhidramina HCI Calamina Zukati Loción x 100 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Silvederma 1% Sulfadiazina De Plata Medifarm Tubo x 50 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Ácido Clavulánico';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Dequalinio + Lidocaína 0.25/5Mg Benzodiazol Menta Siegfried';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C+Zinc+Vitamina D3 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Kx De Neopreno Ajustable Talla P';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mometasona Furoato 0.1% Elok Crema Liali';
UPDATE products SET brand = 'Vincenti' WHERE name = 'Clotrimazol 1% + Neomicina 0,5% + Betametasona 0,05% Crema tópica Vincenti 20 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mupirocina 2% Muproban Tubo x';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kit Completo de Reparacion T270';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina B6';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chocogranola Yogranola';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante de Sucralosa Dulci Light';
UPDATE products SET brand = 'Unknown' WHERE name = 'Obleas De Amaranto Sabor Frutos Rojos Halo Endulzado Con Estevia x 60 gr';
UPDATE products SET brand = 'Calox' WHERE name = 'Diclofenac Potásico 50 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbul Tioconazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betadex 0,1% Betametasona Dipionato Crema Liali x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Extracto Jengibre + Miel + Berro + Sábila Sabe Miel Jarabe x 180 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oxolamina Broxol Tos Jarabe Ped';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Budesonida 32 mcg Budenas Oftalmi Gotas Nasales x 15 ml';
UPDATE products SET brand = 'Neilmed' WHERE name = 'Sinus Rinse Solución Salina Para Preparar Kit Pediátrico Neilmed x 30';
UPDATE products SET brand = 'Naturlife' WHERE name = 'L-Carnitine 600 Mg Naturlife''s Frasco x 50 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Proplus S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C + Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aquatop Restauradora Intensiva Crema';
UPDATE products SET brand = 'Unknown' WHERE name = 'N-Acetilcisteina Flemaxin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Serenoa Repens Prostaplant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Wampole Naranja Aceite de Hígado de Bacalao + Vitaminas Del Complejo B Emulsión x 360 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante Hermesetas Clasico 1200comprimidos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Semilla de Calabaza + Ortiga';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola Viva+ Frutos Secos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Turmeric';
UPDATE products SET brand = 'Calox' WHERE name = 'Cefixima 400 mg Calox';
UPDATE products SET brand = 'Vincenti' WHERE name = 'Complejo B Novhepar Jarabe  Vincenti 180 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Biotina 10.000mcg 30';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Jarabe Expectorante Beusan Vita Herbal x 240 ml';
UPDATE products SET brand = 'Genia Care' WHERE name = 'Vitamina C Nutragum Kids Vit C Bolsa 25Unidades Genia Care';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Calcio + Vitamina D3';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Especial Jogger';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Prokal L-Carnitina';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Clopidogrel Clopidex Plusandex';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetrón 4 mg H&M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oximetazolina Nafazol Gotas Nasales';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche De Magnesia Sabor Menta Biofarco Frasco x';
UPDATE products SET brand = 'Tiares' WHERE name = 'Levonorgestrel + Etinilestradiol 0,15mg/0,03mg Ciclogynon Tiares';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina  500 Mg/4Mg Clorace';
UPDATE products SET brand = 'La Santé' WHERE name = 'Alcohol Polivinílico 1,4% Alilub Pharmetique Labs Lagrimas Humectantes Solución Oftálmica x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diucor 80';
UPDATE products SET brand = 'La Santé' WHERE name = 'Amlodipina 5 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diclofenac Potásico 1,8mg/ml Clofen Frasco x 120 ml Suspensión Oral';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pelota Para Ejercitar La Mano 50mm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rueda Para Hacer Ejercicios De Rodilla';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Aceite De Pescado Omega 369 1000 mg Natural Systems Frasco x 60 Cápsulas Blandas';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina Coenzima Q10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Maleavit 30 Cap Multivitaminico Exeltis.';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colágeno Hidrolizado Limonada de Fresa Sascha Fitness x 490 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Durazno Deshidratado El Jarillo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dexametasona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cranberry Arándano Rojo + Vitamina C 500 mg Val';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mezcla de Frutas Deshidratadas El Jarillo';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Citrato de Calcio 950 mg Calcitrex D3 Oftalmi x 30';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Ampicilina + Sulbactam 1,0mg/500mg Amtacilyn Aless Pharmaceuticals';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfato Ácido de Sodio 16% Nemax Enema Pediátrico x 66 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Preload Energy Energia y Sistema Inmune Marnys 460 g';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 1% Gynodac Crema Vaginal x 50 gr + 6 Aplicadores';
UPDATE products SET brand = 'Unknown' WHERE name = 'Soporte De Rotula Jogger Talla Unica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Una De Gato 60Capsulas Natural Premium';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cleopharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cuerda De Saltar Bicolor Jogger';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Rinocare 60capsulas Herbaplant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante A Base de Stevia Dulcilina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ademina Dermoprotectora';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Cloruro de Sodio 0,9% IPS x 500 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cilostazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol + Miconazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Piridoxina';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Imazol Polvo 1% X 20 G';
UPDATE products SET brand = 'Calox' WHERE name = 'Gabapentina 300 mg Calox';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Ácido Fusídico 2% Topisept Siegfried Crema Tópica x 15 gr';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Probiótico y Prebiótico Inmubiotic Arco iris Laboratorio Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Vitamina D3 5000IU Natural Systems';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Fugolin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Glicirricínico Glizigen Avpharma x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína Batido Muscle Milk Vainilla x 330 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Acetilsalicílico 81 mg Azacard Vifar';
UPDATE products SET brand = 'Unknown' WHERE name = 'AironDuo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C + Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tubo Interno de Neumatico 26 R130 Presta';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Crema Clotrimazol + Neomicina + Beclometasona 1%/0,5%/0,025% Canison BN Zuoz Tubo x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Vitaminas + Minerales Fórmula Magistral Farmatodo Ultra Vit Men Hombres';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol Flenox';
UPDATE products SET brand = 'ASK' WHERE name = 'Arequipe Sin Azucar Nebraska 230 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Naturlife' WHERE name = 'colocleanse 60capsulas naturlifes';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitamínico 12 vitaminas + 13 Minerales Multivinol FC Laboratorios Frasco x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acivirax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ortoban Compresa 18x18';
UPDATE products SET brand = 'Unknown' WHERE name = 'Toxolen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Compresa Laparatomia Ortoban 18x18 5 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidroxido de Potasio  5% Molutrex Skin Care ACM Frasco x 3 ml';
UPDATE products SET brand = 'Vargas' WHERE name = 'Multivitamínico Henovic Vargas Solución Gotas Pediátricas x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Magnesium 6 Vitae';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Calcio + Magnesio + Zinc + Vitamina D Natural Systems Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema Ultra Hidratante Corporal By Coher URI Body Con UREA al 20% x 200 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Wampole Fresa Aceite de Hígado de Bacalao + Vitaminas del Complejo B Emulsión x 240 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aciclovir 5%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Polietilenglicol 3350 MiraLax Ronamedic Polvo x 120 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Drospirenona-Etinilestradiol';
UPDATE products SET brand = 'Leti' WHERE name = 'Ciproterona + Etinilestradiol 35mcg/2mg Galby Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico 2fit Hair, Skin, Nails Advance Formula 60cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcifor Extra + Vitamina D 30Capsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calendula';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hojas de Moringa Saneta';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Omega 3 6 9 Arcoíris';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Sascha Fitness Isolatada Hydrolizada Cookies and Cream';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betametasona + Gentamicina Betadex G';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada sin azucar Conuco sabor a Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Luteína + Zeaxantina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gentamicina+Betam+Clotr Saimed';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cloruro de Sodio + Cloruro de Potasio 0,6g/0,03g Ringer Lactato JL Pharma Frasco x 500 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Tri Bran Now X 100';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema Aclarante W-2 Farmagenik Ácido Tranexámico + Niacinamida 3%-5% Tubo x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Agua Oxigenada Farmatodo 100Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Beducis Locion';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina E con Selenio 400UI-50mcg 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C Acido Absorbico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio 600 + Vitamina D';
UPDATE products SET brand = 'Val' WHERE name = 'Glicinato de Magnesio 325 mg + Vitamina B6+ Potasio VAL x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio + Vitamina D';
UPDATE products SET brand = 'Nutritek' WHERE name = 'Fit and Slim Vegan Evolution Vainilla 904.5g Nutritek';
UPDATE products SET brand = 'Unknown' WHERE name = 'Desonida 0,05% Dermosupril Medihealth Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diclofenaco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bacitracina 500ui';
UPDATE products SET brand = 'Unknown' WHERE name = 'Protector de colchon All Pro Cunas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Extracto Hedera Helix';
UPDATE products SET brand = 'Elmor' WHERE name = 'Bencidamina + Cetilpiridinio 0,15%/0,25% Flomed Elmor Solución Bucal x 45 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jengimiel Jarabe Miel Adulto x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'SueroMax Vitaminado Rehidratante';
UPDATE products SET brand = 'Unknown' WHERE name = 'Laxante Senosidos A y B+Docusato De Sodio 6,8mg/50mg Senokot Docusato Lab. Farma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venpiel Skinreg apósito 5unidades Sumpco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lavado Bucal Flodont X 180 Ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Remeny' WHERE name = 'Bacitracina 500 ui Remeny Ungüento Tubo x 15 gr';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Neilmed' WHERE name = 'Solución Salina Nasal Sinus Rinse Kit Adulto Neilmed';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'La Santé' WHERE name = 'Dequalinio + Lidocaina Benzodiazol Naranja 16';
UPDATE products SET brand = 'FAHD' WHERE name = 'Memantina 20 mg FAHD';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jengimiel Sábila Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nipe Jarabe  Sin Azucar Acetaminofen + Clorfeniramina + Cafeina x 120 ml';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol Ipalat 1%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Sascha Fitness Isolatada Hydrolizada Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para Dolores Lidocaína 4% Medipatch Talla L 5 Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Infusion Natural Gripdel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica 12Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica 20Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Caramelos Freegells Cough Drops Eucalipto x 30 und';
UPDATE products SET brand = 'ASK' WHERE name = 'Vaso mezclador ASK colores surtidos 800 ml';
UPDATE products SET brand = 'ASK' WHERE name = 'Vaso Infusor Ask Color Surtidos 800 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Therma Gel Intervir Ranita';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Cafeína + Clorfeniramina';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Budesonida 200 mcg Budecort Oftalmi Aerosol para Inhalar x 100 Dosis';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colágeno Hidrolizado Macchiato de Caramelo Sascha Fitness x 507.5 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dextrometorfano';
UPDATE products SET brand = 'Unknown' WHERE name = 'Extracto Seco De Cassia Angustifolia 75 mg Ciruelax Minitabs Garden House x 20';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Colmed' WHERE name = 'Esomeprazol Colmed 40 Mg X 20';
UPDATE products SET brand = 'Unknown' WHERE name = 'Berro Con Cebolla Sabe Miel Jarabe x 180 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromhexina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fenobarbital';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Enema';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Noxpirin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Broxol Grip';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diosmit 6sobres Diosmectita';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiamazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Trimebutina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lisin-Be Alm';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol+Gentamicina+Betametasona Crema';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levosulpiride 25 mg Suride x 30';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Micropore 3M 1" X10Yd';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colchon Antiescara Tipo Latice';
UPDATE products SET brand = 'Unknown' WHERE name = 'Furawise N Unguento para uso Topico Externo Nitrofurazona 0.2% x 30 G';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dextonil';
UPDATE products SET brand = 'Calox' WHERE name = 'Ácido Acetilsalicílico 81 mg Caloxpirina Calox x 100';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jengibre-Miel Jengibre Miel Jarabe 120 Ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calostro 300 mg Sp Colostrum Proyecto Nueva Vida Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Angelus' WHERE name = 'Dapagliflozina 5 mg Glinamed Angelus';
UPDATE products SET brand = 'Calox' WHERE name = 'Bisoprolol Fumarato 2,5 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Hioscina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Polietilenglicol 3350';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche Magnesia Sabor Original Biofarco x 120 ml';
UPDATE products SET brand = 'Biotech' WHERE name = 'Desonida 0,1% Erilon Biotech Crema Tópica x 15 gr';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Ácido Poliacrílico 0,2% Acrylarm Poen Gel Oftálmico x 10 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bencidamina Flodont';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cola De Caballo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Creatina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Wampole Fresa Aceite de Hígado de Bacalao + Vitaminas del Complejo B Emulsión x 200 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Coenzima Q10 150 mg Preventud Plus Tarro x 60 Cápsulas';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Zabila C/Miel 120 Ml Jarabe Ped Fc Pharma Ca';
UPDATE products SET brand = 'Europharm' WHERE name = 'Apósito Adhesivo Euromed Eurofarm 5 x 7 cm';
UPDATE products SET brand = 'Val' WHERE name = 'Vinagre De Sidra De Manzana 500 mg Apple Cider VAL Frasco x 30 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te verde';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio Citrato + Vitamina D3 Calpal D';
UPDATE products SET brand = 'Meyer' WHERE name = 'Dexlansoprazol 30 mg Dexopral x 30 Cápsulas Meyer Productos';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Protección Luz Azul +2.5';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Algodon Farmatodo Motas  100Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Para Niños Zuviss 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codeína + Clorfeniramina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply7 Chips de Quinoa Sabor a Queso Cheddar';
UPDATE products SET brand = 'Vivax' WHERE name = 'Complejo B Carvix Vivax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cristal Sabila Barunu Crema X';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromexina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azitromicina Zitrobio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Nutricell Dermatech 60Tabletas Multivitaminico';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Noxpirin Noche Acetaminofén + Fenilefrina + Clorferinamina Panela Limón';
UPDATE products SET brand = 'Now' WHERE name = 'Citrato De Magnesio 200 mg Now Frasco x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol Flenox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Broxol Flem';
UPDATE products SET brand = 'Neilmed' WHERE name = 'Sinus Rinse Adulto Polvo Solución Salina Neilmed x 50';
UPDATE products SET brand = 'Sanofi' WHERE name = 'Nasacort AQ Spray Atomizados 55mcg  120aplic Triamcinolona Sanofi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Giniwa V Probiótico Via Oral Sin Gluten x 14 Cápsulas';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Loteprednol 0,5% Lotesoft Poen Gotas Oftálmicas x 5 ml';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Desonida 0,1% Siegfried Tubo x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato De Oxolamina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Polietilenglicol 3350 Magic Lax Polvo Chemo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol 10 mg Nexium Astrazeneca Gránulos Para Suspesión Oral';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Ovusitol D Italfarmarco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina K2 100mcg 100';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno Hidrolizado NutraBrain';
UPDATE products SET brand = 'Pan' WHERE name = 'Complejo B D-Pantenol';
UPDATE products SET brand = 'Blue Medical' WHERE name = 'GluActive Blue 30';
UPDATE products SET brand = 'La Santé' WHERE name = 'Solunovar compuesto';
UPDATE products SET brand = 'Unknown' WHERE name = 'Agua de Mar 2,2% Solumar D''Lab Solución Hipertónica Spray x 30 ml';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Vitamina A + Luteína + Zaenxantina + Lutemax 500 mg Clerover Naturlifes x 30 Cápsulas';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Angrip Forte Noche';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betahistina Normon 16 mg Lab. Normon';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromuro De Ipratropio 20 mcg Distrilab Aerosol Para Inhalación Inhalador x 200 Dosis';
UPDATE products SET brand = 'Unknown' WHERE name = 'Agua Oxigenada Guardian';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Pseudofedrina + Clorfeniramina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Montelukast Montrax';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Silkplast 2.5Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Selenio 200ug Vitahelp 120';
UPDATE products SET brand = 'Enterex' WHERE name = 'Enterex Glutapak-10 Glutamina Sobre x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartán 160 mg Distrilab';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetron';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elasticas 15Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina + Cafeina Rinot';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cristal Sabila Barunu C/Glicerina Crm X170G';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Hígado de Bacalao + Vitaminas del Complejo B Wampole Sabor Fresa Frasco x 360 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Toallas Húmedas Antibacterial Befresh 24Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Dioxogen Microcapsulas 220 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'CLA + L-Carnitina + Te Verde 60';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Procare' WHERE name = 'Gasa 3x3 Estéril Procare x 2 und';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Algobap 2"X2" X2Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quinchoncho';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quinchoncho 300 Mg 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Cinta Transparente 5 Cm X 4,5 M';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Glicinato de Magnesio Farmatodo Polvo + Colina + Prebioticos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Microporoso Color Blanca 5 Cmx 10 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C + Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Antiseptica Thimerosal 60 Ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Algodon Farmatodo Desmaquillante Discos 80Unds';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema Fresca Hidratante Calaminol Hidraliv Piel Sensible x 88 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Antiseptico Farmatodo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmov Bsn Brazo S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Alimenticio Vivasse Sabor Natural x 400 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorprofenpiridamina + Cafeina Ascafyl';
UPDATE products SET brand = 'Unknown' WHERE name = 'ADH RELA IMPERMEABLE PRE CORT X 4 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Microporoso Color Beige 10 Cm X 4,5 Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tamsulosina 0,4Mg Biumak';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Antiseptico Santa Teresa 700 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Papel Color Piel Briutcare 2,4Cm X 4,57M 1Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D3 Kids';
UPDATE products SET brand = 'Farma' WHERE name = 'Vitamina D Farma D 2000Ui Laboratorios Farma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omebloc';
UPDATE products SET brand = 'Colmed' WHERE name = 'Orlistat 120 mg Colmed';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Agua Oxigenada Farmatodo 240Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo BSN Activ Kids talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina 3000 14 Carnitin Marnys';
UPDATE products SET brand = 'Unknown' WHERE name = 'Blister Omega 3';
UPDATE products SET brand = 'Unknown' WHERE name = 'Teofilina 100 mg Buka';
UPDATE products SET brand = 'ASK' WHERE name = 'Soporte de palma ASK talla S/mM';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein Isolate Vainilla Dulcilina';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol';
UPDATE products SET brand = 'Klinos' WHERE name = 'Vitamina B12 500mcg 20cápsulas Cianocobalamina Klinos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina B1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Pureza C/Valvula 1 L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfato Monobasico de Sodio+Fosfato Dibasico de Sodio Lit Enema 10,8g-4,5g Uso Pediatrico 67,5ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Meal Replacement';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico Cellu Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico High Energy';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo BSN Activ Kids talla Xs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B Pack 3';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo BSN Kids talla Xxs';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Montelukast 10 mg  + Desloratadina 5 mg Roweluk Ultra Rowe Megalabs x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina Liquida 20Viales11ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multi Vitaminas Kids Ziel Pharma Complemento Alimenticio Frasco x 60 Gomitas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nutrisite Protein Modulo de Aislado del Suero de la Leche Medsite x 275 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Vitaminas A, C,D, E y Zinc Preventud Plus 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dexametasona + Neomicina + Clorfeniramina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Berro';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Agua Oxigenada Farmatodo 950Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tamiflu';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Montelukast + Desloratadina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zopiclona 7.5 mg Overol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina Sinutil Pediatrico Gotas 30 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Con Ferula Forma Elastica Derecha Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'AGUA OXIGENADA ALVE 240 CC';
UPDATE products SET brand = 'Behrens' WHERE name = 'Solución Electrolítica 60meq/l Behrens Rehidrosol Manzana x 600 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collar BSN Cervical Suave L';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fluticasona 50 mg FHisflunal Aerosol Inhalacion 120 Dosis Medi-Fav';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Con Ferula Forma Elastica Izquierda Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Damel Sin Azucar Sweet Mix';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante a base de Stevia Dulcilina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Compresa Friopak Frio/Calor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Isotónica de Agua de Mar Esteril Tonimer';
UPDATE products SET brand = 'Now' WHERE name = 'Citrato De Magnesio 200 mg Now x 100';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nutrisite Glutazinc 15.04g Alimento Nutritivo de L-Glutamina y Zinc Medsite';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Vitamina C 1 g Vitadyn C Oftalmi Sabor Mandarina x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Locion Para Pies Cool A-Ped Con Mentol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodón Algobap 100 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Steripharma S/Clinica 1 Und';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curcuma 60';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Farmatodo Absoluto';
UPDATE products SET brand = 'Going' WHERE name = 'Hidratante Going Sabor Fruta Del Dragon Sachet';
UPDATE products SET brand = 'Unknown' WHERE name = 'IntyProb 60capsulas Probiotico-Prebiotico Intylact';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C 100 mg Cebión Minis x 45';
UPDATE products SET brand = 'Unknown' WHERE name = 'Belara Clormadinona + Etinilestradol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina + Sitagliptina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Picosulfato de Sodio Verolax 7.5mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Cafeina + Clorfeniramina Dayflu Dia/Noche';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Vitaminas y Minerales Farmatodo +50 Años Frasco x 30';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Airoplast Adhesivo de plástico transparente Pharmaplast 2,5x5 1 Unidad';
UPDATE products SET brand = 'Pharmacorp' WHERE name = 'Omega-3 Fish Oil 2000 mg Pharmacorp Frasco x 60 Cápsulas';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Bastón 4 Puntas Estándar Altura Regulable Next Step';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Circulares x 100 Unidades Briutcare';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oxido De Zinc Vitamina A + E Ademina Plus Etifar Crema x 60 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Helios Diet Sin Azúcar Manzana x 280 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína de Queso Quest Chips x 32 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply Mix de Frijoles Inflados Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitamínico Antioxidante Oxinorm Medifarm';
UPDATE products SET brand = 'Behrens' WHERE name = 'Solución Electrolítica 45 meq Behrens Rehidrosol Zinc Uva x 600 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elasticas 5Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ortoban Yeso 4" X 3YDS  1Rollo 10 cm x 2,7 M';
UPDATE products SET brand = 'CureBand' WHERE name = 'Curas CureBand';
UPDATE products SET brand = 'Unknown' WHERE name = 'Canula De Oxigeno Tipo Bigote Pediatrica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zarzaparrilla';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Colonplant 400 mg Herbaplant Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Caliente Alivio Medipatch Talla L 10Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ramipril';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glucósidos Antraquinónicos + Acido Salicílico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Torta de Maíz con Yogurt De Fresa Kupiec x 70 gr';
UPDATE products SET brand = 'SPL' WHERE name = 'Crisplus Orlistat';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Hideven Rollo 25 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mezcla Sin Gluten para torta de vainilla Vegan Life';
UPDATE products SET brand = 'Pan' WHERE name = 'Pantoprazol Pandev';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Ginkgo Biloba 60tabletas Natural System';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Neopreno Kx Estabilizadora Talla L/Xl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Kx Elastica Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ibuprofeno + Tiocolchicosido';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ranitidina Vizerul';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidrotalcita 10% Antiacido Gastrum Plux Sabor Menta';
UPDATE products SET brand = 'Neilmed' WHERE name = 'Sinus Rinse Pediátrico Solución Salina Neilmed x 120';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetilcisteína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C 1 g Cebión';
UPDATE products SET brand = 'Unknown' WHERE name = 'FlexiVita Pro 60 Cápsulas Vitae';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cúrcuma Turmeric + Bioperine 1500 mg Val';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bencidamina 0,15%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nexcare Durapore 1x9,14m';
UPDATE products SET brand = 'Leti' WHERE name = 'Lisinopril 10 mg Lisilet Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + N-Butilbromuro De Hioscina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pelota de Yoga 55 cm Live&Fit';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Resveratrol + Vitamina E';
UPDATE products SET brand = 'Natural Systems' WHERE name = 'Vitamina C Natural System';
UPDATE products SET brand = 'Unknown' WHERE name = 'Wampole Tutti Frutti Aceite de Hígado de Bacalao + Vitaminas del Complejo B Emulsión x 240 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteylac Vainilla Instantaneo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Pureza Aloevera 80 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Confitura Sin Azucar Naturgourmet Sabor A Pina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Isla Mint';
UPDATE products SET brand = 'Leti' WHERE name = 'Esomeprazol 20 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion Isotonica de Agua de Mar Esteril Tonimer';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tonimer Normal';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tonimer Baby';
UPDATE products SET brand = 'Unknown' WHERE name = 'Broncoral Jarabe X 120 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'ArtiCure Ostearticular Advanced';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Sin Gluten Naturgourmet Sabor A Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Arepas Masa de Yuca Libre De Gluten Que Bites x 12 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glucerna Rpb Vainilla x 237 ml';