UPDATE products SET brand = 'Unknown' WHERE name = 'Oh Snack Chia y Zanahoria Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Obleas de Amaranto Coco Sin Azúcar Sin Gluten Halo';
UPDATE products SET brand = 'Ricola' WHERE name = 'Caramelos Duros con Hierbas y Edulcorante Original Hierba Suiza Ricola';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Sugar Free Albanese Sobre x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Dioxogen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Diet Sin Azúcar Sabor Fresa Helios Frasco x 280 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Crema Untable A Base De Mani';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collarin Blando Kx Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Piña En Trozos Deshidratado Frusnack';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica Saito Ortopedica 12 Cm';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Andadera Con Ruedas';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla de ruedas estandar';
UPDATE products SET brand = 'Klinos' WHERE name = 'Ondansetrón 8 mg Klinos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Clorfeniramina';
UPDATE products SET brand = 'JHC' WHERE name = 'Ceftriaxona 1 g JHC Vial x 1 Solución Inyectable I.V./I.M.';
UPDATE products SET brand = 'Unknown' WHERE name = 'Test de Embarazo Kx';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Cinta Microporosa Color Beige 1,2 Cmx 10 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sour Mix Damel Sin Azúcar Paquete x 100 g Gomitas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel De Abeja Apiangostura';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Transpiel 20 Unidades';
UPDATE products SET brand = 'Europharm' WHERE name = 'Curita Eurostrips Emo - Stops Eurofarm 31x72mm 12 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'PSI Ervostal 30comprimidos Interfamaceutica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azitromicina';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Montelukast 10 mg Airon Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carboximetilcisteína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Dioxogen Med Refrescante x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Kx Para El Brazo Tipo Malla Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Isogel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chips de Vegetales sin gluten Sensibly Natural con Sal Marina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche de Coco Vilay Sin Azucar Sin Gluten/Sin Lactosa 1 Litro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Energéticas Bolt Sabor Naranja Pro Bar Sobre x 60 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Proteína Quest Peanut Butter x 60 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cacao en polvo para repostería Sin Gluten Wepa 200 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cepillo Quirurgico Dexx';
UPDATE products SET brand = 'SPL' WHERE name = 'Sucralosa Splenda Edulcorante Líquido Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lercanidipina';
UPDATE products SET brand = 'Remeny' WHERE name = 'Fluconazol 150 mg Remeny';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Media Antiembolica Al Muslo Talla XXL Sigvaris DYNAVEN';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acua-e Agua Electrolizada Antiséptica. Limpiadora Piel y Mucosas (Acido Hipocloroso) x 900 ml';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento alimenticio Abintra Enterex Naranja x 27 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mezcla Para Torta Sin Gluten Glutenfri';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Proteína Farmatodo Base Caldo Hueso Vainilla x 560 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmov Bsn Brazo L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Helios Diet Sin Azúcar Albaricoque x 280 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera KX Elastica 2 Vias Sin Talon talla M';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina C 500 mg Letisan Sabor Uva Leti Tiras x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Kx Elastica Con Talon Cerrado Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Kx Elastica Talla M';
UPDATE products SET brand = 'ASK' WHERE name = 'Munequera Ask';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante Cero Calorías Dulcilina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nifedipina Tensomax Lp 30 Mg X 40 Cápsulas Liberación Prolongada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sultamicilina 750 mg DAC 55';
UPDATE products SET brand = 'Unknown' WHERE name = 'Full Granola Yogranola';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multicolageno Hidrolizado Premium 300 gr Mo4t Apex Group';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Integral Spaguetti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Gammasoy Renal L-Carnitina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adh Leukoplast 2x5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adh Leukofix 2.50x5m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Sesitive 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collar Cervical Forma Elastica Suave Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aciclovir 400 mg x 10';
UPDATE products SET brand = 'Calox' WHERE name = 'Acetaminofén + Pseudoefedrina + Clorfeniramina Dolgrip D Calox';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Farmatodo Absoluto 120Cc';
UPDATE products SET brand = 'Europharm' WHERE name = 'Curita Aloe Eurostrips Eurofarm 19X72Mm/25X72Mm 20 Unidades';
UPDATE products SET brand = 'Elmor' WHERE name = 'Flavoxato Clorhidrato 200 mg Genurin Elmor';
UPDATE products SET brand = 'Vivax' WHERE name = 'Meloxicam 15 mg Melovax Vivax';
UPDATE products SET brand = 'La Santé' WHERE name = 'Meloxicam 15 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Neopreno Kx Soporte Del Pulgar Y Correa De Velcro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply Chips de Lentejas Sabor a Jalapeño Sin Gluten';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Meloxicam 7.5 mg Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Elastica Kx 2 Vias Sin Talon S Kx';
UPDATE products SET brand = 'K6' WHERE name = 'Cuerda K6 Para Saltar Apolo III';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Kx Neopreno Talla L';
UPDATE products SET brand = 'ASK' WHERE name = 'Cuerda De Saltar Ask Colores Surtidos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche De Almendras En Polvo Sin Gluten Sin Azúcar Agora x 400 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kit de Reparacion Rapida Ciclismo T220';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Benefic Uomo Talla 2 Color Negro';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Baston de 1 Punto cromado';
UPDATE products SET brand = 'Ebben' WHERE name = 'Venda Economic 5Cm Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina Metform 850 mg Capsuven x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bismuto Subsalicilato Pepto-Bismol Suspensión Oral x 118 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorfeniramina + Dextrometorfano';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Impermeable Color Blanco 5Cm X 4,5Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collar Cervical Forma Elastica Suave Talla M';
UPDATE products SET brand = 'Rowe' WHERE name = 'Fluconazol 200 mg Flucon Rowe';
UPDATE products SET brand = 'Angelus' WHERE name = 'Fluoxetina 20 mg Angelus Health';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Simply7 Palitos de Vegetales con Sal Marina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fenobarbital 100 mg Gardenal MCK Pharmaceutical';
UPDATE products SET brand = 'Calox' WHERE name = 'Flavoxato 200 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Montelukast 10 mg Medigen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel Vital Honey Dose Vital';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Helios Diet Sin Azúcar Arándanos x 280 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein Sabor Vainilla';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Dynaven Sigvaris Beige Talla S 15-20 Pantorrilla x 2 und';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Azul Talla M 15-20 Pantorrilla x 2 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Hombro Izquierdo Kx';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Azul Talla L 15-20 Pantorrilla x 2 und';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Beige Talla XL 20-30 Punta Abierta';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina + Vitamina B5 Marnys 90';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Beige Talla L 20-30 Punta Abierta';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Flexible 10 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mupirocin 2% Dac 55 Ungüento x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Broxol Flem 750 mg/15 ml Jarabe Adulto x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Carne De Soya Soy-Tex 200 G';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina + Ambroxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Redireaders Con Estuche+2.00';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glutamina + BCAA 11 ml Marnys';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Estabilizadora Kx Con Bisagra De Neopreno Talla G';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Estabilizadora Kx Con Bisagra De Neopreno Talla P';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Elastica Almohadillas Silicon Kx Sin Latex Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = '!!Suplemento Alimenticio Inmunex Plus Vainilla Latte Polvo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Quinoa Spaghetti Quinoa Club x 250 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Rodilla 18-23 mmHg Talla 3 Color Daino';
UPDATE products SET brand = 'Pan' WHERE name = 'Medias De Compresion Panty 140 Den Talla 3 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Estéril 4x4 12';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Antiseptico Farmatodo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ceftriaxona';
UPDATE products SET brand = 'Unknown' WHERE name = 'N-Butilbromuro De Hioscina';
UPDATE products SET brand = 'Pan' WHERE name = 'Mezcla sin Gluten para Pancakes de Vainilla Vegan Life';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche de Almendras En Polvo Sin Gluten Sin Azucar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cristal de Sabila Natural para bebidas Terraloe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quinoa En Grano';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cúrcuma Molida';
UPDATE products SET brand = 'Pediasure' WHERE name = 'Pediasure 400 G';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketchup Sin Azucar Naturalyst';
UPDATE products SET brand = 'Unknown' WHERE name = 'Soporte Kx De Neopreno Para Muslo Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Kx De Neopreno Talla M';
UPDATE products SET brand = 'K6' WHERE name = 'Banda Elástica K6 Nivel 1';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento Alimenticio Enterex Protical Vainilla Lata';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mezcla De Brownie Sin Gluten Gluten Fri';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Truballs Mani y Pasas Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostados Sabor a Oregano';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hierro + Ácido Fólico';
UPDATE products SET brand = 'Biotech' WHERE name = 'Blocax Candesartán 16 mg Biotech Blister x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mantequilla En Spray';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Dynamics universal pediatrico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curcuma Organica Molida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cepillo Quirurgico Dispomedic';
UPDATE products SET brand = 'Pan' WHERE name = 'Pancreatina + Simeticona';
UPDATE products SET brand = 'Biotech' WHERE name = 'Betametasona 0,05% Betaderm Biotech Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Elmor' WHERE name = 'Bencidamina + Cetilpiridino 0,15/0,25% Flomed Elmor Solución Tópica Bucal x 180 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Massi Bolas de Algodón Cotton Soft 50 UNID';
UPDATE products SET brand = 'Dixson' WHERE name = 'Pelota de yoga Dixson 65 Cm';
UPDATE products SET brand = 'Dixson' WHERE name = 'Yoga Mat Dixson Colores Surtidos 5MM';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite de Oliva EV en Spray Visciano x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Leon Sport Recovery Pre y Post-workout Crema Real';
UPDATE products SET brand = 'ASK' WHERE name = 'Set De Entrenamiento Ask';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin gluten Maxi Sorrisi Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quinoa Quinoa Club Hojuelas';
UPDATE products SET brand = 'Now' WHERE name = 'Edulcorante Fructosa Now 1.360g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante Hermesetas Liquido Frasco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Kx Elastica Con Talon Cerrao Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica Sport 12 Cm';
UPDATE products SET brand = 'Pan' WHERE name = 'Sin gluten Pan Matin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante All Organic Pure Stevia 50 Gr';
UPDATE products SET brand = 'ASK' WHERE name = 'Ligas de resistencia ASK';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta De Arroz Penne Dorado S/Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bisacodilo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Forma Elastica Para Hombro Femenino Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Con Ferula Forma Elastica Derecha Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Muslo 22-27 mmHg Talla 5 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Rodilla 22-27 mmHg Talla 4 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina K2 Plus - Vitamina D3 100mcg 100';
UPDATE products SET brand = 'Europharm' WHERE name = 'Curita Aloe Eurostrips Eurofarm Variadas 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Antiséptica Dioxogen Med Hipoalergénica x 115 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Itraconazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina 1% Farbicil Medihealth Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vendaje Impermeable Cure Aid Pharmalast 100 Unidades';
UPDATE products SET brand = 'Europharm' WHERE name = 'Sutura Adhesiva Eurofarm Eurosuture 6x38mm';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 1%';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Media de Compresión Sigvaris Negra Talla S 15-20 Pantorrilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nifedipina LP';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromuro de Ipratropio + Fenoterol Bromhidrato 0.25mg/0.5mg JL Pharma';
UPDATE products SET brand = 'CureBand' WHERE name = 'Curitas CureBand Redonda Premium x 100 und';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Dynaven Sigvaris Pantorrilla Beige Talla XL 15-20';
UPDATE products SET brand = 'JHC' WHERE name = 'VPD Muletas Adaptables JHC Médica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tira Elastica Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jengibre Molido';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aminoacidos BCAA + Glutamina Sascha Fitness Uva';
UPDATE products SET brand = 'ASK' WHERE name = 'Mancuernas de Vinil 8LB Ask';
UPDATE products SET brand = 'K6' WHERE name = 'Mancuerna 3LB de Vinil K6';
UPDATE products SET brand = 'ASK' WHERE name = 'Pesa Rusa 8Kg Ask';
UPDATE products SET brand = 'ASK' WHERE name = 'Mancuernas de Vinil 12LB Ask';
UPDATE products SET brand = 'ASK' WHERE name = 'Mancuernas de Vinil 10LB Ask';
UPDATE products SET brand = 'K6' WHERE name = 'Vendaje Deportivo Autoadhesivo K6 7.5cm X 4.5m Surtidos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cintas Kinesiológicas Pre Cortadas 100 % Algodón 20 x 25 cm KT Tape Color Negro';
UPDATE products SET brand = 'Unknown' WHERE name = 'Guata de Algodón Eurosoft 10 cm x 3 mt x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kit de Bio Seguridad Antiseptico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiras Nasales Zuviss x 10 Unidades Grupo Cleanup';
UPDATE products SET brand = 'K6' WHERE name = 'Pelota de Yoga K6 65cm Sin Bomba';
UPDATE products SET brand = 'ASK' WHERE name = 'Balon Medicinal 3kg Ask';
UPDATE products SET brand = 'ASK' WHERE name = 'Pesas Muñequera - Tobillera 1Kg Ask';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromexina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Alm Gammaf Prokal Diab Fibra';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Carboprotein Mant';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína Soy Protein Dulcilina Isolate Piña Colada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pastelitos Rellenos de Queso Libre de Gluten Que Bites x 20 und';
UPDATE products SET brand = 'Pan' WHERE name = 'Pan de Hamburguesa Tradicional Sin Huevo Libre de Gluten Victorias Natural Fooods x 550 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sin Gluten Pasta Chickpea Spaghetti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante Skinny Sweet Eritritol';
UPDATE products SET brand = 'ASK' WHERE name = 'Set TRX Ask';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Pharmapore Sterile 5x7,2 Pharmalast 5 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Albendazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Valproico 500 mg Valpron';
UPDATE products SET brand = 'Unknown' WHERE name = 'Saccharomyces Cerevisiae Florax-Sm 50 Millones 5 Viales x 5 ml Pediátrico Hebron';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Transparente Pharmapore PU IV 5x5,7 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche para Cicatriz Cure Aid Pharmalast 6 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Canula De Oxigeno Tipo Bigote Adulto';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kalan Krunch Red Velvet sin azúcar gluten y sin gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cereal Truballs Mani y Pasas Sin Gluten';
UPDATE products SET brand = 'Pan' WHERE name = 'Pan De Molde Sin Gluten Best Gluten Free x 300 gr';
UPDATE products SET brand = 'Pan' WHERE name = 'Pan Sin Gluten Hogaza Best Gluten Free x 300 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pizza Queso de Bufala Masa Garbazo / Yuca Libre de Gluten BurbujaPizza';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Aimdent Sin Azúcar Sabor Canela x 12 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralosa Endulzante En Polvo Equal 50';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Aimdent Sin Azúcar Sabor Sandia x 12 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína Isolatada Iso26 Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pizza Queso de Bufala';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multicolágeno Hidrolizado Premium M04T x 454 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Sin Azucar Falidu Sabor Uva,Frambuesa Y Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Elastica Almohadillas Silicon Kx Sin Latex Talla G';
UPDATE products SET brand = 'Unknown' WHERE name = 'ALG CHICCO DESMAQ 80 UND';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta De Arroz Fusilli Dorado S/Gluten';
UPDATE products SET brand = 'Tiares' WHERE name = 'Pasta Sedani Quinoa Dorado S/Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Fusilli Quinoa Dorado S/Gluten';
UPDATE products SET brand = 'Angelus' WHERE name = 'Tamsulosina 0,4mg Angelus Health';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetirizina';
UPDATE products SET brand = 'Pan' WHERE name = 'BEB TERRAEPANE RICE COCO 1 LT';
UPDATE products SET brand = 'Unknown' WHERE name = 'Confitura Sin Azucar Naturgourmet Sabor A Durazno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Muslo 22-27 mmHg Talla 2 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Confitura Sin Azucar Naturgourmet Guayaba';
UPDATE products SET brand = 'Unknown' WHERE name = 'Salsa De Tomate Helios Casera';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Rodilla 18-23 mmHg Talla 4 Color Daino';
UPDATE products SET brand = 'Laproff' WHERE name = 'Nitrofurantoína 100 mg Laproff Blíster x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Fusilli Chia Dorado S/Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento Nutricional Nutradition Nino Vainilla';
UPDATE products SET brand = 'Intervit' WHERE name = 'Linaza Molida Intervit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Lentejas Rojas Dorado S/Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bisacodilo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sirope organico de Agave Sugar Krush';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Muslo 18-23 mmHg Talla 5 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colchón Antiescaras Con Compresor Dovant PRESSFLOW x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Muslo 18-23 mmHg Talla 4 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Luekofix 5cm/9,2m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento Nutricional Nutradition Gesta Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento Nutricional Nutradition Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te Nature Jamaica Libre de Azucar 1.2litros';
UPDATE products SET brand = 'Unknown' WHERE name = 'Doxiciclina 100 mg Vivradoxil Alpharma';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Tegaderm + Pad 9x15cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante de Sucralosa Makea Sachets';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Tegaderm + Pad 9x20cm';
UPDATE products SET brand = '3M' WHERE name = 'Adhesivo 3M Tegaderm + Pad 9x25cm';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Beige Talla S 20-30 Punta Abierta';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Gris Talla L 15-20 Pantorrilla';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Gris Talla M 15-20 Pantorrilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te Nature Negro Libre de Azucar 1.2litros';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colageno';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina E 400UI Rarivit E 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Leon Sport Xplosion Pre-workout Iced Lemonade';
UPDATE products SET brand = 'Unknown' WHERE name = 'Farbicil 1%';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Complejo B Miovit Cofasa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Antiseptico Santa Teresa 350 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Isogel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Linaza Con Piña';
UPDATE products SET brand = 'Now' WHERE name = 'Proteina Whey Protein Now Fresa';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gel Farmatodo Antibacterial';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gel Antibacterial Farmatodo 120Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada Sin Gluten Naturgourmet Sabor A Durazno';
UPDATE products SET brand = 'Unknown' WHERE name = 'FM Gel Antibacterial USO INTERNO';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Alim Gammf Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Push Up Bars Jogger';
UPDATE products SET brand = 'Unknown' WHERE name = 'CUBO DE YOGA';
UPDATE products SET brand = 'Pan' WHERE name = 'BEB TERRAEPANE ALMENDRAS 1 LT';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sumplemento Nutricional Nutradition Ad Fos Fresa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te Nature Jamaica Libre de Azucar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de granola sin azucar de miel y pasas Avelina';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Leukoplast Seda 5cm X 9,14m';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Antiembolica Autoreggente Talla M Color Blanco';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antibacterial Sterigel';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'PUSH UP BARS PLASTICAS BODY';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Negra K6 Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion esterilizante Biogermex 500 ml';
UPDATE products SET brand = 'K6' WHERE name = 'Banda Elástica K6 Nivel 2';
UPDATE products SET brand = 'K6' WHERE name = 'TOBILLERA AJUST NEOP K6 T-L';
UPDATE products SET brand = 'Leti' WHERE name = 'Pregabalina 75 mg Pegyt Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calcio 600 + Vitamina D3 Rarivit 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Aimdent Sin Azúcar Sabor Menta Verde x 12 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Aimdent Sin Azúcar Sabor Fresa x 12 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Restore Sascha Fitness x 120';
UPDATE products SET brand = 'Unknown' WHERE name = 'Piña Colada Sin Trigo Sin Lactosa Sin Azúcar Hola Granola x 300 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nistatina Coaspharma Frasco x 60 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Maalox Menta 180 Ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Muslera Especial Neoprene Body T/u';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Neoprene Sencilla Body T/u';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lechosa Deshidratada El Jarillo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Piña Deshidratada El Jarillo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica Sport 20 Cm';
UPDATE products SET brand = 'Ricola' WHERE name = 'Caramelos Duros con Hierbas y Edulcorante con Sabor a Limon Menta Ricola';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elastica Sport 15 Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Llave de Radios Ciclismo T110';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bks Guaya para Accesorios L110';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mezcla Sin Glutten Multiproposito Vegan Life';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cincha para codo Dynamics acolchada';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Arizona Fruit Snacks Green Tea';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gomitas Arizona Fruit Snacks Mixed Fruits';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Exit Premium Sin Azucar Sabor Menta Fuerte 12 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Exit Premium Sin Azucar Sabor Menta-Limonada 12 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mayonesa Sin Gluten Ricarda 1 Sobre';
UPDATE products SET brand = 'Unknown' WHERE name = 'Obleas de Amaranto Bites Capuchino Sin Azúcar Sin Gluten Halo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ketchup Sin Gluten Ricarda Tomate 1 Sobre';
UPDATE products SET brand = 'Unknown' WHERE name = 'Avena Instantanea Avelina con Multi Semillas Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hand Grips Manija Plastica Jogger';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mat de Yoga Jogger';
UPDATE products SET brand = 'ASK' WHERE name = 'Banda de Resistencia Media Ask';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Levocetirizina 5 mg Levorat Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Exit Sin Azucar Sabor Patilla 5 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Exit Sin Azucar Sabor Fresa 5 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Drospirenona + Etinilestradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mantequilla de Maniprotein Vainilla Edellafit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mantequilla de Chocomani Natural Edellafit';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Aclarante Corporal Frasco x 100 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Transparente Fijacion Canulas Pharmapore  7x9 20 Unidades';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Desmanchadora Forte Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio Spermotrend 90Capsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sin Gluten Heaven Cookie Mix';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mantequilla de Mani Natural Edellafit';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Peróxido Benzoilo 10% x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum de Cejas y Pestañas x 10 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Agua Micelar Frasco x 200 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gel Hidratante';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Gel Hidratante Protector Solar Frasco x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Jabón Piel Grasa Frasco x 100 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pesas Tob/Mun Body';
UPDATE products SET brand = 'ASK' WHERE name = 'Mancuernas Ask 2 Und';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Bicarbonato Sodio Sobre/Papeleta x 25 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Bórico Botica Casera Sobre x 20 gr';
UPDATE products SET brand = 'Leti' WHERE name = 'Diclofenac Potásico 50 mg Genven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Estabilizadora Kx Con Bisagra De Neopreno Talla Xg';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Miel de Borax x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Para Hemorroides Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aplicador de Algodon Kx medical 100Unids';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Inmovilizador Dynamics Rod C/sop Post talla XL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Europore Microporoso 2" x 9m Piel Eurociencia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Europore Microporoso 1" x 9m Piel Eurociencia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Europore Microporoso 1" x 9m Blanco Eurociencia';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Azufre Sobre/Papeleta x 25 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera KX Ajustable talla unica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Pharmapore Sterile 10x35 Pharmalast 5 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Antiembolica Autoreggente Talla L Color Blanco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aposito Pharmapore Sterile 10x25 Pharmalast 5 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ejercitador de Antebrazo Ajustable';
UPDATE products SET brand = 'Unknown' WHERE name = 'Set de Pedales Clasicos R600';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite de Coco Frasco x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Jabón Facial Aloe Vera y Manzanilla Frasco x 100 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Gotas de Valeriana Gotero x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Agua de Rosas x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Hojas de Sen Sobre/Papeleta x 10 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Contorno de Ojos Frasco x 10 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum Vitamina C x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Serum Contorno de Ojos Frasco x 10 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Forma Elastica cierre magico negra talla S/M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Con Ferula Forma Elastica Izquierda Talla M';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Ozonizada Frasco x 60 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Crema Antiedad Frasco x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sal De Higuera Botica Casera Sobre x 25 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Uvipiel Hidratante/Antioxidante Gel x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Jabón Facial con Avena Frasco x 100 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Anís Estrellado Sobre/Papeleta x 10 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Memantina';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Montelukast 5 mg Airon Oftalmi';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Forma elastica Universal Talla M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Collar cervical Forma elastica suave talla S';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Jabón Facial De Rosas x 100 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Forma Elastica Para Hombro Masculino Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Forma elastica Universal Talla L';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum De Retinol x 10 ml';
UPDATE products SET brand = 'K6' WHERE name = 'Bandas Elásticas K6 Nivel 3';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Solución Antimicótica fuerte Gotas Anti Hongos x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Pasta al Agua x 150 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite De Coco Extra Virgen Prensado En Frío x 200 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Lifting Hidratante Efecto Tensor Frasco x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Callicida Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Solución Callicida Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Tónico con Minoxidil Frasco x 60 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gotas del Carmen 60 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Exfoliante Facial/Corporal Coconuez Frasco x 50 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alumbre En Piedra Botica Casera Sobre x 20 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jarabe Lamedor Pediátrico x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Dynamics Neopreno Ajustable';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel antibacterial Dioxogen con Vitamina E 110 ml';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias De Compresión Sigvaris Azul Talla S 15-20 Pantorrilla x 2 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tapones De Oídos Espuma Protechs';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Acido Glicolico Frasco x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Serum Restaurador Frasco x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Contorno De Ojos Despigmentante';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Restaurador Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Agua Micelar Frasco x';
UPDATE products SET brand = 'Leti' WHERE name = 'Trimebutina 300 mg Dobracid L.P. Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fluoxetina 20 mg Psicofarma';
UPDATE products SET brand = 'La Santé' WHERE name = 'Carboximetilcisteína 100 mg/5 ml Broxol Flem La Sante Frasco x 120 ml Jarabe Pediátrico.';
UPDATE products SET brand = 'Unknown' WHERE name = 'Riñonera + 2 Botellas Live&Fit';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gotas de Azahares Gotero x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media Pie Sensible Diabetico Hilado Cobre L Blanco Medi Varic';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media Pie Sensible Diabetico Hilado Cobre S Negro Medi Varic';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media Pie Sensible Diabetico Hilado Cobre S Blanco Medi Varic';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite Mineral x 60 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Crema Caléndula Formula Magistral Farmatodo Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum Acido Tranexamico x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Pomada de Azahares Pote x 60 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Universal Forma elastica talla M';
UPDATE products SET brand = 'Elmor' WHERE name = 'Ibuprofeno 400 mg Brugesic Elmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Escitalopram Escitapax';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Emulgel Calendula Manzanilla Y Zabila';
UPDATE products SET brand = 'Unknown' WHERE name = 'Furodemil';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Jabón Pieles Grasas Frasco x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gel Anti Acné';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Emla Xylocaína';
UPDATE products SET brand = 'Elmor' WHERE name = 'Fenticonazol 2% Mycofentin Elmor Crema Vaginal x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Azul Metileno Frasco x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Pomada Fenol x 10 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Cremigel Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Gel Anti Acné Frasco x';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Mebendazol 100 mg Bendamen Siegfried';
UPDATE products SET brand = 'Unknown' WHERE name = 'Oxolamina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Gel Antiflamatorio Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Kinesiologica Go Plus 1 Metro Color Rosado';
UPDATE products SET brand = 'Unknown' WHERE name = 'Aceite De Coco';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinta Kinesiologica Precortada Go Plus 5 Metros Color Rosado';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Parafina';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Pasta Al Agua Ozonizada';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema Para Hematomas x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Jabon Ozonizado';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Kx 4x4 x 2 und';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema Azufrada Al 10% x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gel Antibacterial Farmatodo';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema De Árnica x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jabón Ozonizado x 100 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Yodo Blanco Frasco x 60 ml';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla Sanitaria Ajust Cleany Sin Ruedas';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla Sanitaria Con Ruedas Cleany Plus';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gotas Del Carmen x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cuerda De Resistencia Right Gear';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Negra K6 Talla M';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Azul K6 Talla M';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Champú Para Psoriasis x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Violeta de Genciana Frasco x 30 ml';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Inmovilizador Dynamics Rod Plus C/bisag Art 57m';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Inmovilizador Dynamics Rod C/sop Post talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'ADHESIVO GIDAGUS PIEL 1.25 X 5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Forma Elastica Para Hombro Masculino Talla L';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jabón con Glicerina x 120 ml';
UPDATE products SET brand = 'Calox' WHERE name = 'Finasteride 5 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mupirocin Dalcitrin 2%';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gotas de Árnica Gotero x 60 ml';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Inmovilizador Dynamics Rod C/sop Post talla M';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Inmovilizador Dynamics Rod C/sop Post talla S';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Cremigel Antiage Con Retinol x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Tónico Capilar Anticaída Frasco x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pomada De Azufre 0,1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hierro';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Niacinamida Frasco x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Protector Solar Gel x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jarabe Zabila x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Tonico Farmatodo Facial Dia';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Crema Farmatodo Hipoalergenica';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Crema Farmatodo Acido Glicolico Al 3%';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Crema Facial Humectante x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Alcohol Quemar Frasco x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartán + Hidroclorotiazida';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Gotas Relajante Nervioso Frasco x';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Alcohol Yodado Frasco x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite Bronceador x 60 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Crema Farmatodo Acido Glicolico Al 5%';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Jarabe Zabila Miel y Jengibre Frasco x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Exit Sin Azucar Sabor Menta Suave 5 Unidades';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema Facial Antiedad x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite Alcanforado x 30 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Cloruro De Magnesio Farmatodo Sobre';
UPDATE products SET brand = 'Unknown' WHERE name = 'Toallas Humedas Pulplus 70% Alcohol 25Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Esteril Ortoban 3X3 2Und';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Algodón Farmatodo Motas x 50 und';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Citrato Potasio Frambuesa 10.8% 1Lt';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Jarabe Farmatodo Citrato Potasio 10.8% 1Lt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Para Adultos Zuviss Adhesivas x 20 und';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Antiseptico Farmatodo Galon 3.7Lt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Vult O';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Tela 5 cm x 9,10 m Zuviss x 1 und';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Algodón Farmatodo Hidrofilo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Pureza 240/200 Gr';