UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Colágeno + Magnesio';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Kx Ajustable Talla Unica';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Beige Zuviss 1,25 cm x 9,10 m x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'L-Carnitina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Leukopor Piel 2.5cm X 4.57m';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Andadera Estándar Ajustable Next Step';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Negra K6 Talla L';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Medias de Compresión Sigvaris Beige Talla M 20-30';
UPDATE products SET brand = 'Polinac' WHERE name = 'Centella Asiática 1% Madecassol Polinac Ungüento x 20 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Rarivit Mujer 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Protector de Colchon All Pro Almohada Estandar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nimodipina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Coadyuvante Hemorroides Hemovar Sanavital Crema x 40 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Goli Gomitas Superfrutas 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gotas Nasales Nitrato De Nafazolina 0,1% Ninazo Solución Adultos x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Acu-life Para Ojo';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Levofloxacina 750 mg Levamox FC Pharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B + Vitamina C + Calcio Dovilin Bioquímica Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Kx Elastica Talla M';
UPDATE products SET brand = 'Valmor' WHERE name = 'Pregabalina 75 mg Prelival Valmor';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Media Antiembolica Al Muslo Talla M Sigvaris DYNAVEN';
UPDATE products SET brand = 'Unknown' WHERE name = 'Melatonina';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Pantoprazol 40 mg Aless Pharmaceuticals';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén';
UPDATE products SET brand = 'Unknown' WHERE name = 'Prosilod';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Negra K6 Talla XL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cefepime 1000 mg ADN Medical Solución Inyectable';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Blanca Jogger Ad';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Negra K6 Talla M';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Acetaminofén + Dextrometorfano + Clorfeniramina + Fenilefrina Noxpirin Grip Siegfried x 12';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Dequalinio + Lidocaína 6,25mg/6,00mg Benzodiazol Siegfried Tuttifruti Blíster x 4';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amlodipina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Acido Clavulanico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol Ezolium';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C 1.000 mg Preventud Plus x 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina A + Vitamina D3 Rarivit Gotas Sabor Naranja';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo De Tela Zuviss';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Multivitaminas + Minerales Farmatodo Frasco x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Vision Vitamins 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Frío Para  La Fiebre Medipatch 4 Und';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Sal de Higuera Sobre/Papeleta x 25 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Ácido Bórico Sobre/Papeleta x 25 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Kx Neopreno Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Tela Zuviss';
UPDATE products SET brand = 'Ebben' WHERE name = 'Gasa Super Clinica Estandar 2,4Cm 4Pliegos Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera De Neopreno Jogger T/S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Elastica Blanca Jogger T/M';
UPDATE products SET brand = 'Calox' WHERE name = 'Amoxicilina 500 mg Minoxy x 16 Cápsulas Calox Mck';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Con Ferula Forma Elastica Izquierda Talla L';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin gluten Corn Flakes Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Now' WHERE name = 'Potassium 100tabletas Now';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Mapurite 300 Mg 90Capsulas Arcoiris';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Dama Pasta +3.50';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Dama Pasta +1.00';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Caballero Pasta +1.50';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Caballero Metal +3.00';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Caballero Metal +2.50';
UPDATE products SET brand = 'Leti' WHERE name = 'Kanamicina + Clorfeniramina + Fenilefrina 175/250/125mg Monosulpa Leti Gotas x 15 ml';
UPDATE products SET brand = 'Ebben' WHERE name = 'Gasa Estandar 1,2Cm 4Pliegos Ebben';
UPDATE products SET brand = 'Schar' WHERE name = 'Sin gluten Crostini Schar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clonixinato de Lisina + Propinox Clorhidrato Espasmo Dolofor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack De Quinoa Y Maiz Horneadas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcanfor Dencorub 40G Gel Ponce Y Benzo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Whey Protein Naturistik Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Terbinafina 1% Farbicil Medihealth Loción Tópica x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vendaje Autoadhesivo Kbandage Tipo Coban 10cm x 4.5m Colores Varios No Esteril Volk';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tapones De Oidos Jogger';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Vitaminico Rarivit Calcio + D3 + B12 Suspension Oral Sabor Cereza';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina D3 2000 UI Diglet Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Kupiec Torta de Maiz con';
UPDATE products SET brand = 'Leti' WHERE name = 'Dobesilato de Calcio 500 mg Doxium Leti';
UPDATE products SET brand = 'Sanofi' WHERE name = 'Bascillus Clausii 2000 Millones/5ml Enterogermina Sanofi Suspensión Oral X 10 Frascos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Flatoril 80 mg/ml Frasco x 20 ml Suspensión Gotas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tapones de Oidos para Natacion Adultos TYR';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Caballero Metal +1.00';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Redireaders Con Estuche +2.50';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Glicerina Frasco x 60 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vendaje Neuromuscular Colores Surtidos Pharma KT 1 Unidad.';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Serum Ácido Hialurónico Frasco x 30 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Clarivision Caballero Metal +2.00';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Alumbre en Piedra Sobre/Papeleta x 25 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite de Coco Frasco x 60 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Microporoso Color Blanco 2,5 Cm X 4,5 M';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Protección Luz Azul +3.0';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Levotiroxina Sódica 50 mcg Aless Pharmaceuticals';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mometasona + Ácido Salicílico Furuoativ Plus 0,1%/5%';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Furoato De Mometasona 50 mcg Trinaria Megalabs Spray Nasal x 120 Dosis';
UPDATE products SET brand = 'ASK' WHERE name = 'Medias De Yoga Ask Dedo Abierto Colores Surtidos';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ajo Premium';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorhexidina 0,12% Peridont Enjuague Bucal x 350 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina C 500 mg Letisan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pesas Tobilleras Body 5L';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Escoba De Carnicero Herbaplant 350 Mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico A-D-Vit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitaminico Rarivit Hair 30';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla de rueda ortopedica';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Hidratante Facial con Colágeno x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina D 1000 UI DarliDe FC Laboratorios';
UPDATE products SET brand = 'Unknown' WHERE name = 'Isla Mint';
UPDATE products SET brand = 'Unknown' WHERE name = 'Calaminol Fresh';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol + Clenbuterol Mucosolvan Compositum 7,5mg-5mcg/5ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diosmina-Hesperidina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorace jarabe';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Ambroxol + Clenbuterol 7,5mg-5mcg/5ml Misulvan Compositum PlusAndex Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Cinta Microporosa Color Blanca 5 Cm X 4.5 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tensiometro Digital De Brazo Flexmed';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Liv.52 Himalaya 100 Tab Natural L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ginseng';
UPDATE products SET brand = 'Sigvaris' WHERE name = 'Media de Compresión Sigvaris Negra Talla M 15-20 Pantorrilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Microporoso Color Beige 5 Cm X 10 Cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela microporoso color blanco 1,2 cm x 4,5 m';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Vitamina C Frasco x 30 ml';
UPDATE products SET brand = 'Arcoiris' WHERE name = 'Magnesio Glicinato  Arco Iris Frasco x 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fomentera Electrica Plenia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Guata Ortoban 4"X3Yds 1';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Cinta Transparente 1,2 Cm X 4,5 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Flexibles Briutcare x 20 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Dietetico My Fast Burner 60';
UPDATE products SET brand = 'Europharm' WHERE name = 'Apósito Euroderm Plus Eurofarm 5 x 7 cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Biotin + Vitamina C&E 10000 mcg Falidu Frasco x 60 Gomitas Masticables';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciproterona + Etinilestradiol Mabra 2/0,035Mg X 21';
UPDATE products SET brand = 'Unknown' WHERE name = 'ALGODON CHICCO MOTAS 100UND';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Pureza Aloe Vera 1 L';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Farmatodo Absoluto';
UPDATE products SET brand = 'Unknown' WHERE name = 'Soporte de Rodilla Talla Única Kestal';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Talla Única Kestal';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gotas De Valeriana Gotas x 60 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amiodarona';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Glicerina Frasco x 30 ml';
UPDATE products SET brand = 'Pan' WHERE name = 'Media Panty de Compresión 18-23 mmHg Talla 2 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ampicilina + Sulbactam';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dipirona 500 mg Zaki';
UPDATE products SET brand = 'La Santé' WHERE name = 'Esomeprazol 40 mg Esoz Pharmetique Labs';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Andadera con Ruedas Estándar Ajustable Next Step';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pesa Tobillera 1 Kg Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cinturon para Lumbar Live&Fit';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Autoreggente 280 Den Talla 3 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Muslo 22-27 mmHg Talla 4 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Microporoso Color Blanco 2,5 Cm X 10 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Dioxogen Med Refrescante x 950 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Banda De Resistencia L2';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Elegance 70% Alcohol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Leukoplast Seda 7,5cm X 9,14m';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Muletas Ajustables Estándar Talla S Next Step';
UPDATE products SET brand = 'Unknown' WHERE name = 'Toallita de Alcohol Briutcare 1Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina + Acido Clavulanico Clavoxilin 500/125Mg 16';
UPDATE products SET brand = 'Unknown' WHERE name = 'Citrato de Calcio + Magnesio y Zinc';
UPDATE products SET brand = '3M' WHERE name = 'Manta de Yoga K6 Basic 3mm colores surtidos';
UPDATE products SET brand = 'Going' WHERE name = 'Hidratante Sabor Uva Going Sachet x 10 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Óxido de Zinc + Agua Pastezinc Soma Frasco x 50 g';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Termo Acero Inoxidable';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Protección Luz Azul +0.0';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Nordic Vision' WHERE name = 'Lente Lectura Nordic Vision Helsinborg +1.0';
UPDATE products SET brand = 'Vargas' WHERE name = 'N-Butil-Bromuro de Hioscina 10 mg Atroveran Vargas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Levodopa + Carbidopa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ondansetrón 8 mg H&M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mometasona Furuoativ 0,1%';
UPDATE products SET brand = 'La Santé' WHERE name = 'Ambroxol 15 mg La Santé Jarabe x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cetilpiridinio + Lidocaína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitamínico Prenatal Miagest';
UPDATE products SET brand = 'Unknown' WHERE name = 'Miel Magic Honey Blister 3 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrilo Forma elastica Adulto Fucsia';
UPDATE products SET brand = 'Portugal' WHERE name = 'Clotrimazol 1% Gentamicina 0,1% Betametasona 0,05% Bexaderm Portugal Crema x 20 g';
UPDATE products SET brand = 'Unknown' WHERE name = 'Casabe Molido Casabe';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Serum Antioxidante Frasco x';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gel para Picadura Tubo x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hojas de Sen Botica Casera Sobre x 5 gr';
UPDATE products SET brand = 'Europharm' WHERE name = 'Adhesivo Eurotrasp Eurofarm 1,25cm x 5m';
UPDATE products SET brand = 'JHC' WHERE name = 'VPD Bastón Adaptable 4 Puntas JHC Medica x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ranitidina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorfeniramina – Sinutil Combo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Neumotex';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Negro +2.0';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cojin Ortopedico Alco';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Naranja K6 Talla S';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Naranja K6 Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Glicerina 1,68 g Laxantes Pediátrico';
UPDATE products SET brand = 'Vick' WHERE name = 'Guaifenesina 1,6 g Vick 44 Exp Jarabe Frasco x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Magistral Farmatodo Contorno De Ojos Hipoalergenico Frasco x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostado The Pod Snacks Sabor A Chile y Limon';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media Pie Sensible Diabetico Hilado Cobre L Negro Medi Varic';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media Pie Sensible Diabetico Hilado Cobre XL Blanco Medi Varic';
UPDATE products SET brand = 'Unknown' WHERE name = 'Yoga Mat x 0.5 cm +';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Kx Elastica Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Meal Replacement';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciprofloxacina Ciprolet 500 Mg X 20';
UPDATE products SET brand = 'Unknown' WHERE name = 'Olmesartán Medoximil + Amlodipina';
UPDATE products SET brand = 'Calox' WHERE name = 'Albendazol 200 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Med Comprinet Muslo Sz 7 T/xl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciproterona + Etinilestradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Meal Replacement';
UPDATE products SET brand = 'Unknown' WHERE name = 'Codera Kx Elastica Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Forma elastica Universal Talla M';
UPDATE products SET brand = 'Ebben' WHERE name = 'Venda Elastica 10Cm Ebben';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Aceite de Almendra Frasco x 30 ml';
UPDATE products SET brand = 'Sweetest' WHERE name = 'Edulcorante Sweetest';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Farmatodo Gel Aloe Vera';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mancuerna 5 LB Live&Fit';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Antiséptico Farmatodo Spray';
UPDATE products SET brand = 'Leti' WHERE name = 'Empagliflozina 10 mg Izaban Leti';
UPDATE products SET brand = 'Rowe' WHERE name = 'Losartán 100 mg Nefrotal Rowe';
UPDATE products SET brand = 'La Santé' WHERE name = 'Mometasona 0,1% MomeQ Pharmetique Labs Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Norestisterona Enantato + Estradiol Valerato';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina + Montelukast';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hisopos de Yodo 50unidades Lodopovidona Two5med';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Muletas Ajustables Estándar Talla M Next Step';
UPDATE products SET brand = 'Procare' WHERE name = 'Gasa Sobre 2x2 Procare';
UPDATE products SET brand = 'Zuzu' WHERE name = 'Mesalazina 500 mg Laboratorios Zuzu x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gasa Estéril 4x4 Compomedica Sobre x 2 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Forma Elastica Para Hombro Masculino Talla Xl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vendaje Neuromuscular Rosado Pharma KT 1 Unidad.';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen Analper 150 mg/5 mL Jarabe Pediátrico x 120 mL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Kx Elastica 4 Vias Talla S';
UPDATE products SET brand = 'Vargas' WHERE name = 'Simeticona 160 mg Antifom Forte Vargas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Laxante Lactulosa Solucion USP';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diclofenac Sódico 1% Soto Global Group Gel x 50 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Antiseptico Guardian';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Kx Para El Brazo Tipo Malla Talla P';
UPDATE products SET brand = 'Calox' WHERE name = 'Amoxicilina 500 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Memantina 10 mg Eutebrol Adium x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteína NutriClara de Huevo Sabor  a Moka';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Algodón Hombre Rodilla 18-23 mmHg Talla 4 Color Azul';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Silla De Baño Con Respaldar Dovant x 1 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Microporoso Color Beige 5 Cm X 4,5 M';
UPDATE products SET brand = 'Europharm' WHERE name = 'Adhesivo Europor Eurofarm 5cm x 5m';
UPDATE products SET brand = 'ASK' WHERE name = 'Yoga Mat ASK 173 x 61 x 0.3 cm';
UPDATE products SET brand = 'Ricola' WHERE name = 'Caramelos Duros con Hierbas y Edulcorante Ricola con Sabor a Arándano Rojo Sin Azucar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Roskitas Horneadas De Yuca';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento alimenticio Multivitaminas y minerales 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curcuma+ Moringa + Vitamina E + Selenio Bio Vital 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Jengibre + Propoleo + Zinc + Vitamina C Nutri-Defen 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solucion bactericida germicida GERDEX en spray 240 ml';
UPDATE products SET brand = 'Sweetest' WHERE name = 'Edulcorante Sweetest Doypack Reciclable x 200 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Endulzante Dulcilina Stevia Envase Reciclable x 200 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante Stevian Forte';
UPDATE products SET brand = 'Unknown' WHERE name = 'Linaza Molida Mucilagos Life System';
UPDATE products SET brand = 'Unknown' WHERE name = 'Arequipe Wepa Con Stevia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Toalla Alcoholada 70% alcohol 100unidades Two5med';
UPDATE products SET brand = 'Unknown' WHERE name = 'Apósito Adhesivo de silicona 10 cm x 20 cm x 1 Unidad Covalon';
UPDATE products SET brand = 'Pan' WHERE name = 'Media Panty de Compresión 18-23 mmHg Talla 5 Color Daino';
UPDATE products SET brand = 'Pan' WHERE name = 'Media Panty de Compresión 22-27 mmHg Talla 5 Color Daino';
UPDATE products SET brand = 'Pan' WHERE name = 'Media Panty de Compresión 22-27 mmHg Color Daino';
UPDATE products SET brand = 'Pan' WHERE name = 'Media Panty de Compresión 22-27 mmHg Talla 3 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Aimdent Sin Azucar Sabor Menta Verde 18 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Choco Sin Trigo Sin Lactosa Sin Azúcar Hola Granola x 300 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Papas Saludable Sin gluten El Valle Supreme';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acido Folico';
UPDATE products SET brand = 'Nutritek' WHERE name = 'L-Arginina Evolution 120capsulas Nutritek';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esparadrapo Quirurgico Pharmamed 5x5 1 Unidad';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Gambaletto 280 Den Talla 3 Color Daino';
UPDATE products SET brand = 'Ensure' WHERE name = 'Ensure Advance Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina + Pseudoefedrina 60/5 Mg Rinaris';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venda Elasticas 7Cm';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 100 mg Imazol Siegfried';
UPDATE products SET brand = 'Calox' WHERE name = 'Carvedilol 6,25mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobillera Elastica Kx 2 Vias Sin Talon L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Saludable Sin gluten Papas El Valle Sabor Ketchup';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cepillo Quirurgico Sol Desinf Bioscrub';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hola Granola Joy Sin Azucar- Sin Trigo - Sin Lactosa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ñam Suspiros Light Sabor Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen + Cafeina Analper Caf 500/40mg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Spray 70%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Granola Trail Mix Naturgourmet';
UPDATE products SET brand = 'Unknown' WHERE name = 'Te Nature Negro Libre de Azucar';
UPDATE products SET brand = 'Unknown' WHERE name = 'Barra de Proteina Dark NuGo Vainilla Yogurt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cuerda para Saltar Apolo Ajustable IV';
UPDATE products SET brand = 'CureBand' WHERE name = 'Curas CureBand Translucidas Venditas Standard x 30 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Munequera Neopreno Kx Estabilizadora Talla S/M';
UPDATE products SET brand = 'Europharm' WHERE name = 'Compresa Eurodressing Eurofarm 10 x 10 cm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Tela Impermeable 10Cm X 4,5M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bastón De 1 Punto Plegable DOVANT x 1 Unidad';
UPDATE products SET brand = 'K6' WHERE name = 'K6 Set de 3 Bandas Elasticas de Tela';
UPDATE products SET brand = 'Going' WHERE name = 'Hidratante Sabor Limonada De Coco Going Sachet x 10 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Atún Yoffi en Agua';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Leti' WHERE name = 'Acetaminofén + Dextrometorfano+ Fenilefrina + Clorfineramina Alivet Plus LETI x 10 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Chicle Aimdent Sin Azucar Sabor Fresa 18 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen Analper Forte 650 mg 10Tabletas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen 500mg 10tabletas';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gel Antibacterial Farmatodo 100 Ml';
UPDATE products SET brand = 'Balker' WHERE name = 'Solución ElectrolíticaSabor Mandarina  75 Meq/L Zinc Suerolit Balker Frasco x 400 ml';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Media de Compresión Dama Rodilla 18-23 mmHg Talla 5 Color Daino';
UPDATE products SET brand = 'Behrens' WHERE name = 'Solución Electrolítica 45meq Behrens Rehidrosol Fresa x 600 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Para Adultos Zuviss Mixtas Adhesivas x 20 und';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Kit Facial Fórmula Farmatodo Agua Micelar + Serum Acido Hialuronico + Contorno Ojos';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Jengibre + Eucalipto + Vitamina C ToFlem Naturlife''s Jarabe Expectorante Sin Azúcar x 240 ml';
UPDATE products SET brand = 'Genfar' WHERE name = 'Acetaminofen Genfar 500mg 10 Tabletas';
UPDATE products SET brand = 'Leti' WHERE name = 'Clindamicina 600 mg Genven';
UPDATE products SET brand = 'Pan' WHERE name = 'Pancreatina + Simeticona';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Alcohol Boricado x 120 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Pomada Boricada x 30 gr';
UPDATE products SET brand = 'Pan' WHERE name = 'Medias De Compresion Panty 140 Den Talla 4 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Eurofix 15cm x 2m Eurociencia';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Hypafix 10Cm X 10Mts';
UPDATE products SET brand = 'ASK' WHERE name = 'Yoga Mat TPE 6mm Ask';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Formula Gotas Farmatodo Valeriana';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema Facial Hidratante Colágeno x 30 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Solución Citrato De Potasio 10.8% x 500 ml';
UPDATE products SET brand = 'Behrens' WHERE name = 'Solución Electrolítica 45meq/l Behrens Rehidrosol Frambuesa x 600 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'N-Butilbromuro de Hioscina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pomada De Azufre al 0,05';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Crema Azufrada Al 5% x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromuro de Ipratropio -';
UPDATE products SET brand = 'Unknown' WHERE name = 'Soporte Neopreno Kx Para Muslo Talla P';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Gris +1,5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omega 3';
UPDATE products SET brand = 'Pharmacorp' WHERE name = 'Vitamina D3+K2 30tabletas Pharmacorp';
UPDATE products SET brand = 'Unknown' WHERE name = 'Papas Saludable Sin gluten El Valle Supreme sabor Trufa Negra';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quinoa Club Arepa Sin Gluten';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfato Disódico de Betametasona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol Mucomax';
UPDATE products SET brand = 'Optiko' WHERE name = 'Lente De Lectura Optiko Demi +2.5';
UPDATE products SET brand = 'Unknown' WHERE name = 'Guata Ortoban 20Cmx2,7Mts8"X3Yds';
UPDATE products SET brand = 'Unknown' WHERE name = 'Guata Ortoban 15Cmx2,7Mts6"X3Yds';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Desmaquillante Bifásico Frasco x 98 gr';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Jabón Ácido Láctico x 120 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Steritex Hidrofilo 100 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Algodon Hideven Rollo 10 Gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitamínico Prenatal Maternavit Medifarm';
UPDATE products SET brand = 'Unknown' WHERE name = 'Castaño de Indias';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Leukofix 5cm X 5m';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Alcohol Farmatodo Absoluto 1Lt';
UPDATE products SET brand = 'Unknown' WHERE name = 'Infusion Delta Moringa';
UPDATE products SET brand = 'Unknown' WHERE name = 'Atún Yoffi En Aceite Sin Gluten';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Gotas Farmatodo De Azahares 60Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostado The Pod Snacks Sabor A Crema y Cebolla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Protector Para Dedos Flents 12 UND';
UPDATE products SET brand = 'Unknown' WHERE name = 'Etoricoxib';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pulseras Anti Nauseas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Toallas Humedas Pulplus Antibacteriales Aloe Vera 40Und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azitromicina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Elegance 70% Alcohol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Traje De Sauna Jogger Pvc Negro Xxl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Liga Para Aerobic Jogger Trimmer';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Asiento Elevado para sanitario con apoya brazo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Cinta Microporosa Color Beige 1,2 Cm X 4,5 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Cinta Transparente 2,5 Cm X 4,5 M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Inmovilizador Para Dedo Talla L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Kx De Neopreno Ajustable Talla M';
UPDATE products SET brand = 'K6' WHERE name = 'Codera K6 Nivel 2 Talla L/XL';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sin Gluten Pasta Penne Rigate La Molisana';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofen 650mg 10 Tabletas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Elegance 70% Alcohol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Antiséptica Dioxogen Med Hipoalergénica x 230 ml';
UPDATE products SET brand = 'Aless Pharm' WHERE name = 'Meropenem 1 g Mespen Aless Pharmaceuticals Polvo para Solución Inyectable';
UPDATE products SET brand = 'Pan' WHERE name = 'Leprit Enzimatico Levosulpirida + Simeticona + Pancreatina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Acetaminofén + Clorferinamina';
UPDATE products SET brand = 'Pharmatech' WHERE name = 'Pancreatina + Proteasa + Amilasa Papaya Fruit Pharmatech Frasco x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vinagre De Manzana';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Magistral Farmatodo Gel Mentolado x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nifedipina 10 mg Nio Pharmaceutical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Hidroclorotiazida 12,5 mg Laboratorios Buka';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Cloruro De Sodio Fisiolin Oftalmi Solución Nasal Gotas x 15 ml';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Fórmula Farmatodo Pomada Azufre 10% Frasco x 30 gr';
UPDATE products SET brand = 'Pan' WHERE name = 'Mezcla Sin Gluten para Pan Vegan Life';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ácido Ascórbico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complejo B';
UPDATE products SET brand = 'Intervit' WHERE name = 'Linaza Molida Intervit con pina';
UPDATE products SET brand = 'Enterex' WHERE name = '!!Suplemento Alimenticio Enterex Total RPB Fresa Botella x 237 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Omeprazol 40 mg DN Medical Solución Inyectable';
UPDATE products SET brand = 'Unknown' WHERE name = 'HAR Atropina Ronatropine';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Cloruro De Sodio Fisiolin Oftalmi 260 Dosis Solución Fisiológica Nebulizador Nasal x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Doxiciclina 100 mg MT Global';
UPDATE products SET brand = 'Unknown' WHERE name = 'Linaza Molida Life System Con Avena';
UPDATE products SET brand = 'Dollder' WHERE name = 'Venlafaxina 75 mg Idoxen Dollder';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Cloruro de Sodio 0.9% IPS Frasco x 100 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Anís Estrellado Botica Casera Sobre x 5 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta Oro Sin Gluten Plumitas';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Miel Farmatodo De Borax 30Cc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Solución Ringer Lactato IPS Frasco x 500 ml';
UPDATE products SET brand = 'La Santé' WHERE name = 'Levofloxacina 500 mg La Sante';
UPDATE products SET brand = 'Unknown' WHERE name = 'Eucalipto + Rabano Pulmosan';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ñame Salvaje 300 mg Natural Premium Frasco x 60 Cápsulas';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Bora Farmatodo Sobre';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Pureza Original 1 L';
UPDATE products SET brand = 'Unknown' WHERE name = 'Loratadina';
UPDATE products SET brand = 'Leti' WHERE name = 'Sultamicilina 750 mg Genven';
UPDATE products SET brand = 'Bayer' WHERE name = 'Alka-Seltzer Bayer';
UPDATE products SET brand = 'Unknown' WHERE name = 'Parche Para Dolor Rodillas Medipatch x 12 und';
UPDATE products SET brand = 'Leti' WHERE name = 'Alivet Plus';
UPDATE products SET brand = 'Unknown' WHERE name = 'Multivitamínico + Resveratrol Uvavital Antioxidante Cosmelab Frasco x 30 Cápsulas';
UPDATE products SET brand = 'K6' WHERE name = 'Medias De Compresion Naranja K6 Talla L';
UPDATE products SET brand = 'K6' WHERE name = 'MEDIAS DE COMPRESION NARANJA K6 T-M';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Pomada Farmatodo Salicialda Al 20%';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Azul K6 Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C';
UPDATE products SET brand = 'Unknown' WHERE name = 'Plexamin';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Caracolito Nnova Rice';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Azul K6 Talla Xl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pentoxifilina 400 mg Psicofarma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metotrexato 2.5mg Trixate GP Pharma Blister x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Paletas para natacion Jogger Azl S-m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zarzaparrilla';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Aceite Farmatodo De Ricino 30Cc';
UPDATE products SET brand = 'CureBand' WHERE name = 'Curas CureBand Premium Impermeable Surtidas x 30 und';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tiras Adhesivas Cure Aid Foot Care Plaster Pharmalast 6 Unidades';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Silkplast 7.5Cm';
UPDATE products SET brand = 'VPD' WHERE name = 'VPD Andadera Reciprocal';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Dynamics universal Azul';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Forma Elastica Adulto Azul';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mun Forma elastica Forma E Universal Xl';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Forma elastica Pediatrico Ni?a';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cabestrillo Forma elastica Pediatrico Ni?o';
UPDATE products SET brand = 'Unknown' WHERE name = 'Papas Saludable Sin gluten El Valle Supreme';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mermelada St Dalfour';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antiinflamatorio Carprofedyl  Perros 100mg 10 Tabletas';
UPDATE products SET brand = 'Unknown' WHERE name = 'N-Butil-Bromuro de Hioscina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Meropenem';
UPDATE products SET brand = 'Europharm' WHERE name = 'Tira Eurosuture Eurofarm 6x75mm 6 Unidades';
UPDATE products SET brand = 'Ebben' WHERE name = 'Venda Economic 20Cm Ebben';
UPDATE products SET brand = 'Unknown' WHERE name = 'Gel Antibacterial Dioxogen Med Refrescante x 50 ml';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Ciprofloxacina 0,3% Quinotic Oftalmi Solución Ótica x 4 ml';
UPDATE products SET brand = 'Calox' WHERE name = 'Captopril 50 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nifedipina 30 mg Dac 55';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cefazolina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Leche de Soya Lactovisoy Vainilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pasta de Arroz Sin Gluten Lasaña Nnova Rice';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante Dulcilight';
UPDATE products SET brand = 'Europharm' WHERE name = 'Apósito Euroderm Foam Eurofarm 10x10cm x 1 und';
UPDATE products SET brand = 'Europharm' WHERE name = 'Adhesivo Eurosilk Eurofarm 2,5cm x 5m';
UPDATE products SET brand = 'Europharm' WHERE name = 'Adhesivo Europor Eurofarm 2,5Cm X 5M';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Unknown' WHERE name = 'Antiinflamatorio Carprofedyl perros 75mg 10 Tabletas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bisacodilo 5 mg Laxopro Eczane Pharma';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Betametasona+Clotrimazol+Neomicina 0,04g/1g/0,5g';
UPDATE products SET brand = 'Herbaplant' WHERE name = 'Piña Y Grappefrut Herbaplant 450 Mg X 60 Cápsulas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Creatina Monohidratada Varity Labs x 150 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fosfomemory 30capsulas Vit-Aminoacidos Pharmamerican';
UPDATE products SET brand = 'ASK' WHERE name = 'Morral plegable ASK';
UPDATE products SET brand = 'Pan' WHERE name = 'Linaza Pantera';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Now' WHERE name = 'Unknown';
UPDATE products SET brand = 'Europharm' WHERE name = 'Adhesivo Europor Eurofarm 1,25cm x 5m';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostados Sabor a Especias Arabes';
UPDATE products SET brand = 'Unknown' WHERE name = 'IntestVita Enzymes Vitae';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lente Lectura Redireaders Con Estuche +1.00';
UPDATE products SET brand = 'Farma' WHERE name = 'Betadine Iodo-Povidona Laboratorios Farma Jabón Liquido x 180 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol + Loratadina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betametasona 0,05% - Acido Salicilico 2% Betasalic Locion';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Forma elastica Universal Talla L';
UPDATE products SET brand = 'Farmatodo' WHERE name = 'Solucion Farmatodo Limpiador Cristales55Ml';
UPDATE products SET brand = 'Ana Maria Lajusticia' WHERE name = 'Ashwagandha + Rhodiola + Magnesio Triptofano Plus Ana María Lajusticia Frasco x 60';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rodillera Forma elastica Universal Talla S';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Beige Zuviss 2,5 cm x 9,10 m x 1 und';
UPDATE products SET brand = 'ASK' WHERE name = 'Porta celular para entrenamiento ASK';
UPDATE products SET brand = 'ASK' WHERE name = 'Codera ASK talla S/M';
UPDATE products SET brand = 'Unknown' WHERE name = 'Liga De Ejercicio Aerobica Body';
UPDATE products SET brand = 'Unknown' WHERE name = 'Obleas de Amaranto Vainilla Sin Azúcar Sin Gluten Halo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Mezcla De Maiz, Mani Y Merey';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Ácido Fólico 10 mg PlusAndex x 30';
UPDATE products SET brand = 'Leti' WHERE name = 'Losartán Potásico 50 mg Genven';
UPDATE products SET brand = 'FC Pharma' WHERE name = 'Vitamina E + Selenio 400UI-50mcg Seles FC Pharma';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina C Letisan Leti Solución Oral Sin Azúcar Gotas x 20 ml';
UPDATE products SET brand = 'Pan' WHERE name = 'Media Panty de Compresión 22-27 mmHg Talla 2 Color Daino';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zarzaparrilla';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diente De Leon';
UPDATE products SET brand = 'Colmed' WHERE name = 'Vitamina B6+B12+Acido Folico 30cap Colmed';
UPDATE products SET brand = 'Now' WHERE name = 'Omega 3-6-9 100capsulas Now';
UPDATE products SET brand = 'Himalaya' WHERE name = 'Sal Rosada del Himalaya con Molino Kaldini 390 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medias De Compresion Gambaletto 140 Den Talla 2 Color Daino';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Omeprazol 20 mg Medigen Oftalmi';
UPDATE products SET brand = 'K6' WHERE name = 'Mangas De Compresion Naranja K6 Talla XL';
UPDATE products SET brand = 'Going' WHERE name = 'Barra de Proteína Going Endurance Frutos Rojos x 60 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mango En Trozos Deshidratado Frusnack';
UPDATE products SET brand = 'Unknown' WHERE name = 'Snack Saludable Sin gluten Papas El Valle sabor Mediterraneo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Vitamina C+Zinc';
UPDATE products SET brand = 'Unknown' WHERE name = 'Alcohol Spray 70%';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Rela Cinta Microporosa Beige 2,5cmx10m';
UPDATE products SET brand = 'CureBand' WHERE name = 'Adhesivo CureBand';
UPDATE products SET brand = 'Unknown' WHERE name = 'Curitas Cure Band';
UPDATE products SET brand = 'Unknown' WHERE name = 'Edulcorante De Sucralosa Makea 50 Sachets';
UPDATE products SET brand = 'Unknown' WHERE name = 'Proteina Liq Powerful Coco';
UPDATE products SET brand = 'Naturlife' WHERE name = 'Artrovit Gel Naturlifes x 120 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Transparente Microperforado Zuviss 1,25cm x 9,10m';
UPDATE products SET brand = 'Leti' WHERE name = 'Vitamina C 500 mg Letisan Tiras x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Complemento Alimenticio ReConnect Vitae';
UPDATE products SET brand = 'Unknown' WHERE name = 'Garbanzos Tostado The Pod Snacks Sabor A Oregano';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fomentera Electrica Therma Heating Pad Regular Conaircomfort';
UPDATE products SET brand = 'Unknown' WHERE name = 'Adhesivo Silkplast';