UPDATE products SET brand = 'Rowe' WHERE name = 'Orlistat 120 mg Diecaps Rowe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Plidan Compuesto';
UPDATE products SET brand = 'Unknown' WHERE name = '**Salicilato de Bismuto 262 mg Pepsadel Laboratorios Fardel';
UPDATE products SET brand = 'Unknown' WHERE name = 'Amoxicilina';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina 5 mg Kimiceg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Drospirenona + Etinilestradiol';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Cetirizina 10 mg Celay Cofasa';
UPDATE products SET brand = 'Elmor' WHERE name = 'Albendazol 200 mg Albicar Elmor';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Desloratadina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Azitromicina';
UPDATE products SET brand = 'Galderma' WHERE name = 'Amorolfina 5% Loceryl Solución Laca Para Uñas Galderma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ambroxol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Suplemento Nutricional Singras Plus';
UPDATE products SET brand = 'Angelus' WHERE name = 'Metformina 500 mg Angelus Health';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Bisoprolol 2,5 mg Corentel Megalabs';
UPDATE products SET brand = 'Unknown' WHERE name = 'Butilbromuro De Hioscina 10 mg Lattan Medic';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betametasona Dipropinoato + Betametasona';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metformina 850 mg Biumak Pharmaceuticals';
UPDATE products SET brand = 'Biotech' WHERE name = 'Blocax Candesartán 16 mg Biotech x 30';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Bisoprolol 5 mg Corbis Siegfried';
UPDATE products SET brand = 'Unknown' WHERE name = 'Anflat';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sitagliptina + Metformina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sitagliptina + Metformina';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Complejo B Hepafol B12 Antianemico Siegfried';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fexofenadina';
UPDATE products SET brand = 'Calox' WHERE name = 'Festal Pancreatina Calox';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Oximetazolina Clorhidrato 0,05% Airfen Cofasa Gotas Nasales Adulto x 15 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Carbamazepina 200 mg Genven';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 200 mg Aless Pharmaceuticals';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol 100 mg Tiares';
UPDATE products SET brand = 'La Santé' WHERE name = 'Ciprofloxacina 500 mg La Sante x 10';
UPDATE products SET brand = 'Valmor' WHERE name = 'Cander Hct 16/12,5mg Candesartán';
UPDATE products SET brand = 'Unknown' WHERE name = 'Cefalexina';
UPDATE products SET brand = 'Leti' WHERE name = 'Pregabalina 150 mg Pegyt Leti';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Ciprofloxacina + Hidrocortisona 0.20%/1% Quinotic Hc Oftalmi Suspensión Ótica x 5 ml';
UPDATE products SET brand = 'Calox' WHERE name = 'Cefadroxilo 500 mg Calox';
UPDATE products SET brand = 'Leti' WHERE name = 'Clotrimazol 2% Genven Crema Vaginal x 20 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Captopril';
UPDATE products SET brand = 'Laproff' WHERE name = 'Colchicina 0.5 mg Laproff Blíster x 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorfeniramina + Dextrometorfano';
UPDATE products SET brand = 'Calox' WHERE name = 'Candesartán 16 mg Calox';
UPDATE products SET brand = 'La Santé' WHERE name = 'Cefadroxilo 500 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'PSI Clonozepam';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ciprofloxacina';
UPDATE products SET brand = 'Leti' WHERE name = 'Bisoprolol 2.5 mg Biotalol Leti';
UPDATE products SET brand = 'Leti' WHERE name = 'Bisoprolol 5 mg Biotalol Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Budesonida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromuro de Ipratropio 0,250mg/ml Teuto Frasco x';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Clotrimazol + Neomicina + Dexametasona 1,0%/0,50%/0,04% Clonedac DAC Crema x 20 gr';
UPDATE products SET brand = 'Biotech' WHERE name = 'Betametasona + Clotrimazol + Gentamicina Betaderm Plus Biotech Crema x';
UPDATE products SET brand = 'Leti' WHERE name = 'Bisoprolol 10 mg Biotalol Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bromhexina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diosmina + Hesperidina Femaven';
UPDATE products SET brand = 'Unknown' WHERE name = 'Valsartán 160 mg Valtan Zoriak';
UPDATE products SET brand = 'La Santé' WHERE name = 'Valsartán 80 mg La Santé';
UPDATE products SET brand = 'Leti' WHERE name = 'Diclofenac Potásico 100 mg Diklason A.P Leti';
UPDATE products SET brand = 'Calox' WHERE name = 'Deflazacort 6 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ivermectina';
UPDATE products SET brand = 'Rowe' WHERE name = 'Dexametasona + Neomicina + Polimixina Poli-Otico Rowe Gotas Óticas x 5 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diclofenac Potásico';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metronidazol + Miconazol + Lidocaína';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sulfadiazina De Plata Silverdin 1%/10Mg Tubo';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Bencidamina 0,15% Cofasa Frasco x 120 ml Solución Bucal';
UPDATE products SET brand = 'Leti' WHERE name = 'Nitazoxanida 500 mg Zontricon Leti';
UPDATE products SET brand = 'Plusandex' WHERE name = 'Secnidazol 500 mg Secnidex PlusAndex';
UPDATE products SET brand = 'Vivax' WHERE name = 'Nitazoxanida 500 mg Nytaxin Vivax';
UPDATE products SET brand = 'Megalabs' WHERE name = 'Diltiazem 60 mg Daltazen Megalabs';
UPDATE products SET brand = 'Leti' WHERE name = 'Trimebutina 300 mg Dobracid LP Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Quetiapina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Enantato de Noretisterona + Estradiol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Betasol';
UPDATE products SET brand = 'Valmor' WHERE name = 'Risperidona 1 mg Esquidone Valmor';
UPDATE products SET brand = 'Laproff' WHERE name = 'Fluconazol 200 mg Laproff Blíster x 4 Cápsulas';
UPDATE products SET brand = 'La Santé' WHERE name = 'Solunovar compuesto';
UPDATE products SET brand = 'Unknown' WHERE name = 'Lisina + Ergotamina';
UPDATE products SET brand = 'Leti' WHERE name = 'Fluconazol 150 mg Genven';
UPDATE products SET brand = 'Valmor' WHERE name = 'Lamotrigina 100 mg Epitral Valmorca';
UPDATE products SET brand = 'Unknown' WHERE name = 'Simvastatina + Ezetimiba';
UPDATE products SET brand = 'Valmor' WHERE name = 'Lamotrigina 50 mg Epitral Valmor';
UPDATE products SET brand = 'Valmor' WHERE name = 'Risperidona 2 mg Esquidone Valmor';
UPDATE products SET brand = 'Elmor' WHERE name = 'Fenticonazol 2% Mycofentin Elmor Tubo x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Furosemida 20 mg Lasix Mck Pharmaceutical';
UPDATE products SET brand = 'La Santé' WHERE name = 'Flavoxato Clorhidrato 200 mg La Sante';
UPDATE products SET brand = 'Unknown' WHERE name = 'Famotidina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Furosemida 40 mg Lasix MCK Pharmaceutical';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fexofenadina + Pseudoefedrina';
UPDATE products SET brand = 'Rowe' WHERE name = 'Flunarizina 10 mg Misellim Rowe';
UPDATE products SET brand = 'Rowe' WHERE name = 'Fluconazol 150 mg Flucon Rowe';
UPDATE products SET brand = 'Biotech' WHERE name = 'Carvedilol 12.5 mg Carbatil Biotech';
UPDATE products SET brand = 'Unknown' WHERE name = 'Clorfeniramina + Kanamicina + Fenilefrina 2,5/2,5/1,25mg Rinomax Solución Nasal x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nitazoxanida';
UPDATE products SET brand = 'Unknown' WHERE name = 'Diecaps';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mentol Davis Ungüento Lata x 28.3 gr';
UPDATE products SET brand = 'Kimiceg' WHERE name = 'Secnidazol 500 mg Kimiceg';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dapagliflozina 10 mg Diapaglix10 DPT';
UPDATE products SET brand = 'Unknown' WHERE name = 'Dextrometorfano Tilodrin Frasco x 120 ml Jarabe';
UPDATE products SET brand = 'La Santé' WHERE name = 'Levosulpiride 25 mg La Santé';
UPDATE products SET brand = 'Unknown' WHERE name = 'Piridoxina + Doxilamina';
UPDATE products SET brand = 'Biotech' WHERE name = 'Desonida 0.05% Erilon Biotech Crema x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Desonida + Clioquinol 0,1/0,3% Dermosupril C Medihealth Crema x 15 gr';
UPDATE products SET brand = 'Calox' WHERE name = 'Fluconazol 150 mg Calox';
UPDATE products SET brand = 'Unknown' WHERE name = 'Flebosmin';
UPDATE products SET brand = 'Rowe' WHERE name = 'Hierro 40 mg Ferganic Rowe';
UPDATE products SET brand = 'Unknown' WHERE name = 'Pomada Corporal Alcanfor + Mentol + Eucalipto Mentorub x 30 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Memantina 20 mg Eutebrol Tecnofarma';
UPDATE products SET brand = 'Elmor' WHERE name = 'Trazodone 50 mg Trittico Elmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Metoclopramida Farmionni';
UPDATE products SET brand = 'Unknown' WHERE name = 'Fisiolin';
UPDATE products SET brand = 'Angelus' WHERE name = 'Rosuvastatina 20 mg Angelus Health';
UPDATE products SET brand = 'Unknown' WHERE name = 'Micoativ 1% Crema Topica';
UPDATE products SET brand = 'Dollder' WHERE name = 'Pantoprazol Inibil 40 mg Dollder';
UPDATE products SET brand = 'Dollder' WHERE name = 'Pantoprazol Inibil 20 mg Dollder x 14';
UPDATE products SET brand = 'Leti' WHERE name = 'Tamsulosina 0.4 mg Tamostin L.P Leti';
UPDATE products SET brand = 'Unknown' WHERE name = 'Venlafaxina Idoxen';
UPDATE products SET brand = 'Unknown' WHERE name = 'Micoderm Soma';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Oximetazolina 0,05% Clarix Oftalmi Solución Nasal Gotas x 15 ml';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Oximetazolina 0,25% Clarix Oftalmi Solución Nasal Pediátrica x 15 ml';
UPDATE products SET brand = 'Leti' WHERE name = 'Oximetazolina 0,05% Nasin Leti Solución Nasal Gotas x 15 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Misulvan 7.5mg/ml solución gotas';
UPDATE products SET brand = 'Unknown' WHERE name = 'Merthiolate 0,13% atomizador';
UPDATE products SET brand = 'Valmor' WHERE name = 'PSI Alprazolam 2 mg Alpram Valmorca';
UPDATE products SET brand = 'Valmor' WHERE name = 'PSI Alprazolam  1 mg Alpram Valmor';
UPDATE products SET brand = 'Unknown' WHERE name = 'Plucbiotic Probiotico Multicepa con Preiotico Selenio Zinc y Vit C';
UPDATE products SET brand = 'Valmor' WHERE name = 'PSI Alprazolam 0,5 mg Alpram Valmor';
UPDATE products SET brand = 'Colmed' WHERE name = 'Pantoprazol 40 mg Colmed';
UPDATE products SET brand = 'Unknown' WHERE name = 'Propranolol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Prucaloprida 1 mg Diploz MCK Pharmaceutical';
UPDATE products SET brand = 'Dollder' WHERE name = 'Ranitidina 75 mg Vizerul Dollder';
UPDATE products SET brand = 'Unknown' WHERE name = 'Misoprostol 200 mcg Mt Global Care x 4';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mupirocin 2% Unguento 15 g SGG';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mupirocin 2% Presiderm Medihealth Ungüento x 15 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Medihealth Dermosupril 0,05% Desonida Emulsion';
UPDATE products SET brand = 'Unknown' WHERE name = 'Melax Polvo';
UPDATE products SET brand = 'Unknown' WHERE name = 'Mucolipto';
UPDATE products SET brand = 'Unknown' WHERE name = 'Neodia 1,5mg 1 Comprimido Levonorgestrel Neoquimica';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Nafazolina 0,12mg/ml Clarasol Ofatlmi Gotas Oftálmicas x 15 ml';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Noxpirin Dia Acetaminofén + Fenilefrina Granulado Mandarina 15 gr x 6';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nimesulide';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nimesulide Reduben 100 Mg X 10';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nistatina + Oxido de Zinc Oxyderme 100.000UI/g-200mg/g Pomada 60 Gr';
UPDATE products SET brand = 'GreenPharma' WHERE name = 'Nitrofurazona 0,20g/100g Fuxal GreenPharma';
UPDATE products SET brand = 'Unknown' WHERE name = 'Nafazolina 0,1% Fanasal Gotas Nasales Adulto x 15 ml';
UPDATE products SET brand = 'Oftalmi' WHERE name = 'Nafazolina 0,05% NAS Oftalmi Gotas Nasales Pediatrico x 15 ml';
UPDATE products SET brand = 'Cofasa' WHERE name = 'Oximetazolina 0,025% Airfen Cofasa Gotas Pediátricas x 15 ml';
UPDATE products SET brand = 'Colmed' WHERE name = 'Pantoprazol Colmed';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tobramicina-Dexametasona 0,3%-0,1%';
UPDATE products SET brand = 'Polinac' WHERE name = 'Polantac antiacido 30tabletas Magnesio Polinac';
UPDATE products SET brand = 'Valmor' WHERE name = 'PSI Clonazepam 2 mg Clonzep Valmor';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Perten 1% Terbinafina Siegfried Tubo x 20 gr';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rifamicina 1% Zukati Solución Atomizadora x 25 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Tachigrip Acetaminofén + Cafeína + Dexclorfeniramina';
UPDATE products SET brand = 'Behrens' WHERE name = 'Solución Cloruro de Sodio 0,9% Flexi-Behr Behrens Frasco x 500 ml';
UPDATE products SET brand = 'Unknown' WHERE name = 'Rogastril Plus 200 MG x';
UPDATE products SET brand = 'Unknown' WHERE name = 'Zolpidem';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sitagliptina 100 mg x 30';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sucralfato';
UPDATE products SET brand = 'Unknown' WHERE name = 'Sulfadiazina de plata 1% + Lidocaina 0,6% Platsiderm Crema';
UPDATE products SET brand = 'Mallen' WHERE name = 'Salbutamol 100mcg Salbutral + Camara Aeromed Aerosol Mallen x 250 Dosis';
UPDATE products SET brand = 'Zuzu' WHERE name = 'Acido Ursodesoxicolico 300 mg Laboratorios Zuzu x 10';
UPDATE products SET brand = 'Siegfried' WHERE name = 'Acetilcisteína 600 mg Acemuk Siegfried';
UPDATE products SET brand = 'Calox' WHERE name = 'Fexofenadina 120 mg Calox';
UPDATE products SET brand = 'Colmed' WHERE name = 'Pantoprazol 20 mg Colmed';
UPDATE products SET brand = 'Unknown' WHERE name = 'Esomeprazol';
UPDATE products SET brand = 'Unknown' WHERE name = 'Famotidina + Magnesio + Calcio Kalmax Compositum Antiácido';
UPDATE products SET brand = 'Unknown' WHERE name = 'Ranitidina';
UPDATE products SET brand = 'Unknown' WHERE name = 'Bacitracina 500 UI';